define([], function anonymous(
) {
var pluralFuncs = {
  en: function(n, ord) {
    var s = String(n).split('.'), v0 = !s[1], t0 = Number(s[0]) == n,
        n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2);
    if (ord) return (n10 == 1 && n100 != 11) ? 'one'
        : (n10 == 2 && n100 != 12) ? 'two'
        : (n10 == 3 && n100 != 13) ? 'few'
        : 'other';
    return (n == 1 && v0) ? 'one' : 'other';
  }
};
var fmt = {};
var number = function(value, offset) {
  if (isNaN(value)) throw new Error("'" + value + "' isn't a number.");
  return value - (offset || 0);
};
var plural = function(value, offset, lcfunc, data, isOrdinal) {
  if ({}.hasOwnProperty.call(data, value)) return data[value]();
  if (offset) value -= offset;
  var key = lcfunc(value, isOrdinal);
  if (key in data) return data[key]();
  return data.other();
};
var select = function(value, data) {
  if ({}.hasOwnProperty.call(data, value)) return data[value]();
  return data.other()
};

return {
  "general.a_text_message_will_be": function(d) { return "A text message will be sent to confirm your participation.  You must reply <strong>YES</strong> to confirm your subscription to complete the sign-up process."; },
  "general.activity": function(d) { return "Activity"; },
  "general.add_coupon": function(d) { return "Add Coupon"; },
  "general.add_item": function(d) { return "Add Item"; },
  "general.add_items": function(d) { return "Add Items"; },
  "general.add_items_to_this_coupon": function(d) { return "Add items to this coupon"; },
  "general.afternoon": function(d) { return "Afternoon"; },
  "general.all_pizzas": function(d) { return "All Pizzas"; },
  "general.all_two_topping": function(d) { return "All large 2-topping pizzas $5.99 each"; },
  "general.an_easy_order_is_the": function(d) { return "An Easy Order is the fastest way to order from Domino's. What you want, how you want to get it, and how you want to pay for it is all saved so it's simpler than ever to order next time."; },
  "general.and": function(d) { return "and"; },
  "general.and_you_are_already_enrolled": function(d) { return "And you are already enrolled to have our hot text offers delivered right to <span class=\"js-phone\">" + d.phone + "</span>!"; },
  "general.apply_now": function(d) { return "Apply Now"; },
  "general.april": function(d) { return "April"; },
  "general.are_you_sure_you_want": function(d) { return "Are you sure you want to remove the Easy Order \"" + d.easyOrderNickname + "\"?"; },
  "general.area": function(d) { return "Districts"; },
  "general.at_menu_price": function(d) { return "At Menu Price"; },
  "general.august": function(d) { return "August"; },
  "general.av_meet_here": function(d) { return "Meet here"; },
  "general.back_to_sign_in": function(d) { return "Back to sign in"; },
  "general.back_to_tracker": function(d) { return "Back to Tracker"; },
  "general.become_a_member": function(d) { return "Become a Member"; },
  "general.birthday": function(d) { return "Birthday"; },
  "general.bogo_popup_at_menu_price": function(d) { return "at menu price"; },
  "general.bogo_popup_buy_one_pizza": function(d) { return "buy one pizza"; },
  "general.bogo_popup_get_one_free": function(d) { return "get one free"; },
  "general.bogo_popup_legal": function(d) { return "Valid " + d.dateRange + ". Second pizza of equal or lesser value for free.  Applies to menu priced pizza ordered online."; },
  "general.bogo_popup_of_equal_value": function(d) { return "of equal or lesser value"; },
  "general.bogo_popup_online_carryout_only": function(d) { return "online and carryout only"; },
  "general.by_tracking_your_order_you": function(d) { return "By tracking your order you agree to our <a class=\"js-isTemplatePopup\" data-template-popup=\"contentPageTerms\" href=\"" + d.ctx + "/" + "#" + "!/content/terms/\">Terms of Use</a> and that you are at least 14 years old."; },
  "general.call_back_phone_number": function(d) { return "Call Back Phone Number"; },
  "general.call_center": function(d) { return ""; },
  "general.carryout": function(d) { return "Carryout"; },
  "general.carryout_only": function(d) { return "Carryout only"; },
  "general.carryout_tips_3_off": function(d) { return "$3 off"; },
  "general.carryout_tips_3_off_html": function(d) { return ""; },
  "general.carryout_tips_3_off_modal": function(d) { return "$3 off"; },
  "general.carryout_tips_3_online_tip": function(d) { return "$3 Online tip"; },
  "general.carryout_tips_abbreviated_legal": function(d) { return "Offer applies to online carryout orders placed on or before 04/09/23. Claim a $3 code by Sunday of the same week the order was placed. Codes redeemable for an online carryout order of $5 or more during the next week. You may be responsible to pay sales tax on the $3 tip. Prices, participation and charges may vary. For complete details visit carryouttips.com."; },
  "general.carryout_tips_by_claiming_this_code": function(d) { return "By claiming this code, you agree to receiving up to 2 emails related to this offer."; },
  "general.carryout_tips_carryout_online": function(d) { return "Carryout online"; },
  "general.carryout_tips_check_your_email_for": function(d) { return "Check your email for"; },
  "general.carryout_tips_claim_it_on_next_screen": function(d) { return "Claim it on the next screen!"; },
  "general.carryout_tips_claim_your_3_tip": function(d) { return "Claim your $3 tip"; },
  "general.carryout_tips_claim_your_3_tip_online": function(d) { return "Claim your $3 tip online"; },
  "general.carryout_tips_claim_your_tip": function(d) { return "Order carryout online and claim your $3 tip now"; },
  "general.carryout_tips_claim_your_tip_2": function(d) { return ""; },
  "general.carryout_tips_claim_your_tip_now": function(d) { return "Claim your tip now"; },
  "general.carryout_tips_claim_your_tip_pre": function(d) { return "Claim your tip"; },
  "general.carryout_tips_combine_coupons": function(d) { return "Combine it with other coupons"; },
  "general.carryout_tips_combine_your_3_off": function(d) { return "Combine your $3 off"; },
  "general.carryout_tips_congrats": function(d) { return "Congrats!"; },
  "general.carryout_tips_currency_amount": function(d) { return "3"; },
  "general.carryout_tips_currency_symbol": function(d) { return "$"; },
  "general.carryout_tips_delivery_driver": function(d) { return "delivery driver"; },
  "general.carryout_tips_dont_forget": function(d) { return "Don't forget"; },
  "general.carryout_tips_dont_forget_exclamation": function(d) { return "Don't forget!"; },
  "general.carryout_tips_dont_forget_to_claim": function(d) { return "Don't forget to claim it on the next screen!"; },
  "general.carryout_tips_earned_dough": function(d) { return "earned some dough!"; },
  "general.carryout_tips_earned_some_dough": function(d) { return "Earned some dough"; },
  "general.carryout_tips_for_being_your": function(d) { return "For being your"; },
  "general.carryout_tips_for_your_tip_on_next_order": function(d) { return "For your $3 tip on next week's online carryout order"; },
  "general.carryout_tips_get_3_off": function(d) { return "Get $3 off"; },
  "general.carryout_tips_get_3_off_2": function(d) { return ""; },
  "general.carryout_tips_good_news": function(d) { return "Good News!"; },
  "general.carryout_tips_here_is_your_discount": function(d) { return "here is your discount"; },
  "general.carryout_tips_legal": function(d) { return "Domino’s Carryout Tips offer applies to online carryout orders only. Orders placed on or before 04/09/23 will be eligible to claim a $3 coupon code until Sunday of the same week the order was placed. Coupon codes may be redeemed for a future online carryout order placed the following Monday through Sunday. Minimum purchase of $5 (after tax, not including donations and gratuities) required when redeeming this coupon code. You may be responsible to pay sales tax on the $3 tip. Prices, participation and charges may vary. Limit: One coupon code may be claimed and redeemed per day."; },
  "general.carryout_tips_next_week": function(d) { return "Again Next Week"; },
  "general.carryout_tips_next_week_get": function(d) { return ""; },
  "general.carryout_tips_next_week_to_get": function(d) { return "Next week to get"; },
  "general.carryout_tips_next_week_when_you": function(d) { return "Next week when you"; },
  "general.carryout_tips_next_weeks_order": function(d) { return "Next week's online carryout order"; },
  "general.carryout_tips_one_time_use": function(d) { return "One time use only. Valid next Mon-Sun"; },
  "general.carryout_tips_order_again_online": function(d) { return "Order Again Online"; },
  "general.carryout_tips_order_carryout": function(d) { return "Order Carryout"; },
  "general.carryout_tips_order_online_carryout": function(d) { return "Order carryout online"; },
  "general.carryout_tips_order_qualifies": function(d) { return "your order qualifies for a <span class='carryout-tip-account-creation-tile__tip'><span class='carryout-tip-account-creation-tile__tip-dollar'>$</span>3 tip</span>"; },
  "general.carryout_tips_own": function(d) { return "own"; },
  "general.carryout_tips_this_offer_valid_for": function(d) { return "This offer is only valid for"; },
  "general.carryout_tips_this_promo_code": function(d) { return "this promo code"; },
  "general.carryout_tips_to_get": function(d) { return "To get"; },
  "general.carryout_tips_to_use_on_next_weeks_order": function(d) { return "To use on next week's order"; },
  "general.carryout_tips_to_use_when": function(d) { return ""; },
  "general.carryout_tips_toward_next_weeks_order": function(d) { return "Toward next week's online carryout order"; },
  "general.carryout_tips_valid_only": function(d) { return "Valid Only 01/31 - 05/22"; },
  "general.carryout_tips_we_are_emailing_you": function(d) { return "We're emailing you this promo code"; },
  "general.carryout_tips_we_are_sending_code_to": function(d) { return "We're sending a promo code to:"; },
  "general.carryout_tips_we_just_emailed_you_a_promo_code": function(d) { return "We just emailed you a promo code"; },
  "general.carryout_tips_we_just_sent_you_your": function(d) { return "We just sent you your"; },
  "general.carryout_tips_we_want_to_tip_you": function(d) { return "We want to tip you"; },
  "general.carryout_tips_we_want_to_tip_you_2": function(d) { return ""; },
  "general.carryout_tips_we_want_to_tip_you_modal": function(d) { return "We want to tip you"; },
  "general.carryout_tips_when_you_carry_out": function(d) { return "when you carry out"; },
  "general.carryout_tips_when_you_carryout_next_week": function(d) { return "When you order carryout online next week"; },
  "general.carryout_tips_when_you_order": function(d) { return "when you order"; },
  "general.carryout_tips_when_you_order_carryout_online_next_week": function(d) { return "When you order carryout online next week"; },
  "general.carryout_tips_when_you_order_online": function(d) { return ""; },
  "general.carryout_tips_with_any_other_coupon": function(d) { return "With any other coupon"; },
  "general.carryout_tips_you_just": function(d) { return "You just"; },
  "general.carryout_tips_your_online_promo_code": function(d) { return "Your online promo code"; },
  "general.carryout_tips_your_order_placed": function(d) { return "Your order has been placed!"; },
  "general.cart": function(d) { return "Cart"; },
  "general.caution": function(d) { return "Caution!"; },
  "general.celebra": function(d) { return "Calebra"; },
  "general.checkin": function(d) { return "Check In"; },
  "general.checkout": function(d) { return "Checkout"; },
  "general.click_here": function(d) { return "Click here"; },
  "general.close": function(d) { return "Close"; },
  "general.close_modal": function(d) { return "Close modal"; },
  "general.coca_cola": function(d) { return "Coca-Cola"; },
  "general.collapse": function(d) { return "Collapse"; },
  "general.complete": function(d) { return "Complete"; },
  "general.condiments": function(d) { return "Condiments"; },
  "general.confirm_address": function(d) { return "confirm address"; },
  "general.congratulations_firstname_your_pizza_profile": function(d) { return "Congratulations " + d.firstName + "! Your Pizza Profile has been created."; },
  "general.contact_us": function(d) { return "Contact Us"; },
  "general.continue": function(d) { return "Continue"; },
  "general.continue_as_guest": function(d) { return "Continue as guest"; },
  "general.continue_checkout": function(d) { return "Continue Checkout"; },
  "general.continue_ordering": function(d) { return "Continue Ordering"; },
  "general.continue_shopping": function(d) { return "Continue shopping"; },
  "general.continue_to_site": function(d) { return "Continue to site"; },
  "general.continue_with_cart": function(d) { return "continue with cart"; },
  "general.coupon": function(d) { return "Coupon"; },
  "general.coupon_incomplete": function(d) { return "Coupon Incomplete"; },
  "general.coupon_selected": function(d) { return "Coupon Selected!"; },
  "general.coupon_service_method_warning": function(d) { return "<p>The coupon you picked is for <em>" + d.currentServiceMethod + "</em> orders only. If you'd rather order <em>" + d.nextServiceMethod + "</em>, we found a coupon for you.</p><p><strong>For " + d.nextServiceMethod + ":</strong> " + d.couponDescription + "</p>"; },
  "general.coupon_service_method_warning_cancel": function(d) { return "Order " + d.currentServiceMethod; },
  "general.coupon_service_method_warning_carryout": function(d) { return "Carryout"; },
  "general.coupon_service_method_warning_confirm": function(d) { return "Order " + d.nextServiceMethod; },
  "general.coupon_service_method_warning_delivery": function(d) { return "Delivery"; },
  "general.coupon_wizard": function(d) { return "Coupon Wizard"; },
  "general.coupon_wizard_coupon_applied": function(d) { return "Coupon Applied"; },
  "general.coupons": function(d) { return "Coupons"; },
  "general.create_one": function(d) { return "Create one"; },
  "general.create_profile": function(d) { return "Create Profile"; },
  "general.create_your_pizza_profile": function(d) { return "Create your pizza profile and enroll in piece of the pie rewards"; },
  "general.create_your_pizza_profileCA": function(d) { return "Create your pizza profile and enroll in piece of the pie rewards<sup>&reg;</sup>"; },
  "general.create_your_profile": function(d) { return "Create Your Profile"; },
  "general.creating_an_easy_order": function(d) { return "Creating an Easy Order"; },
  "general.credit_card": function(d) { return "Credit Card"; },
  "general.customerNameTax": function(d) { return ""; },
  "general.customize": function(d) { return "Customize"; },
  "general.date": function(d) { return "Date"; },
  "general.day": function(d) { return "day"; },
  "general.december": function(d) { return "December"; },
  "general.delivering_dairy_goodness": function(d) { return "Delivering Dairy Goodness"; },
  "general.delivery": function(d) { return "Delivery"; },
  "general.diners": function(d) { return "Diners Club"; },
  "general.discounted_price_with_mix_and_match": function(d) { return "Discounted price with Mix and Match"; },
  "general.dominos": function(d) { return "Domino's"; },
  "general.dominos_pizza": function(d) { return "Domino's Pizza"; },
  "general.dominos_pizza_made_with_a": function(d) { return "According to our most recent assessment of scientific data, foods containing gluten levels not exceeding 20 PPM would not pose a health risk to the vast majority of individuals with Celiac Disease or to individuals with gluten sensitivity. The level of gluten found in our pizza made with Gluten Free Crust is below 20 PPM. However, Domino's pizza made with a Gluten Free Crust is prepared in a common kitchen with the risk of gluten exposure. Therefore, Domino's DOES NOT recommend this pizza for customers with Celiac Disease. Customers with gluten sensitivities should exercise judgement in consuming this pizza.<br>Note: Gluten free crust may be subject to an additional charge."; },
  "general.dominos_tracker_copyright": function(d) { return ""; },
  "general.dont_have_a_pizza_profile": function(d) { return "Don't have a Pizza Profile?"; },
  "general.dont_have_one_create_one": function(d) { return "Don't have one? <a href=\"" + d.ctx + "/pages/rewards/" + "#" + "!/create-profile/?enrollnow=true&EnrollmentSourceTag=" + d.enrollmentSourceTag + "\" class=\"btn--arrow createAccount js-createProfile c-createprofile-link\">Create one</a>"; },
  "general.dowload_menu": function(d) { return ""; },
  "general.download_the_app": function(d) { return "DOWNLOAD THE APP"; },
  "general.driver_callback_warning": function(d) { return "**IMPORTANT:** You may receive a call from your store to verify your order."; },
  "general.driver_callback_warning_no_answer": function(d) { return "If you do not answer, your order may be delayed or cancelled."; },
  "general.each_browser_has_different_steps_required_for_upgrading": function(d) { return "Each browser has different steps required for upgrading. Follow the links below for instructions on updating your browser."; },
  "general.earn_free_pizza_and_checkout_faster": function(d) { return "Earn free pizza, get exclusive deals, and check out faster!​"; },
  "general.easy_order": function(d) { return "Easy Order"; },
  "general.easy_order_instructions": function(d) { return "<ol><li>1. Add products to your order.</li><li>2. Go to checkout.</li><li>3. While checking out, look for the option to save your order as your Easy Order.<div class=\"center\"><img src=\"" + d.assets_ctx + "/images/img/easy_order_checkbox.jpg\" /></div></li><li>4. Place your order and we&apos;ll save it as your Easy Order!</li></ol>"; },
  "general.easy_order_instructions_1": function(d) { return "Add products to your order."; },
  "general.easy_order_instructions_2": function(d) { return "Go to checkout."; },
  "general.easy_order_instructions_3": function(d) { return "While checking out, look for the option to save your order as your Easy Order. See example below:"; },
  "general.easy_order_instructions_4": function(d) { return "Place your order and we&apos;ll save it as your Easy Order!"; },
  "general.easy_order_instructions_flag_alt_text": function(d) { return "Picture of a flag representing easy order."; },
  "general.ecom47364_curbside_exclusive_offer": function(d) { return "This Curbside Pickup exclusive offer is only available between 4 to 9 PM local time."; },
  "general.ecom51405_carryout_tips_cart_legal": function(d) { return "Domino’s Carryout Tips offer applies to online carryout orders only. Orders placed before 5/22/22 will be eligible to claim a $3 coupon code until Sunday of the same week the order was placed. Coupon codes may be redeemed for a future online carryout order placed the following Monday through Sunday. Minimum purchase of $5 (including tax, not including donations and gratuities) required when redeeming this coupon code. Prices, participation and charges may vary. Limit: One coupon code may be claimed and redeemed per day."; },
  "general.ecom65403_available_items": function(d) { return ""; },
  "general.ecom65403_carousel_instructions": function(d) { return ""; },
  "general.ecom65403_item_x_of_y": function(d) { return ""; },
  "general.ecom65403_next_item": function(d) { return ""; },
  "general.ecom65403_previous_item": function(d) { return ""; },
  "general.ecom65403_product_for_price": function(d) { return ""; },
  "general.ecom65403_product_for_price_with_discount": function(d) { return ""; },
  "general.ecom69775_find_a_store": function(d) { return "Find a Store"; },
  "general.ecom69775_select_a_dominos": function(d) { return "Select a Domino's store to see pricing in your area."; },
  "general.emailOffers": function(d) { return "Domino's delivers terrific deals through email messaging. Review your subscription status"; },
  "general.email_offers": function(d) { return "Email Offers"; },
  "general.emergency_pizza_all_yours": function(d) { return "That Free Pizza Is All Yours!"; },
  "general.emergency_pizza_claim_free_pizza": function(d) { return "Claim Free Pizza"; },
  "general.emergency_pizza_congrats": function(d) { return "Congrats!"; },
  "general.emergency_pizza_find_it_now": function(d) { return "Find it now in my deals & rewards"; },
  "general.emergency_pizza_free_pizza": function(d) { return "Free Pizza"; },
  "general.emergency_pizza_legal_copy": function(d) { return "Loyalty members may redeem this offer for a free medium, 2-topping pizza with their next online order. Handmade Pan Pizza will be extra. Offer earned with online carryout orders ($7.99 or more) or with an online delivery order that meets the local store’s delivery min. Excludes orders placed through Domino's Anyware platforms, iPad® app or for future orders. Limit one offer per loyalty account. Must claim offer within 7 days from the date earned. Offer is not transferable and must be redeemed within 30 days of claiming. Redeem at the My Deals and Rewards page in your loyalty account. Redemptions for delivery must meet the local store’s delivery minimum requirement."; },
  "general.emergency_pizza_take_me_there": function(d) { return "Take Me There"; },
  "general.emergency_pizza_you_earned_a": function(d) { return "You Earned A"; },
  "general.enter_and_confirm_your_details": function(d) { return "Enter and confirm your profile details"; },
  "general.enter_and_confirm_your_email": function(d) { return "Enter and confirm your email and password, you'll need them to sign in later."; },
  "general.enter_location": function(d) { return "Enter your location to connect to your local Domino's and build your order."; },
  "general.error_404_back_to_main": function(d) { return "<a href=\"" + d.ctx + "/\">Click Here</a> to go back to Dominos.ca"; },
  "general.error_404_page_not_found": function(d) { return "Somewhere along the way the page you are looking for went missing. Take a look at the URL you typed and make sure it's correct."; },
  "general.error_404_try_again": function(d) { return "If you got here by clicking a link, try back a little later. We move pretty fast, so odds are it'll be back shortly."; },
  "general.error_404_where_am_i": function(d) { return "Where... Am I?"; },
  "general.evening": function(d) { return "Evening"; },
  "general.expand": function(d) { return "Expand"; },
  "general.explore_app_gallery": function(d) { return "Explore on App Gallery"; },
  "general.ext": function(d) { return "Ext."; },
  "general.extend_session": function(d) { return "Yes, extend session"; },
  "general.february": function(d) { return "February"; },
  "general.fifty_percent_off": function(d) { return "50% Off"; },
  "general.find_a_location": function(d) { return "Find a Location"; },
  "general.first_name_string": function(d) { return "<a data-quid=\"site-nav-user-name\" href=\"" + d.ctx + "/pages/customer/" + "#" + "!/customer/profile/\" aria-label=\"" + d.firstName + " - view profile\"class=\"site-nav__profile__welcome-user js-userName\">" + d.firstName + "</a>."; },
  "general.follow_the_steps_below_to_be_sure_you_have_the_most_up_to_date_mobile_browser": function(d) { return "Follow the steps below to be sure you have the most up to date mobile browser."; },
  "general.follow_us": function(d) { return "Follow us"; },
  "general.footer_privacy_updated": function(d) { return "<span class=\"underline\">Domino's Privacy Policy has been revised effective May 25, 2018.</span> The policy has been revised as new data protection regulations come into effect in the European Union. The revised policy will make it easier to understand the choices available to you. <a href=\"" + d.ctx + "/" + "#" + "!/content/privacy/\">Click Here</a> to review the revised Privacy Policy."; },
  "general.for": function(d) { return "for"; },
  "general.forgot_password": function(d) { return "Forgot password?"; },
  "general.forgot_your_password": function(d) { return ""; },
  "general.franchise": function(d) { return "Franchise"; },
  "general.from_list": function(d) { return ""; },
  "general.garlic_parmesan_white_sauce": function(d) { return "garlic parmesan white sauce"; },
  "general.get_faster_access_to_your": function(d) { return "Get faster access to your profile features such as recent orders and saved addresses."; },
  "general.get_started": function(d) { return "Get Started"; },
  "general.go_create_your_applet": function(d) { return ""; },
  "general.go_to_checkout": function(d) { return "Go to checkout"; },
  "general.got_it_thanks": function(d) { return "Got It. Thanks."; },
  "general.got_it_thanks_comma": function(d) { return "Got it, thanks"; },
  "general.got_your_order": function(d) { return "we got your order!"; },
  "general.great_choice": function(d) { return "Great Choice!"; },
  "general.heads_up": function(d) { return "Heads Up!"; },
  "general.hi": function(d) { return "Hi,"; },
  "general.hi_when_username_is_null": function(d) { return "Hi!"; },
  "general.high_donation": function(d) { return "Donations through this form are limited to $99.99 or less. If you would like to donate a greater amount, please visit <a target='_blank' href='https://www.stjude.org/donate/tg-dominos.html'>https://www.stjude.org/donate/tg-dominos.html</a> to donate."; },
  "general.i_am_student": function(d) { return "I Am Student"; },
  "general.if_other": function(d) { return ""; },
  "general.in_case_the_store_needs": function(d) { return "In case the store needs to reach you, we'll call this phone number.  If you do not answer we will be unable to deliver your order."; },
  "general.instructions_to_update_mobile_device_browsers": function(d) { return "Instructions to update mobile device browsers"; },
  "general.instructions_to_update_your_desktop_computer_browser": function(d) { return "Instructions to update your desktop computer browser"; },
  "general.international": function(d) { return "International"; },
  "general.internet_connectivity_issue": function(d) { return "Internet Connectivity Issue"; },
  "general.interswitch": function(d) { return "Interswitch"; },
  "general.its_official": function(d) { return "It's official,"; },
  "general.january": function(d) { return "January"; },
  "general.join_now": function(d) { return "Join Now"; },
  "general.july": function(d) { return "July"; },
  "general.june": function(d) { return "June"; },
  "general.keep_me_signed_in": function(d) { return "Keep me signed in"; },
  "general.kiosk_timeout_remaining": function(d) { return "Are you still there? Your ordering session will expire in <strong class=\"js-remainingTime dominosColor2\">10</strong> seconds. If you would like to continue, hit OK below."; },
  "general.learn_more": function(d) { return "Learn More"; },
  "general.legal_notice": function(d) { return "Legal Notice"; },
  "general.legal_stuff": function(d) { return "Legal Stuff:"; },
  "general.libro": function(d) { return "Libro"; },
  "general.limited_time_only": function(d) { return "Limited Time Only"; },
  "general.load_more": function(d) { return "Load More"; },
  "general.looking_for_artisan": function(d) { return "Looking for Artisan Pizza?"; },
  "general.looks_like_no_eo": function(d) { return "Looks like you don't have an easy order yet."; },
  "general.low_donation": function(d) { return "Donation must be greater than $0.00."; },
  "general.loyalty_coupon_incomplete": function(d) { return "Redemption Incomplete"; },
  "general.loyalty_mastercard_save_my_credit_card_for": function(d) { return "Save my payment information for faster future ordering and make this my primary card."; },
  "general.loyalty_piece_of_the_pie": function(d) { return "Piece of the Pie"; },
  "general.loyalty_piece_of_the_pie_reward": function(d) { return "Piece of the Pie Rewards<sup>&reg;</sup>"; },
  "general.loyalty_piece_of_the_pie_wizard": function(d) { return "Redemption"; },
  "general.make_this_order_my_easy_order": function(d) { return "MAKE THIS ORDER MY EASY ORDER"; },
  "general.march": function(d) { return "March"; },
  "general.may": function(d) { return "May"; },
  "general.menu": function(d) { return "Menu"; },
  "general.mind_ordering_tile_title": function(d) { return ""; },
  "general.month": function(d) { return "month"; },
  "general.more_info": function(d) { return "More info"; },
  "general.morning": function(d) { return "Morning"; },
  "general.my_easy_order": function(d) { return "My Easy Order"; },
  "general.my_order": function(d) { return "My Order"; },
  "general.name_your_card": function(d) { return "Name Your Card."; },
  "general.name_your_credit_card": function(d) { return "Name Your Card."; },
  "general.name_your_easy_order": function(d) { return "Name Your Easy Order."; },
  "general.next_steps": function(d) { return "Next Steps"; },
  "general.no_donate": function(d) { return "No, I would not like to donate"; },
  "general.no_preference": function(d) { return "No Preference"; },
  "general.no_thanks": function(d) { return "No Thanks"; },
  "general.no_thanks_comma": function(d) { return "No, thanks"; },
  "general.not_firstname_sign_out": function(d) { return "Not " + d.firstName + "? Sign Out"; },
  "general.note": function(d) { return "Note:"; },
  "general.november": function(d) { return "November"; },
  "general.now_give_it_a_name": function(d) { return "Now give it a name (optional)"; },
  "general.num0": function(d) { return "0"; },
  "general.num1": function(d) { return "1"; },
  "general.num10": function(d) { return "10"; },
  "general.num2": function(d) { return "2"; },
  "general.num3": function(d) { return "3"; },
  "general.num4": function(d) { return "4"; },
  "general.num5": function(d) { return "5"; },
  "general.num6": function(d) { return "6"; },
  "general.num7": function(d) { return "7"; },
  "general.num8": function(d) { return "8"; },
  "general.num9": function(d) { return "9"; },
  "general.october": function(d) { return "October"; },
  "general.ok": function(d) { return "ok"; },
  "general.okay_got_it": function(d) { return "Okay, got it"; },
  "general.okay_thanks": function(d) { return "Okay thanks"; },
  "general.online_only": function(d) { return "Online Only"; },
  "general.open": function(d) { return "Open"; },
  "general.open_for_lunch": function(d) { return "Open For Lunch"; },
  "general.order": function(d) { return "Order"; },
  "general.order_carryout": function(d) { return "Order Carryout"; },
  "general.order_eo_from_all_devices": function(d) { return "If you saved this as your Easy Order, you could order from all your favorite devices. Just saying."; },
  "general.order_faster_and_easier_than": function(d) { return "Order faster and easier than ever with a pizza profile."; },
  "general.order_now": function(d) { return "Order Now"; },
  "general.order_now_50_off": function(d) { return "50% off all pizzas at menu price"; },
  "general.order_now_alternate": function(d) { return ""; },
  "general.order_now_to_enter": function(d) { return "Order Now to Enter"; },
  "general.order_now_with_this_coupon": function(d) { return "Order now with this coupon"; },
  "general.order_online": function(d) { return "Order Online"; },
  "general.order_track": function(d) { return "order & track"; },
  "general.order_with_dom": function(d) { return "Order with Dom"; },
  "general.order_with_dom_text": function(d) { return "Hi, I’m Dom! It looks like you’ve either selected your store or already started putting items in your cart. I’m still in beta and don’t have a good memory, so if you continue forward with me your store and cart will be cleared."; },
  "general.phone": function(d) { return "Phone"; },
  "general.phone_no_with_dialer_wrapper": function(d) { return "<a class='inactive-link' href='tel:" + d.dataPhone + "'>" + d.dataPhone + "</a>"; },
  "general.phone_note": function(d) { return "The restaurant may call you for quality control purposes. Please enter a phone number where we can reach you."; },
  "general.piece_of_the_pie_rewards_r": function(d) { return "Piece of the Pie Rewards®"; },
  "general.pizza": function(d) { return "Pizza"; },
  "general.pizza_builder": function(d) { return ""; },
  "general.pizza_profile": function(d) { return "Pizza Profile"; },
  "general.please_confirm_your_password_so": function(d) { return "Please confirm your password so we know it's you!"; },
  "general.pos": function(d) { return "Pos"; },
  "general.powered_by_fac": function(d) { return "Powered by FAC"; },
  "general.price_my_order": function(d) { return ""; },
  "general.pricing_changes_possible": function(d) { return "Please be aware that the updates made to your order could affect the total price."; },
  "general.primary_address": function(d) { return "(Primary Address)"; },
  "general.print_menu": function(d) { return "Print Menu"; },
  "general.print_menu_halal": function(d) { return ""; },
  "general.product_for_discounted_price": function(d) { return d.variantName + " for " + d.discountPrice; },
  "general.product_for_price": function(d) { return d.variantName + " for " + d.variantPrice; },
  "general.push_notification_title": function(d) { return "Domino's Pizza"; },
  "general.qty": function(d) { return "QTY"; },
  "general.rate_limiting": function(d) { return "Our apologies.  Due to overwhelming orders during peak hours, you may not receive your order on time."; },
  "general.reminder": function(d) { return "Reminder"; },
  "general.remove_your_easy_order": function(d) { return "Remove Your Easy Order"; },
  "general.reset_password": function(d) { return "Reset Password"; },
  "general.sadad_id": function(d) { return ""; },
  "general.save_eo_by_creating_profile": function(d) { return "Save your Easy Order by creating a Pizza Profile"; },
  "general.save_eo_when_you_place_order": function(d) { return "Save this as your Easy Order when you place your order."; },
  "general.save_eo_without_placing_order": function(d) { return "Save now without placing your order?"; },
  "general.save_my_credit_card_for": function(d) { return "Save my payment information for faster future ordering."; },
  "general.save_my_payment_information_for": function(d) { return "Save my payment information for faster future ordering."; },
  "general.save_now": function(d) { return "Save now"; },
  "general.save_or_checkout": function(d) { return "<span>Save or Checkout</span>"; },
  "general.save_this_order_as_my": function(d) { return "Save this order as my Easy Order."; },
  "general.save_your_order_and_checkout_faster": function(d) { return "Save your order and order details for upcoming orders to save time and check-out fast!"; },
  "general.saved_cart_message": function(d) { return "Pick up where you left off. Continue ordering with your saved cart or start a new order."; },
  "general.saved_cart_title": function(d) { return "We saved your cart"; },
  "general.secure_payment": function(d) { return ""; },
  "general.select_your_local_store": function(d) { return "select your local store"; },
  "general.september": function(d) { return "September"; },
  "general.service_method_or": function(d) { return d.currentServiceMethod + " or " + d.nextServiceMethod + "?"; },
  "general.session_timeout_message": function(d) { return "Heads up! Your session is about to expire. Would you like to extend this session?"; },
  "general.session_timeout_title": function(d) { return "Session Timeout"; },
  "general.short_mix_and_match": function(d) { return "Choose 2 or more select menu items for <em>$" + d.price + "</em> each."; },
  "general.short_mix_and_match_upsell": function(d) { return "Choose 2 or more: Medium Specialty Pizzas for <em>$" + d.upsellPrice + "</em> or select menu items for <em>$" + d.price + "</em> each."; },
  "general.sign_in": function(d) { return ""; },
  "general.sign_in_for_this_order": function(d) { return "Sign In For this Order"; },
  "general.sign_in_keep_me_signed": function(d) { return "Sign In & Keep Me Signed In"; },
  "general.sign_in_to_activate": function(d) { return "Sign In to Activate"; },
  "general.sign_in_to_your_existing_pizza": function(d) { return "Sign in to your existing Pizza Profile"; },
  "general.sign_in_to_your_pizza": function(d) { return "Sign in to your Pizza Profile"; },
  "general.sign_in_to_your_pizza_bp": function(d) { return "Sign in to your Pizza Profile To Claim <span class=\"lowercase\">bp</span> Reward"; },
  "general.sign_out": function(d) { return "Sign Out"; },
  "general.sign_out_when_username_is_null": function(d) { return "Sign Out"; },
  "general.sign_up_now": function(d) { return "Sign Up Now"; },
  "general.skip_to_main_content_CA": function(d) { return "Skip to Main Content"; },
  "general.special_carryout_offer": function(d) { return "Special Carryout Offer"; },
  "general.special_offer": function(d) { return "Special Offer!"; },
  "general.special_online_coupon": function(d) { return "Special Online Coupon"; },
  "general.sponsor": function(d) { return "Sponsor"; },
  "general.stage1": function(d) { return "1"; },
  "general.stage10": function(d) { return "10"; },
  "general.stage11": function(d) { return "11"; },
  "general.stage12": function(d) { return "12"; },
  "general.stage13": function(d) { return "13"; },
  "general.stage14": function(d) { return "14"; },
  "general.stage15": function(d) { return "15"; },
  "general.stage16": function(d) { return "16"; },
  "general.stage17": function(d) { return "17"; },
  "general.stage18": function(d) { return "18"; },
  "general.stage19": function(d) { return "19"; },
  "general.stage2": function(d) { return "2"; },
  "general.stage20": function(d) { return "20"; },
  "general.stage21": function(d) { return "21"; },
  "general.stage22": function(d) { return "22"; },
  "general.stage23": function(d) { return "23"; },
  "general.stage24": function(d) { return "24"; },
  "general.stage25": function(d) { return "25"; },
  "general.stage26": function(d) { return "26"; },
  "general.stage27": function(d) { return "27"; },
  "general.stage28": function(d) { return "28"; },
  "general.stage29": function(d) { return "29"; },
  "general.stage3": function(d) { return "3"; },
  "general.stage30": function(d) { return "30"; },
  "general.stage4": function(d) { return "4"; },
  "general.stage5": function(d) { return "5"; },
  "general.stage6": function(d) { return "6"; },
  "general.stage7": function(d) { return "7"; },
  "general.stage8": function(d) { return "8"; },
  "general.stage9": function(d) { return "9"; },
  "general.start_new_order": function(d) { return "start a new order"; },
  "general.start_order": function(d) { return "Start Your Order"; },
  "general.start_over": function(d) { return "Start Over"; },
  "general.start_your_order": function(d) { return "Start Your Order"; },
  "general.starting_at": function(d) { return "Starting at:"; },
  "general.stay_on_dominos": function(d) { return "Stay on Dominos.ca"; },
  "general.step_1": function(d) { return "Step 1"; },
  "general.step_2": function(d) { return "Step 2"; },
  "general.step_3": function(d) { return "Step 3"; },
  "general.success": function(d) { return "Success"; },
  "general.surprise_frees_blurb": function(d) { return "<span class=\"surprise-frees-blurb__part-1\">Order <span class=\"surprise-frees-blurb__highlight\">delivery</span> online and you might get</span> <span class=\"surprise-frees-blurb__part-2\"><span class=\"surprise-frees-blurb__flag\">free</span> pizza, lava cakes, and more</span>"; },
  "general.surprise_frees_heading": function(d) { return "We're Giving Away $50 Million in Surprise Frees"; },
  "general.surprise_frees_legal": function(d) { return "<abbr title=\"No Purchase Necessary\">No Purch. Nec</abbr>. Open to 50 U.S (D.C.), 13+ through 1/9/22 11:59.pm ET (subject to black-out dates). 1:14 odds of winning. See <a target=\"_blank\" data-dpz-track-evt-label=\"" + d.eventLabel + "\" href=\"https://bit.ly/3iAIqTp\">official rules</a> for free entry, restrictions & details."; },
  "general.surprise_frees_order_now": function(d) { return "Order now <span class=\"is-visually-hidden\">for delivery for your chance to win Surprise Frees</span>"; },
  "general.take_it_for_a_ride": function(d) { return "Take it for a ride"; },
  "general.talk_to_dom": function(d) { return "Talk to Dom"; },
  "general.telephone_abbr": function(d) { return "Tel"; },
  "general.tell_me_more": function(d) { return "Tell me more"; },
  "general.thank_you": function(d) { return "Thank You!"; },
  "general.thank_you_for_signing_up": function(d) { return ""; },
  "general.thank_you_for_signing_up_both": function(d) { return "Thank you for signing up to have our hot email and text offers delivered right to " + d.phone + " and " + d.email + "!"; },
  "general.thank_you_for_signing_up_email": function(d) { return "Thank you for signing up to have our hot email offers delivered right to " + d.email + "!"; },
  "general.thank_you_for_signing_up_phone": function(d) { return "Thank you for signing up to have our hot text offers delivered right to " + d.phone + "!"; },
  "general.this_is_the_dominos_national": function(d) { return "This is the Domino's national menu. To see prices, coupons and exactly what items are available to you,"; },
  "general.this_is_the_dominos_national_note": function(d) { return ""; },
  "general.to": function(d) { return "to"; },
  "general.try_again": function(d) { return "Try Again"; },
  "general.update_android": function(d) { return "<p><strong>Android</strong><br/>Open Google Play app on your mobile device.<br/>Search for the web browser.<br/>Click <strong>Update</strong>.</p>"; },
  "general.update_chrome": function(d) { return "<strong>Chrome (Windows & Mac)- </strong> <a href=\"https://www.google.com/chrome/\">https://www.google.com/chrome/</a>"; },
  "general.update_edge": function(d) { return "<strong>Edge- </strong>Microsoft Edge is part of an operating system and can’t be separately updated. It’s updated through regular windows updates."; },
  "general.update_internet_explorer": function(d) { return "<strong>Internet Explorer- </strong><a href=\"https://support.microsoft.com/en-us/help/17621/internet-explorer-downloads\">https://support.microsoft.com/en-us/help/17621/internet-explorer-downloads</a>"; },
  "general.update_ios": function(d) { return "<p><strong>iOS</strong><br/>Open the App Store app on mobile device.<br/>Search for the web browser.<br/>Click <strong>Update</strong>.</p>"; },
  "general.update_mozilla_firefox": function(d) { return "<strong>Mozilla Firefox (Windows & Mac)- </strong><a href=\"https://www.mozilla.org/en-US/firefox/\">https://www.mozilla.org/en-US/firefox/</a>"; },
  "general.update_safari_mac": function(d) { return "<strong>Safari (Mac)- </strong><a href=\"https://support.apple.com/downloads/safari\">https://support.apple.com/downloads/safari</a>"; },
  "general.update_safari_windows": function(d) { return "<strong>Safari (Windows)- </strong><a href=\"https://support.apple.com/downloads/safari-for-windows\">https://support.apple.com/downloads/safari-for-windows</a>"; },
  "general.update_windows": function(d) { return "<p><strong>Windows</strong><br/>Open the Microsoft Store app on your mobile device.<br/>Search for the web browser.<br/>Click <strong>Update</strong>.</p>"; },
  "general.view_cart": function(d) { return "View Cart"; },
  "general.we_have_made_some_changes": function(d) { return "We've made some changes..."; },
  "general.wed_like_you_to_know": function(d) { return "We'd Like you to know..."; },
  "general.wedding_registry": function(d) { return "Domino's Wedding Registry"; },
  "general.welcome_to_dominos": function(d) { return "Welcome to Domino's!"; },
  "general.well_keep_your_cart": function(d) { return "We'll keep your cart ready for you! Order any time today."; },
  "general.were_sorry": function(d) { return "We're sorry…"; },
  "general.were_sorry_plain": function(d) { return "We're sorry"; },
  "general.why": function(d) { return "Why?"; },
  "general.wodth_with_dom_text": function(d) { return ""; },
  "general.work_with_us": function(d) { return "Work With Us"; },
  "general.year": function(d) { return "year"; },
  "general.yes_add_to_order": function(d) { return "Yes, Add to Order"; },
  "general.yes_donate": function(d) { return "Yes, I would like to donate"; },
  "general.yes_i_agree_to_the": function(d) { return "Yes. I agree to the <a class=\"js-isTemplatePopup\" data-template-popup=\"contentPageTerms\" href=\"" + d.ctx + "/" + "#" + "!/content/terms/\">Terms of Use</a> and I am 13 or older"; },
  "general.yes_i_agree_to_the_cs": function(d) { return "I accept Terms & Condition and Privacy Policy <br> <span class=\"create-profile--term-links\">I have read and I accept the <a class=\"js-isTemplatePopup\" data-template-popup=\"contentPageTerms\" href=\"" + "#" + "\">terms & conditions</a> of use. If your order is a carryout, your First Name and Last Name will be displayed on the screen in-store with the waiting time indication. If you don’t want to display it we suggest to add some symbols in the Last Name field (i.e. ***)"; },
  "general.yes_i_would_like_to": function(d) { return "<span class=\"dominosColor2 yes\">Yes!</span> I would like to receive <strong>exclusive</strong> e-mail coupons from Domino's Pizza"; },
  "general.yes_i_would_like_to_receive_sms": function(d) { return "Yes, I would like to receive sms offers from Domino's Pizza"; },
  "general.yes_remove": function(d) { return "Yes, remove"; },
  "general.you_are_already_enrolled_to": function(d) { return "You are already enrolled to have our hot text offers delivered right to " + d.phone + "!"; },
  "general.you_must_ask": function(d) { return "You must ask for this limited time offer. Prices, participation, delivery area and charges may vary. Offer applies to the pizza portion of your order only. Minimum purchase required for delivery."; },
  "general.you_now_have_a_pizza_profile": function(d) { return "You now have a Pizza Profile"; },
  "general.you_will_have_the_opportunity": function(d) { return "You will have the opportunity to select \"Keep me signed in\" checkbox when you create a Pizza Profile or sign in to your existing Pizza Profile for a quicker ordering experience. By checking this box, you allow Domino's to provide you with a more personalized experience in which you will be greeted by your first name and presented with (i) your Easy Order, (ii) a list of your recent orders and (iii) information about your local store. When you select \"Keep me signed in\", you will remain signed in to your Pizza Profile on that particular computer or device for up to six months or until you select the \"sign out\" link or clear your computer's or device's cookies. Although you are signed in to your Pizza Profile account, you will be prompted for your password if you attempt to perform a sensitive action such as modifying the personal information in your Pizza Profile account or completing an order using a stored credit card. If you change your mind about remaining signed in, simply select the \"sign out\" link to deactivate this feature.<br>NOTE: To prevent others from accessing your Pizza Profile account, Domino's does not recommend the use of this feature on any public or shared computer or device."; },
  "general.your_browser_is_out_of_date": function(d) { return "Your Browser is out of Date"; },
  "general.your_current_browser_does_not_meet_new_security_standards": function(d) { return "<p>Your current browser does not meet new <a href=\"https://blog.pcisecuritystandards.org/are-you-ready-for-30-june-2018-sayin-goodbye-to-ssl-early-tls\">security standards</a> for our website. Properly managing customer data is a very high priority for Domino’s, and we work closely with our customers to ensure that critical information is transferred over the Internet using the most current data security standards.</p><p>In order to continue accessing dominos.ca you’ll need to update your browser to the most recent version. Please follow the instructions below for each application to ensure that your systems are up to date.</p>"; },
  "general.your_reorder_will_be_updated": function(d) { return "Your order has been updated to reflect changes to your store's menu or coupons. Review the following updates:"; },
  "general.your_stores_lobby_closes_for": function(d) { return "Your store's lobby closes for the night at " + d.carryoutCloseTime + ". If you place your carryout order by " + d.carryoutCloseTime + ", don't worry, you can still pick it up. After that, you can still place a delivery order until " + d.deliveryCloseTime + "."; },
  "general.youre_all_set": function(d) { return "You're all set!"; }
}
}
);
