define([], function anonymous(
) {
var pluralFuncs = {
  en: function(n, ord) {
    var s = String(n).split('.'), v0 = !s[1], t0 = Number(s[0]) == n,
        n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2);
    if (ord) return (n10 == 1 && n100 != 11) ? 'one'
        : (n10 == 2 && n100 != 12) ? 'two'
        : (n10 == 3 && n100 != 13) ? 'few'
        : 'other';
    return (n == 1 && v0) ? 'one' : 'other';
  }
};
var fmt = {};
var number = function(value, offset) {
  if (isNaN(value)) throw new Error("'" + value + "' isn't a number.");
  return value - (offset || 0);
};
var plural = function(value, offset, lcfunc, data, isOrdinal) {
  if ({}.hasOwnProperty.call(data, value)) return data[value]();
  if (offset) value -= offset;
  var key = lcfunc(value, isOrdinal);
  if (key in data) return data[key]();
  return data.other();
};
var select = function(value, data) {
  if ({}.hasOwnProperty.call(data, value)) return data[value]();
  return data.other()
};

return {
  "titles.About Domino's Menu": function(d) { return "About Domino's Menu"; },
  "titles.Bread": function(d) { return "Bread"; },
  "titles.Builder": function(d) { return ""; },
  "titles.Checkout Add&ndash;on": function(d) { return ""; },
  "titles.Checkout Confirmation - Domino's Pizza, Order Pizza Online for Delivery - Dominos.com": function(d) { return "Checkout Confirmation - Domino's Pizza Canada®, Order Pizza Online for Delivery - Dominos.ca"; },
  "titles.Chicken": function(d) { return "Chicken"; },
  "titles.Chicken Wings | Domino's": function(d) { return "Chicken Wings | Domino's"; },
  "titles.Coupon Wizard": function(d) { return ""; },
  "titles.Coupon | Continue Online Ordering": function(d) { return ""; },
  "titles.Coupons From Domino's Pizza": function(d) { return "Coupons From Domino's Pizza Canada®"; },
  "titles.Coupons | Enter Code": function(d) { return ""; },
  "titles.Coupons | Feeds 1-2": function(d) { return ""; },
  "titles.Coupons | Feeds 3-5": function(d) { return ""; },
  "titles.Coupons | Feeds 6 Plus": function(d) { return ""; },
  "titles.Coupons | Lunch Offers": function(d) { return ""; },
  "titles.Coupons | Most Popular": function(d) { return ""; },
  "titles.Coupons | View All": function(d) { return ""; },
  "titles.CouponsAll": function(d) { return "Coupons | View All"; },
  "titles.CouponsEnterCode": function(d) { return "Coupons | Enter Code"; },
  "titles.CouponsFeeds1To2": function(d) { return "Coupons | Feeds 1-2"; },
  "titles.CouponsFeeds3To5": function(d) { return "Coupons | Feeds 3-5"; },
  "titles.CouponsFeeds6Plus": function(d) { return "Coupons | Feeds 6 Plus"; },
  "titles.CouponsLunchOffers": function(d) { return "Coupons | Lunch Offers"; },
  "titles.CouponsMostPopular": function(d) { return "Coupons | Most Popular"; },
  "titles.Customer Service FAQs - Domino's Pizza, Order Pizza Online for Delivery - Dominos.com": function(d) { return "Service à la clientèle - Domino's Pizza, Commandez de la pizza en ligne pour la faire livrer - Dominos.ca"; },
  "titles.Customer Service FAQs - Domino's Pizza, Order Pizza Online for Delivery - dominos.ch": function(d) { return ""; },
  "titles.Customer Service FAQs - Domino's Pizza, Order Pizza Online for Delivery - dominos.ma": function(d) { return ""; },
  "titles.Dessert": function(d) { return "Dessert"; },
  "titles.Domino's Home Page - Domino's Pizza, Encomenda Pizza Online para entrega - Dominos.com": function(d) { return ""; },
  "titles.Domino's Home Page - Domino's Pizza, Encomenda Pizza Online para entrega - dominos.com.br": function(d) { return ""; },
  "titles.Domino's Home Page - Domino's Pizza, Order Pizza Online for Delivery - Dominos.com": function(d) { return "Domino's Pizza Canada® - Order Pizza Online - Dominos.ca"; },
  "titles.Domino's Home Page - Domino's Pizza, Order Pizza Online for Delivery - Dominos.com.gt": function(d) { return ""; },
  "titles.Domino's Home Page - Domino's Pizza, Order Pizza Online for Delivery - Dominos.com.pe": function(d) { return ""; },
  "titles.Domino's Home Page - Domino's Pizza, Order Pizza Online for Delivery - Dominos.com.sv": function(d) { return ""; },
  "titles.Domino's Home Page - Domino's Pizza, Order Pizza Online for Delivery - Dominospizza.cl": function(d) { return ""; },
  "titles.Domino's Home Page - Domino's Pizza, Order Pizza Online for Delivery - Dominospizza.ph": function(d) { return ""; },
  "titles.Domino's Home Page - Domino's Pizza, Order Pizza Online for Delivery - dominos.ae": function(d) { return ""; },
  "titles.Domino's Home Page - Domino's Pizza, Order Pizza Online for Delivery - dominos.aw": function(d) { return ""; },
  "titles.Domino's Home Page - Domino's Pizza, Order Pizza Online for Delivery - dominos.ch": function(d) { return ""; },
  "titles.Domino's Home Page - Domino's Pizza, Order Pizza Online for Delivery - dominos.com.br": function(d) { return ""; },
  "titles.Domino's Home Page - Domino's Pizza, Order Pizza Online for Delivery - dominos.com.kh": function(d) { return ""; },
  "titles.Domino's Home Page - Domino's Pizza, Order Pizza Online for Delivery - dominos.ma": function(d) { return ""; },
  "titles.Domino's Home Page - Domino's Pizza, Order Pizza Online for Delivery - dominos.vi": function(d) { return ""; },
  "titles.Domino's Home Page - Domino's Pizza, Order Pizza Online for Delivery - dominospizza.hn": function(d) { return ""; },
  "titles.Domino's Pizza Frequently Asked Questions - Domino's FAQ Section": function(d) { return "Domino's Pizza Canada® Customer Service - Contact Us - Dominos.ca"; },
  "titles.Domino's Pizza Restaurants": function(d) { return "Domino's Pizza Canada® Restaurants"; },
  "titles.Domino's Pizza, Customer Service - Dominos.com": function(d) { return ""; },
  "titles.Domino's Pizza, Encomendar Pizza Online para entrega - Dominos.com": function(d) { return ""; },
  "titles.Domino's Pizza, Encomendar Pizza Online para entrega - dominos.com.br": function(d) { return ""; },
  "titles.Domino's Pizza, Order Pizza Online for Delivery - Dominos.ca": function(d) { return "Domino's Pizza Canada®, Order Pizza Online for Delivery - Dominos.ca"; },
  "titles.Domino's Pizza, Order Pizza Online for Delivery - Dominos.com": function(d) { return "Domino's Pizza, Order Pizza Online for Delivery - Dominos.com"; },
  "titles.Domino's Pizza, Order Pizza Online for Delivery - Dominos242.com": function(d) { return ""; },
  "titles.Domino's Pizza, Order Pizza Online for Delivery - Dominospizza.ph": function(d) { return ""; },
  "titles.Domino's Pizza, Order Pizza Online for Delivery - dominos.ae": function(d) { return ""; },
  "titles.Domino's Pizza, Order Pizza Online for Delivery - dominos.aw": function(d) { return ""; },
  "titles.Domino's Pizza, Order Pizza Online for Delivery - dominos.ch": function(d) { return ""; },
  "titles.Domino's Pizza, Order Pizza Online for Delivery - dominos.com.br": function(d) { return ""; },
  "titles.Domino's Pizza, Order Pizza Online for Delivery - dominos.com.kh": function(d) { return ""; },
  "titles.Domino's Pizza, Order Pizza Online for Delivery - dominos.ma": function(d) { return ""; },
  "titles.Domino's Pizza, Order Pizza Online for Delivery - dominos.vi": function(d) { return ""; },
  "titles.Domino's Pizza, customerFeedback - Dominos.ca": function(d) { return "Domino's Pizza Canada®, customerFeedback - Dominos.ca"; },
  "titles.Domino's Pizza, customerFeedback - Dominos.com": function(d) { return "Domino's Pizza, customerFeedback - Dominos.com"; },
  "titles.Domino's Pizza, customerFeedback - Dominospizza.ph": function(d) { return ""; },
  "titles.Domino's Pizza, customerFeedback - dominos.ae": function(d) { return ""; },
  "titles.Domino's Pizza, customerFeedback - dominos.aw": function(d) { return ""; },
  "titles.Domino's Pizza, customerFeedback - dominos.ch": function(d) { return ""; },
  "titles.Domino's Pizza, customerFeedback - dominos.com.br": function(d) { return ""; },
  "titles.Domino's Pizza, customerFeedback - dominos.com.kh": function(d) { return ""; },
  "titles.Domino's Pizza, customerFeedback - dominos.ma": function(d) { return ""; },
  "titles.Domino's Pizza, customerFeedback - dominos.vi": function(d) { return ""; },
  "titles.Domino's Pizza, franchiseOpportunities - Dominos.com": function(d) { return ""; },
  "titles.Domino's Sitemap | Domino's Pizza": function(d) { return "Domino's Sitemap | Domino's Pizza Canada®"; },
  "titles.Drinks": function(d) { return "Drinks"; },
  "titles.Drinks | View All": function(d) { return ""; },
  "titles.Email Opt In - Domino's Pizza, Order Pizza Online for Delivery - Dominos.ca": function(d) { return "Email Opt In - Domino's Pizza Canada®, Order Pizza Online for Delivery - Dominos.ca"; },
  "titles.Email Opt In - Domino's Pizza, Order Pizza Online for Delivery - dominos.ch": function(d) { return ""; },
  "titles.Email Opt In - Domino's Pizza, Order Pizza Online for Delivery - dominos.ma": function(d) { return ""; },
  "titles.Email Opt Out - Domino's Pizza, Order Pizza Online for Delivery - Dominos.ca": function(d) { return "Email Opt Out - Domino's Pizza Canada®, Order Pizza Online for Delivery - Dominos.ca"; },
  "titles.Email Opt Out - Domino's Pizza, Order Pizza Online for Delivery - dominos.ch": function(d) { return ""; },
  "titles.Email Opt Out - Domino's Pizza, Order Pizza Online for Delivery - dominos.ma": function(d) { return ""; },
  "titles.Entrees Home": function(d) { return ""; },
  "titles.Entrees | Calzone": function(d) { return ""; },
  "titles.Entrees | Chicken": function(d) { return ""; },
  "titles.Entrees | Pasta": function(d) { return ""; },
  "titles.Entrees | Sandwich": function(d) { return ""; },
  "titles.Entrees | Specialty Pizza": function(d) { return ""; },
  "titles.Extras": function(d) { return "Extras"; },
  "titles.Find a Nearby Domino's": function(d) { return "Find a Nearby Domino's - Dominos.ca"; },
  "titles.Food Delivery from Domino's Pizza": function(d) { return "Food Delivery from Domino's Pizza Canada®"; },
  "titles.FoodAllDesserts": function(d) { return ""; },
  "titles.FoodAllDrinks": function(d) { return "Drinks | View All"; },
  "titles.FoodAllEntrees": function(d) { return "Entrees Home"; },
  "titles.FoodAllPizzas": function(d) { return "Entrees | Pizzas"; },
  "titles.FoodAllSides": function(d) { return "Sides and Desserts | View All"; },
  "titles.FoodAllentrees": function(d) { return ""; },
  "titles.FoodBread": function(d) { return "Sides and Desserts | Bread"; },
  "titles.FoodCalzone": function(d) { return "Entrees | Calzone"; },
  "titles.FoodChips": function(d) { return "Sides and Desserts | Chips"; },
  "titles.FoodDessert": function(d) { return "Sides and Desserts | Desserts"; },
  "titles.FoodGSalad": function(d) { return "Sides and Desserts | Salads"; },
  "titles.FoodHoagie": function(d) { return "Entrees | Hoagies"; },
  "titles.FoodPasta": function(d) { return "Entrees | Pasta"; },
  "titles.FoodPizza": function(d) { return "Entrees | Feast Pizza"; },
  "titles.FoodSandwich": function(d) { return "Entrees | Sandwich"; },
  "titles.FoodSides": function(d) { return "Sides and Desserts | Extras"; },
  "titles.FoodWings": function(d) { return "Entrees | Chicken"; },
  "titles.General Menu": function(d) { return "Dominos.ca"; },
  "titles.General Menu | Desserts": function(d) { return ""; },
  "titles.General Menu | Drinks": function(d) { return ""; },
  "titles.General Menu | Entrees": function(d) { return ""; },
  "titles.General Menu | Sides": function(d) { return ""; },
  "titles.Get National & Local Domino's Pizza Coupons for Carryout or Delivery": function(d) { return ""; },
  "titles.Get National & Local Dominos Pizza Coupons for Carryout or Delivery": function(d) { return "Domino's Pizza Canada® Coupons - Save on Your Order - Dominos.ca"; },
  "titles.Group Ordering | Drinks and Sides": function(d) { return ""; },
  "titles.Group Ordering | Pizzas": function(d) { return ""; },
  "titles.GroupOrderingPizza": function(d) { return "Group Ordering | Pizzas"; },
  "titles.GroupOrderingSides": function(d) { return "Group Ordering | Drinks and Sides"; },
  "titles.Jobs at Domino's": function(d) { return "Jobs at Domino's - Dominos.ca"; },
  "titles.Location No Results": function(d) { return ""; },
  "titles.Location Results": function(d) { return ""; },
  "titles.Location Search": function(d) { return ""; },
  "titles.Location Search - ": function(d) { return ""; },
  "titles.Lunch Ideas | Domino's Pizza": function(d) { return "Lunch Ideas | Domino's Pizza Canada®"; },
  "titles.Online Delivery from Domino's Pizza": function(d) { return "Online Delivery from Domino's Pizza Canada®"; },
  "titles.Online Pizza by Domino's": function(d) { return "Online Pizza by Domino's"; },
  "titles.Opt In for Domino's Email & Text Offers Online or by App": function(d) { return "Sign Up for Domino's Pizza Canada® Newsletter - Dominos.ca"; },
  "titles.Order Confirmation": function(d) { return ""; },
  "titles.Order Food Online From Domino's": function(d) { return "Order Food Online From Domino's"; },
  "titles.Order Pizza & Pasta Online for Carryout & Delivery - Domino's Pizza": function(d) { return "Domino's Home Page - Domino's Pizza Canada®, Order Pizza Online for Delivery - Dominos.ca"; },
  "titles.Order from the Domino's Pizza Menu for Carryout or Delivery": function(d) { return ""; },
  "titles.Order from the Domino's Pizza Menu for Carryout or Delivery - ": function(d) { return ""; },
  "titles.Payment": function(d) { return "Payment"; },
  "titles.Payment - Domino's Pizza, Order Pizza Online for Delivery - Dominos.com": function(d) { return "Payment - Domino's Pizza Canada®, Order Pizza Online for Delivery - Dominos.ca"; },
  "titles.Philly Cheese Steak | Oven Baked Sandwiches | Domino's": function(d) { return "Philly Cheese Steak | Oven Baked Sandwiches | Domino's"; },
  "titles.Pizza": function(d) { return "Pizza"; },
  "titles.Pizza Crust | Domino's": function(d) { return "Pizza Crust | Domino's"; },
  "titles.Pizza Delivery by Domino's": function(d) { return "Pizza Delivery by Domino's"; },
  "titles.Pizza Menu | Pizza Made Just For You | Domino's": function(d) { return "Pizza Menu | Pizza Made Just For You | Domino's"; },
  "titles.Pizza Party | Domino's Pizza": function(d) { return "Pizza Party | Domino's Pizza Canada®"; },
  "titles.Pizza Profile Add/Edit Saved Locations": function(d) { return ""; },
  "titles.Pizza Profile Change Password": function(d) { return ""; },
  "titles.Pizza Profile Details": function(d) { return ""; },
  "titles.Pizza Profile Edit Details": function(d) { return "Manage or edit your Domino's Pizza Canada® Profile settings"; },
  "titles.Pizza Profile Edit Details - ": function(d) { return ""; },
  "titles.Pizza Profile Forgot Your Password?": function(d) { return ""; },
  "titles.Pizza Profile Login": function(d) { return ""; },
  "titles.Pizza Profile Registration Form": function(d) { return ""; },
  "titles.Pizza Promo Savings": function(d) { return "Pizza Promo Savings"; },
  "titles.Place Order": function(d) { return ""; },
  "titles.Product Details": function(d) { return ""; },
  "titles.Review Order": function(d) { return ""; },
  "titles.Sides and Desserts | Bread": function(d) { return ""; },
  "titles.Sides and Desserts | Chips": function(d) { return ""; },
  "titles.Sides and Desserts | Desserts": function(d) { return ""; },
  "titles.Sides and Desserts | Extras": function(d) { return ""; },
  "titles.Sides and Desserts | Salads": function(d) { return ""; },
  "titles.Sides and Desserts | View All": function(d) { return ""; },
  "titles.The American Pizzeria": function(d) { return "The American Pizzeria"; },
  "titles.The Best Pizza Ever Created by Domino's": function(d) { return "The Best Pizza Ever Created by Domino's"; },
  "titles.The Pizza Places That You Love": function(d) { return "The Pizza Places That You Love"; },
  "titles.Track Your Domino's Order. - Dominos.com": function(d) { return "Track Your Domino's Order. - Dominos.ca"; },
  "titles.Track Your Domino's Order. - Dominospizza.ph": function(d) { return ""; },
  "titles.Track Your Domino's Order. - dominos.ae": function(d) { return ""; },
  "titles.Track Your Domino's Order. - dominos.aw": function(d) { return ""; },
  "titles.Track Your Domino's Order. - dominos.ch": function(d) { return ""; },
  "titles.Track Your Domino's Order. - dominos.com.br": function(d) { return ""; },
  "titles.Track Your Domino's Order. - dominos.com.kh": function(d) { return ""; },
  "titles.Track Your Domino's Order. - dominos.ma": function(d) { return ""; },
  "titles.Track Your Domino's Order. - dominos.vi": function(d) { return ""; },
  "titles.Track your Order with the Domino's Tracker to Know about your Pizza": function(d) { return "Dominos.ca"; },
  "titles.Tracker Order Progress": function(d) { return ""; },
  "titles.Tracker Search For Order": function(d) { return ""; },
  "titles.Tracker Search For Order - Track your Order with the Domino's Tracker to Know about your Pizza": function(d) { return ""; },
  "titles.Vegetarian Pizza | Domino's": function(d) { return "Vegetarian Pizza | Domino's"; },
  "titles.Wings": function(d) { return "Wings"; },
  "titles.You're Enrolled | Email Opt In": function(d) { return ""; },
  "titles.at_1834_locations_error_overlay": function(d) { return "Locations Geolocation Error"; },
  "titles.at_1834_store_locator_permission_overlay": function(d) { return "Locations Geolocation Permission"; },
  "titles.bonus_activation_error": function(d) { return "Bonus Activation Error"; },
  "titles.bonus_activation_form": function(d) { return "Bonus Activation"; },
  "titles.bonus_activation_success": function(d) { return "Bonus Activation Success"; },
  "titles.bread": function(d) { return ""; },
  "titles.builder": function(d) { return ""; },
  "titles.cart": function(d) { return "Cart"; },
  "titles.categoryall": function(d) { return "Domino's Pizza Canada® Menu - Pizza, Pasta, Sides & More"; },
  "titles.categorybread": function(d) { return ""; },
  "titles.categorybreadsAndSides": function(d) { return ""; },
  "titles.categorychicken": function(d) { return ""; },
  "titles.categorydesserts": function(d) { return "Domino's Pizza Canada® Menu - Desserts"; },
  "titles.categorydrinks": function(d) { return "Domino's Pizza Canada® Menu - Drinks"; },
  "titles.categoryentrees": function(d) { return "Domino's Pizza Canada® Menu - Pizza & Pasta Entrees"; },
  "titles.categoryextras": function(d) { return ""; },
  "titles.categorygsalad": function(d) { return ""; },
  "titles.categorypasta": function(d) { return ""; },
  "titles.categorypizza": function(d) { return ""; },
  "titles.categorysandwich": function(d) { return ""; },
  "titles.categorysides": function(d) { return "Domino's Pizza Canada® Menu - Chicken, Breads & Sauces"; },
  "titles.categoryviewAll": function(d) { return "Domino's Pizza Canada® Menu - Pizza, Pasta, Sides & More"; },
  "titles.changepassword": function(d) { return "Pizza Profile Change Password"; },
  "titles.checkout": function(d) { return "Checkout"; },
  "titles.checkout_addon": function(d) { return ""; },
  "titles.checkoutview": function(d) { return "Place Order"; },
  "titles.chicken": function(d) { return ""; },
  "titles.claim_rewards": function(d) { return "Claim Your Rewards - Domino's Pizza Canada®, Order Pizza Online for Delivery - Dominos.ca"; },
  "titles.confirmation": function(d) { return "Order Confirmation"; },
  "titles.content_accessibility_policy": function(d) { return "Accessibility Policy | Domino's"; },
  "titles.content_apps": function(d) { return "Mobile Apps - Domino's Pizza Canada®, Order Pizza Online for Delivery - Dominos.ca"; },
  "titles.content_biometric_data": function(d) { return "Biometric Data Policy | Domino's"; },
  "titles.content_catering": function(d) { return "Domino's Pizza Canada® Catering - Find Details & Pricing Options - Dominos.ca"; },
  "titles.content_cookies": function(d) { return "Cookie Policy - Domino's Pizza Canada®, Order Pizza Online for Delivery - Dominos.ca"; },
  "titles.content_dinner_bell": function(d) { return "Domino's Dinner Bell"; },
  "titles.content_employment": function(d) { return "Domino's Pizza Canada® Jobs - Apply Online - Dominos.ca"; },
  "titles.content_gift_cards": function(d) { return "Gift Cards - Domino's Pizza Canada®, Order Pizza Online for Delivery - Dominos.ca"; },
  "titles.content_privacy": function(d) { return "Privacy Policy & Information Collection | Domino's"; },
  "titles.content_terms": function(d) { return "Terms Of Use | Domino's"; },
  "titles.coupon_continue_online_ordering": function(d) { return ""; },
  "titles.coupon_wizard": function(d) { return ""; },
  "titles.coupons": function(d) { return "Coupons"; },
  "titles.coupons_enter_code": function(d) { return ""; },
  "titles.coupons_feeds_1_2": function(d) { return ""; },
  "titles.coupons_feeds_3_5": function(d) { return ""; },
  "titles.coupons_feeds_6_plus": function(d) { return ""; },
  "titles.coupons_lunch_offers": function(d) { return ""; },
  "titles.coupons_most_popular": function(d) { return ""; },
  "titles.coupons_view_all": function(d) { return ""; },
  "titles.create-profile": function(d) { return "Create a Domino's Pizza Canada® Profile - Sign Up Today"; },
  "titles.customer_email_verified": function(d) { return "Email Verified"; },
  "titles.customer_suggested_hotspots": function(d) { return "Suggested Hotspots"; },
  "titles.dessert": function(d) { return ""; },
  "titles.dominos_home_page_dominos_pizza": function(d) { return ""; },
  "titles.dominos_pizza_order_pizza_online": function(d) { return ""; },
  "titles.drinks": function(d) { return ""; },
  "titles.drinks_view_all": function(d) { return ""; },
  "titles.entrees_calzone": function(d) { return ""; },
  "titles.entrees_chicken": function(d) { return ""; },
  "titles.entrees_home": function(d) { return ""; },
  "titles.entrees_pasta": function(d) { return ""; },
  "titles.entrees_sandwich": function(d) { return ""; },
  "titles.entrees_specialty_pizza": function(d) { return ""; },
  "titles.extras": function(d) { return ""; },
  "titles.forgotpassword": function(d) { return "Pizza Profile Forgot Your Password?"; },
  "titles.fulfiller": function(d) { return "Coupon Wizard"; },
  "titles.general_menu": function(d) { return ""; },
  "titles.general_menu_desserts": function(d) { return ""; },
  "titles.general_menu_drinks": function(d) { return ""; },
  "titles.general_menu_entrees": function(d) { return ""; },
  "titles.general_menu_sides": function(d) { return ""; },
  "titles.group_ordering_drinks_and_sides": function(d) { return ""; },
  "titles.group_ordering_pizzas": function(d) { return ""; },
  "titles.hotspots_fyi_overlay": function(d) { return "Hotspots FYI"; },
  "titles.hotspots_location_error_overlay": function(d) { return "Hotspots Geolocation Error"; },
  "titles.hotspots_location_permission_overlay": function(d) { return "Hotspots Geolocation Permission"; },
  "titles.hotspots_search": function(d) { return "Hotspots Search"; },
  "titles.landing": function(d) { return "Pizza Profile Details"; },
  "titles.location": function(d) { return "Pizza Profile Add/Edit Saved Locations"; },
  "titles.location_no_results": function(d) { return ""; },
  "titles.location_results": function(d) { return "Location Results"; },
  "titles.location_search": function(d) { return ""; },
  "titles.locations": function(d) { return "Find Nearby Pizza Locations | Domino's"; },
  "titles.locationsall": function(d) { return "Location Search"; },
  "titles.locationsnoresults": function(d) { return "Location No Results"; },
  "titles.locationsresults": function(d) { return "Location Results"; },
  "titles.locationssearch": function(d) { return "Pizza Restaurants Near Me"; },
  "titles.locationsshoprunner": function(d) { return ""; },
  "titles.login": function(d) { return "Login to your Domino's Pizza Canada® Profile"; },
  "titles.menu": function(d) { return "Menu"; },
  "titles.national_coupons": function(d) { return "Domino's Pizza Canada® Coupons - Save on Your Order - Dominos.ca"; },
  "titles.national_menu": function(d) { return "Domino's National Menu"; },
  "titles.optin": function(d) { return "You're Enrolled | Email Opt In"; },
  "titles.order": function(d) { return "Domino's Pizza Canada® Tracker"; },
  "titles.orderStoreID": function(d) { return "Tracker Order Progress"; },
  "titles.order_confirmation": function(d) { return ""; },
  "titles.payment": function(d) { return "Payment"; },
  "titles.pizza": function(d) { return ""; },
  "titles.pizza_profile_add_edit_saved": function(d) { return ""; },
  "titles.pizza_profile_change_password": function(d) { return ""; },
  "titles.pizza_profile_details": function(d) { return ""; },
  "titles.pizza_profile_edit_details": function(d) { return ""; },
  "titles.pizza_profile_forgot_your_password": function(d) { return ""; },
  "titles.pizza_profile_login": function(d) { return ""; },
  "titles.pizza_profile_registration_form": function(d) { return ""; },
  "titles.place_order": function(d) { return ""; },
  "titles.product": function(d) { return "Product Details"; },
  "titles.product_details": function(d) { return ""; },
  "titles.productbuilder": function(d) { return "Builder"; },
  "titles.profile": function(d) { return "Create a Domino's Pizza Profile - Sign Up Today"; },
  "titles.profilenew": function(d) { return "Create a Domino's Pizza Canada® Profile - Sign Up Today"; },
  "titles.registration": function(d) { return "Pizza Profile Registration Form"; },
  "titles.review_order": function(d) { return ""; },
  "titles.rewards": function(d) { return "Piece of the Pie Rewards | Domino's Rewards Program"; },
  "titles.rewardshistory": function(d) { return "Rewards History"; },
  "titles.sides_and_desserts_bread": function(d) { return ""; },
  "titles.sides_and_desserts_chips": function(d) { return ""; },
  "titles.sides_and_desserts_desserts": function(d) { return ""; },
  "titles.sides_and_desserts_extras": function(d) { return ""; },
  "titles.sides_and_desserts_salads": function(d) { return ""; },
  "titles.sides_and_desserts_view_all": function(d) { return ""; },
  "titles.store_locator": function(d) { return "Store Locator"; },
  "titles.time": function(d) { return "Time"; },
  "titles.track_your_dominos_order_dominos": function(d) { return ""; },
  "titles.tracker_order_progress": function(d) { return ""; },
  "titles.tracker_search_for_order": function(d) { return ""; },
  "titles.upsell": function(d) { return "Checkout Add&ndash;on"; },
  "titles.upsellreengagement": function(d) { return "Coupon | Continue Online Ordering"; },
  "titles.variant": function(d) { return "Builder"; },
  "titles.wings": function(d) { return ""; },
  "titles.youre_enrolled_email_opt_in": function(d) { return ""; }
}
}
);
