define([], function anonymous(
) {
var pluralFuncs = {
  en: function(n, ord) {
    var s = String(n).split('.'), v0 = !s[1], t0 = Number(s[0]) == n,
        n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2);
    if (ord) return (n10 == 1 && n100 != 11) ? 'one'
        : (n10 == 2 && n100 != 12) ? 'two'
        : (n10 == 3 && n100 != 13) ? 'few'
        : 'other';
    return (n == 1 && v0) ? 'one' : 'other';
  }
};
var fmt = {};
var number = function(value, offset) {
  if (isNaN(value)) throw new Error("'" + value + "' isn't a number.");
  return value - (offset || 0);
};
var plural = function(value, offset, lcfunc, data, isOrdinal) {
  if ({}.hasOwnProperty.call(data, value)) return data[value]();
  if (offset) value -= offset;
  var key = lcfunc(value, isOrdinal);
  if (key in data) return data[key]();
  return data.other();
};
var select = function(value, data) {
  if ({}.hasOwnProperty.call(data, value)) return data[value]();
  return data.other()
};

return {
  "tiles.10_dash_piece_wings": function(d) { return "10-Piece Wings"; },
  "tiles.1999PerfectCombo_description": function(d) { return "2 Medium 1-Topping Pizzas, 16-piece Parmesan Bread Bites, 8 Piece Cinnamon Twists and a 2 Liter of Coke for $19.99."; },
  "tiles.1_dash_topping": function(d) { return "1-Topping"; },
  "tiles.20_off": function(d) { return "20% off"; },
  "tiles.20_percent_off": function(d) { return "20% off"; },
  "tiles.2_min": function(d) { return "2-minute"; },
  "tiles.2_min_countdown_begins": function(d) { return "2-minute countdown begins after you check in and your order is ready."; },
  "tiles.2_min_guarantee": function(d) { return "2-minute guarantee"; },
  "tiles.2mg_logo": function(d) { return "Domino’s team member brings your order to your car when you carry out from a Domino’s location."; },
  "tiles.35_off_all_orders": function(d) { return "all orders"; },
  "tiles.35_off_at_menu_price": function(d) { return "at menu price"; },
  "tiles.35_off_flag": function(d) { return "We know right now every cost counts"; },
  "tiles.35_off_legal": function(d) { return "You must ask for this limited-time offer. Prices, participation, delivery area and charges may vary. Discount applies to menu-priced items only. Not combinable with any other offer."; },
  "tiles.35_off_limited_time_offer": function(d) { return "Limited-Time Offer"; },
  "tiles.35_off_off": function(d) { return "off"; },
  "tiles.3_dash_toppings": function(d) { return "3-Toppings"; },
  "tiles.3_topping_pizzas": function(d) { return "3-Topping Pizzas"; },
  "tiles.3_toppings": function(d) { return "3 toppings"; },
  "tiles.50_off_all_pizzas": function(d) { return "all pizzas"; },
  "tiles.50_off_at_menu_price": function(d) { return "at menu price"; },
  "tiles.50_off_featured_title": function(d) { return "50%off"; },
  "tiles.50_off_flag_text": function(d) { return "valid 3/20 - 3/26"; },
  "tiles.50_off_legal_profiled_desktop": function(d) { return "March 20th – 26th select this online only offer. Min. purchase required for delivery. Prices, participation, delivery area and charges may vary. Offer applies to the pizza portion of your order only."; },
  "tiles.50_off_legal_profiled_handheld": function(d) { return "Select this online only offer. Min. purchase required for delivery. Prices, participation, delivery area and charges may vary. Offer applies to the pizza portion of your order only."; },
  "tiles.50_off_off": function(d) { return "off"; },
  "tiles.50_off_online": function(d) { return "online"; },
  "tiles.50_off_only": function(d) { return "only"; },
  "tiles.50_off_pizzas": function(d) { return "pizzas"; },
  "tiles.5_crusts": function(d) { return "5 crusts"; },
  "tiles.9pm_to_close": function(d) { return "9pm-store close"; },
  "tiles.AnyCrustSide_alt": function(d) { return "Any crust, any size* 2-topping pizzas $12.99 Order Now"; },
  "tiles.AnyCrustSide_description": function(d) { return "Any crust, any size* 2-topping pizzas $12.99"; },
  "tiles.AnyCrustSide_each": function(d) { return "each"; },
  "tiles.AnyCrustSide_flag": function(d) { return "Carryout only"; },
  "tiles.AnyCrustSide_legal": function(d) { return "*Extra large may be available at select locations for<br>an additional charge. Pricing may very per store."; },
  "tiles.AnyCrustSide_title": function(d) { return "Any crust, any size*<br /><span class=\"promo__title__emphasis\">2-topping<br>pizzas</span>"; },
  "tiles.Boostweek50Off02Hero_alt": function(d) { return "More pizza for less dough 50% off All Pizzas Feb. 27 - Mar. 5 Online Only ORDER NOW"; },
  "tiles.Boostweek50Off02Hero_description": function(d) { return "More pizza for less dough 50% off All Pizzas Feb. 27 - Mar. 5 Online Only ORDER NOW"; },
  "tiles.Boostweek50Off02Hero_flag": function(d) { return "Feb. 27 - Mar. 5"; },
  "tiles.Boostweek50Off02Hero_legal": function(d) { return "Valid only at participating locations."; },
  "tiles.Boostweek50Off02Hero_title": function(d) { return "<span class=\"promo__title__emphasis\">50<span class=\"percent\">%</span></span><span class=\"off\">Off</span><span class=\"promo__title__emphasis__smaller\">All Pizzas</span><span class=\"dates\">Feb. 27 - Mar. 5</span><span class=\"online-only\">Online Only</span>"; },
  "tiles.Boostweek50Off02Hero_title_mobile": function(d) { return "<span class=\"promo__title__emphasis\">50<span class=\"percent\">%</span></span><span class=\"off\">Off</span><span class=\"promo__title__emphasis__smaller\">All Pizzas</span><span class=\"dates\">Feb. 27 - Mar. 5</span><span class=\"online-only\">Online Only</span>"; },
  "tiles.Boostweek50Off02Hero_title_wide": function(d) { return "<span class=\"promo__title__emphasis\">50<span class=\"percent\">%</span></span><span class=\"off\">Off</span><span class=\"promo__title__emphasis__smaller\">All Pizzas</span><span class=\"online-only\">Online Only</span>"; },
  "tiles.Boostweek50Off03Hero_alt": function(d) { return "March 7 — 13 50% Off All Pizzas. Online Only. Valid only at participating locations.  Order Now"; },
  "tiles.Boostweek50Off03Hero_description": function(d) { return "50% Off All Pizzas. Online Only. Valid only at participating locations"; },
  "tiles.Boostweek50Off03Hero_flag": function(d) { return "March 7 — 13"; },
  "tiles.Boostweek50Off03Hero_title": function(d) { return "<span class=\"promo__title__emphasis\">50<span class=\"percent\">%</span></span><span class=\"off\">off</span><span class=\"all-pizzas\">All Pizzas</span><span class=\"promo__title__smaller\">Online Only<span class=\"valid\">Valid only at participating locations</span></span>"; },
  "tiles.Boostweek50Off04Hero_alt": function(d) { return "Crave Days 50% Off That Pizza You Always Wanted. Online Only. Order Now"; },
  "tiles.Boostweek50Off04Hero_description": function(d) { return "Crave Days 50% Off That Pizza You Always Wanted. Online Only."; },
  "tiles.Boostweek50Off04Hero_flag": function(d) { return "Crave Days"; },
  "tiles.Boostweek50Off04Hero_title": function(d) { return "<span class=\"promo__title__emphasis\">50% Off</span><span class=\"promo__title__emphasis__smaller\">That Pizza You<br>Always Wanted</span><span class=\"promo__title__flag\">Online Only</span>"; },
  "tiles.Boostweek50Off04Hero_title_mobile": function(d) { return "<span class=\"promo__title__emphasis\">50% Off</span><span class=\"promo__title__emphasis__smaller\">That Pizza You<br>Always Wanted</span><span class=\"promo__title__flag\">Online Only</span>"; },
  "tiles.Boostweek50Off04Hero_title_profiled": function(d) { return "<span class=\"promo__title__emphasis\">50% Off</span><span class=\"promo__title__emphasis__smaller\">That Pizza You Always Wanted</span><span class=\"promo__title__flag\">Online Only</span>"; },
  "tiles.Boostweek50Off05Hero_alt": function(d) { return "More pizza for less dough 50% off All Pizzas July 3 - 9  Online Only ORDER NOW"; },
  "tiles.Boostweek50Off05Hero_description": function(d) { return "More pizza for less dough 50% off All Pizzas July 3 - 9 Online Only ORDER NOW"; },
  "tiles.Boostweek50Off05Hero_flag": function(d) { return "July 3 - 9"; },
  "tiles.Boostweek50Off05Hero_legal": function(d) { return "Valid only at participating locations."; },
  "tiles.Boostweek50Off05Hero_title": function(d) { return "<span class=\"promo__title__emphasis\">50<span class=\"percent\">%</span></span><span class=\"off\">Off</span><span class=\"promo__title__emphasis__smaller\">All Pizzas</span><span class=\"dates\">July 3 - 9 </span><span class=\"online-only\">Online Only</span>"; },
  "tiles.Boostweek50Off05Hero_title_mobile": function(d) { return "<span class=\"promo__title__emphasis\">50<span class=\"percent\">%</span></span><span class=\"off\">Off</span><span class=\"promo__title__emphasis__smaller\">All Pizzas</span><span class=\"dates\">July 3 - 9 </span><span class=\"online-only\">Online Only</span>"; },
  "tiles.Boostweek50Off05Hero_title_wide": function(d) { return "<span class=\"promo__title__emphasis\">50<span class=\"percent\">%</span></span><span class=\"off\">Off</span><span class=\"promo__title__emphasis__smaller\">All Pizzas</span><span class=\"online-only\">Online Only</span>"; },
  "tiles.Boostweek50Off06Hero_alt": function(d) { return "50% Off Online Only All Pizzas All Week July 4-10 ORDER NOW"; },
  "tiles.Boostweek50Off06Hero_description": function(d) { return "50% Off Online Only All Pizzas All Week July 4-10 ORDER NOW"; },
  "tiles.Boostweek50Off06Hero_flag": function(d) { return "Online Only"; },
  "tiles.Boostweek50Off06Hero_title": function(d) { return "<span class=\"promo__title__emphasis\">50<span class=\"percent\">%</span></span><span class=\"off\">Off</span><span class=\"promo__title__emphasis__smaller\">All Pizzas<br />All Week</span><span class=\"dates\">July 4-10</span>"; },
  "tiles.Boostweek50Off06Hero_title_wide": function(d) { return "<span class=\"promo__title__emphasis\">50<span class=\"percent\">%</span></span><span class=\"off\">Off</span><span class=\"promo__title__emphasis__smaller\">All Pizzas<br />All Week</span><span class=\"dates\">July 4-10</span>"; },
  "tiles.Boostweek50Off07Hero_alt": function(d) { return "Crave Days 50% Off That Pizza You Always Wanted. Online Only. Order Now"; },
  "tiles.Boostweek50Off07Hero_description": function(d) { return "Crave Days 50% Off That Pizza You Always Wanted. Online Only."; },
  "tiles.Boostweek50Off07Hero_flag": function(d) { return "Crave Days"; },
  "tiles.Boostweek50Off07Hero_legal": function(d) { return "Carryout at Participating Locations"; },
  "tiles.Boostweek50Off07Hero_title": function(d) { return "<span class=\"promo__title__emphasis\">50% Off</span><span class=\"promo__title__emphasis__smaller\">That Pizza You<br>Always Wanted</span><span class=\"promo__title__flag\">Online Only</span>"; },
  "tiles.Boostweek50Off07Hero_title_mobile": function(d) { return "<span class=\"promo__title__emphasis\">50% Off</span><span class=\"promo__title__emphasis__smaller\">That Pizza You<br>Always Wanted</span><span class=\"promo__title__flag\">Online Only</span>"; },
  "tiles.Boostweek50Off07Hero_title_profiled": function(d) { return "<span class=\"promo__title__emphasis\">50% Off</span><span class=\"promo__title__emphasis__smaller\">That Pizza You Always Wanted</span><span class=\"promo__title__flag\">Online Only</span>"; },
  "tiles.Boostweek50Off09Hero_alt": function(d) { return "More pizza for less dough 50% off All Pizzas Sept. 12-18 Online Only ORDER NOW"; },
  "tiles.Boostweek50Off09Hero_description": function(d) { return "More pizza for less dough 50% off All Pizzas Sept. 12-18 Online Only ORDER NOW"; },
  "tiles.Boostweek50Off09Hero_flag": function(d) { return "Sept. 12-18"; },
  "tiles.Boostweek50Off09Hero_title": function(d) { return "<span class=\"promo__title__emphasis\">50<span class=\"percent\">%</span></span><span class=\"off\">Off</span><span class=\"promo__title__emphasis__smaller\">All Pizzas</span><span class=\"dates\">Sept. 12-18</span><span class=\"online-only\">Online Only</span>"; },
  "tiles.Boostweek50Off09Hero_title_mobile": function(d) { return "<span class=\"promo__title__emphasis\">50<span class=\"percent\">%</span></span><span class=\"off\">Off</span><span class=\"promo__title__emphasis__smaller\">All Pizzas</span><span class=\"dates\">Sept. 12-18</span><span class=\"online-only\">Online Only</span>"; },
  "tiles.Boostweek50Off09Hero_title_wide": function(d) { return "<span class=\"promo__title__emphasis\">50<span class=\"percent\">%</span></span><span class=\"off\">Off</span><span class=\"promo__title__emphasis__smaller\">All Pizzas</span><span class=\"online-only\">Online Only</span>"; },
  "tiles.Boostweek50Off10Hero_alt": function(d) { return "More pizza for less dough 50% off All Pizzas Sept 25 - Oct 02  Online Only ORDER NOW"; },
  "tiles.Boostweek50Off10Hero_description": function(d) { return "More pizza for less dough 50% off All Pizzas Sept 25 - Oct 02 Online Only ORDER NOW"; },
  "tiles.Boostweek50Off10Hero_flag": function(d) { return "Sept 25 - Oct 1"; },
  "tiles.Boostweek50Off10Hero_legal": function(d) { return "Valid only at participating locations."; },
  "tiles.Boostweek50Off10Hero_title": function(d) { return "<span class=\"promo__title__emphasis\">50<span class=\"percent\">%</span></span><span class=\"off\">Off</span><span class=\"promo__title__emphasis__smaller\">All Pizzas</span><span class=\"dates\">Sept 25 - Oct 1 </span><span class=\"online-only\">Online Only</span>"; },
  "tiles.Boostweek50Off10Hero_title_mobile": function(d) { return "<span class=\"promo__title__emphasis\">50<span class=\"percent\">%</span></span><span class=\"off\">Off</span><span class=\"promo__title__emphasis__smaller\">All Pizzas</span><span class=\"dates\">Sept 25 - Oct 1 </span><span class=\"online-only\">Online Only</span>"; },
  "tiles.Boostweek50Off10Hero_title_wide": function(d) { return "<span class=\"promo__title__emphasis\">50<span class=\"percent\">%</span></span><span class=\"off\">Off</span><span class=\"promo__title__emphasis__smaller\">All Pizzas</span><span class=\"online-only\">Online Only</span>"; },
  "tiles.BuyAnyLargePizzaFeatured_alt": function(d) { return "Get up to 3 medium 2-topping pizzas for $5"; },
  "tiles.BuyAnyLargePizzaFeatured_description": function(d) { return "Get up to 3 medium 2-topping pizzas for $5"; },
  "tiles.BuyAnyLargePizzaFeatured_details": function(d) { return "Get up to 3 medium 2-topping pizzas for"; },
  "tiles.BuyAnyLargePizzaFeatured_legal": function(d) { return "*Buy any large pizza at menu price and receive up to 3 medium 2-topping pizzas for $5 each. Select stores only. Additional charge for some crusts and toppings. Offer code: 9955"; },
  "tiles.BuyAnyLargePizzaFeatured_price": function(d) { return "<ul class=\"promo__additional__details__container\"><li class=\"promo__additional__details__text\"><span class=\"promo__additional__details__dollar\">$</span><span>5</span><span class=\"promo__additional__details__pizza\"></span></li><li class=\"promo__additional__details__text\"><span class=\"promo__additional__details__dollar\">$</span><span>5</span><span class=\"promo__additional__details__pizza\"></span></li><li class=\"promo__additional__details__text\"><span class=\"promo__additional__details__dollar\">$</span><span>5</span><span class=\"promo__additional__details__pizza\"></span></li></ul>"; },
  "tiles.BuyAnyLargePizzaFeatured_title": function(d) { return "Buy any <br> large <br> pizza <span class=\"promo__title__asterix\">*</span>"; },
  "tiles.COS_alt": function(d) { return "Carryout Deal - Large two toppings $5.99 each"; },
  "tiles.COS_description": function(d) { return "<h2>All large two topping pizzas</h2> <h2>$5.99 each</h2> <h2>Valid May 2nd - May 8th</h2> <h2>Order online - pick it up at the store</h2> <h2>Carry out only</h2>"; },
  "tiles.Carside_alt": function(d) { return "Domino’s Carside DeliveryTM. The fastest and safest way to carry out your order. Learn More"; },
  "tiles.ChooseAny2Hero_alt": function(d) { return "Choose any 2 or more $7.99* ORDER NOW 2 item minimum"; },
  "tiles.ChooseAny2Hero_description": function(d) { return "Choose any 2 or more $7.99* ORDER NOW 2 item minimum"; },
  "tiles.ChooseAny2Hero_legal": function(d) { return "2 item minimum"; },
  "tiles.ChooseAny2Hero_title": function(d) { return "Choose any<br>2 or more"; },
  "tiles.CinnaBites_alt": function(d) { return "New To Mix & Match * 2 item minimum"; },
  "tiles.CinnaBites_description": function(d) { return "New To Mix & Match * 2 item minimum"; },
  "tiles.CinnaBites_each": function(d) { return "each"; },
  "tiles.CinnaBites_flag": function(d) { return "<span class=\"new\">New</span> <span class=\"mix-and-match\">Mix & Match</span>"; },
  "tiles.CinnaBites_legal": function(d) { return "* 2 item minimum"; },
  "tiles.CinnaBites_title": function(d) { return "Cinna Bites"; },
  "tiles.Coke2020Footer_alt": function(d) { return "Any Two 500 mL Coca-Cola® Beverages Calories: 0–220 per 500 mL serving *Single units are sold at regular price. The trademarks that appear are the property of their respective trademark owners. Dasani® bottle is 591 mL and Fanta® bottle is 473 mL."; },
  "tiles.Coke2020Footer_calorie_details": function(d) { return "Cals 0–220 per 500 mL serving"; },
  "tiles.Coke2020Footer_legal": function(d) { return "*Single units are sold at regular price.<span class=\"mobile\"><sup>&" + "#" + "8224;</sup>Dasani® bottle is 591 mL and Fanta® bottle</span> <span class=\"mobile\">is 473 mL. The trademarks that appear are the property of their respective trademark owners.</span>"; },
  "tiles.Coke2020Footer_title": function(d) { return "Any Two 500<sup>&" + "#" + "8224;</sup>&nbsp;<span class=\"small\">m</span>L Coca-Cola® Beverages"; },
  "tiles.Coke2020Footer_title_mobile": function(d) { return "Any Two 500<sup>&" + "#" + "8224;</sup>&nbsp;<span class=\"small\">m</span>L<br>Coca-Cola® Beverages"; },
  "tiles.CokeFall_alt": function(d) { return "Fresh Meets Refreshing 2 x MEDIUM 2-TOPPING PIZZAS 4 x Any 500† mL COCA-COLA® BOTTLED BEVERAGES *Single units are sold at regular price. †Dasani® bottle is 591 mL. Trademarks shown are the property of their respective trademark owners."; },
  "tiles.CokeFall_description": function(d) { return "Fresh Meets Refreshing 2 x MEDIUM 2-TOPPING PIZZAS 4 x Any 500† mL COCA-COLA® BOTTLED BEVERAGES  *Single units are sold at regular price. $21.99* ORDER NOW †Dasani® bottle is 591 mL. Trademarks shown are the property of their respective trademark owners."; },
  "tiles.CokeFall_legal": function(d) { return "*Single units are sold at regular price.<br><span>&nbsp;</span><sup>&" + "#" + "8224;</sup>Dasani® bottle is 591 mL. Trademarks<br>shown are the property of their<br>respective trademark owners."; },
  "tiles.CokeFall_title": function(d) { return "<span class=\"promo__title__emphasis\">Fresh <span>&nbsp;</span><span>Meets</span><span>&nbsp;</span> Refreshing</span> 2 x MEDIUM 2-TOPPING PIZZAS<br>4 x Any 500<sup>&" + "#" + "8224;</sup> <span class=\"small\">m</span>L COCA-COLA® BOTTLED BEVERAGES"; },
  "tiles.CokeHoliday_alt": function(d) { return "ADD ANY TWO 500 mL COCA-COLA® BEVERAGES"; },
  "tiles.CokeHoliday_description": function(d) { return "ADD ANY TWO 500 mL COCA-COLA® BEVERAGES *Single units are sold at regular price."; },
  "tiles.CokeHoliday_legal": function(d) { return "*Single units are sold at regular price."; },
  "tiles.CokeHoliday_title": function(d) { return "ADD ANY<br>TWO 500 <span class=\"small\">m</span>L<br>COCA-COLA®<br>BEVERAGES"; },
  "tiles.CokeNHLPlayoff_alt": function(d) { return "2 X Medium 2-Topping Pizzas 4 X any 500† mL Coca Cola® Beverages"; },
  "tiles.CokeNHLPlayoff_description": function(d) { return "2 X Medium 2-Topping Pizzas<br>4 X any 500<sup>†</sup> <span class=\"small\">m</span>L Coca Cola® Beverages"; },
  "tiles.CokeNHLPlayoff_legal": function(d) { return "*Single units are sold at regular price. <sup>†</sup>Dasani® bottle is 591 mL.<br>Trademarks shown are the property of their respective owners."; },
  "tiles.CokeNHLPlayoff_title": function(d) { return "Breakaway Deal"; },
  "tiles.CokeOlympics_alt": function(d) { return "Bring Home A Winning Deal 4 x Any 500† mL COCA-COLA® BOTTLED BEVERAGES 2 x MEDIUM 2-TOPPING PIZZAS *Single units are sold at regular price. †Dasani® bottle is 591 mL. Trademarks shown are the property of their respective trademark owners."; },
  "tiles.CokeOlympics_description": function(d) { return "Bring Home A Winning Deal 4 x Any 500† mL COCA-COLA® BOTTLED BEVERAGES 2 x MEDIUM 2-TOPPING PIZZAS *Single units are sold at regular price. $21.99* ORDER NOW †Dasani® bottle is 591 mL. Trademarks shown are the property of their respective trademark owners."; },
  "tiles.CokeOlympics_legal": function(d) { return "*Single units are sold at regular price.<br><span>&nbsp;</span><sup>&" + "#" + "8224;</sup>Dasani® bottle is 591 mL Trademarks shown are<br>the property of their respective trademark owners."; },
  "tiles.CokeOlympics_title": function(d) { return "<span class=\"promo__title__emphasis\">Bring Home A Winning Deal</span> 4 x Any 500<sup>&" + "#" + "8224;</sup> <span class=\"small\">m</span>L COCA-COLA® BOTTLED BEVERAGES<br>2 x MEDIUM 2-TOPPING PIZZAS<br>"; },
  "tiles.CokeSports_alt": function(d) { return "Big Game Deal 2 Medium 2-Topping Pizzas & 4 – 500mL Coca-Cola® Beverages. *Single units are sold at regular price. †Dasani® bottle is 591 mL and Fanta® bottle is 473 mL. Trademarks shown are the property of their respective trademark owners."; },
  "tiles.CokeSports_description": function(d) { return "Big Game Deal 2 Medium 2-Topping Pizzas & 4 – 500mL Coca-Cola® Beverages. $21.99 ORDER NOW. *Single units are sold at regular price. †Dasani® bottle is 591 mL and Fanta® bottle is 473 mL. Trademarks shown are the property of their respective trademark owners."; },
  "tiles.CokeSports_legal": function(d) { return "*Single units are sold at regular price. <span>&nbsp;</span><sup>&" + "#" + "8224;</sup>Dasani® bottle is 591 mL<br>and Fanta® bottle is 473 mL. Trademarks shown are the property<br>of their respective trademark owners."; },
  "tiles.CokeSports_title": function(d) { return "<span class=\"promo__title__emphasis\">Big Game Deal</span> 2 x MEDIUM 2-TOPPING PIZZAS<br>4 x Any 500<sup>&" + "#" + "8224;</sup> <span class=\"small\">m</span>L COCA-COLA® BEVERAGES"; },
  "tiles.ComboOfferFooter2022_title": function(d) { return "2 Medium Pizzas With<br>6-Toppings Combined<br>& 1 Cheesy Bread"; },
  "tiles.ComboOfferFooter_title": function(d) { return "2 Medium Pizzas With<br>6-Toppings Combined<br>& 1 Cheesy Bread"; },
  "tiles.ComboOfferSide_alt": function(d) { return "Build Your Combo 2 Medium Pizzas With 6-Toppings Combined & 1 Cheesy Bread Order Now"; },
  "tiles.ComboOfferSide_calorie_details": function(d) { return "Cals 420 – 520 per slice and 2 pcs bread"; },
  "tiles.ComboOfferSide_description": function(d) { return "Build Your Combo 2 Medium Pizzas With 6-Toppings Combined & 1 Cheesy Bread"; },
  "tiles.ComboOfferSide_flag": function(d) { return "Build Your Combo"; },
  "tiles.ComboOfferSide_title": function(d) { return "2 Medium Pizzas With<br>6-Toppings Combined<br> & 1 Cheesy Bread"; },
  "tiles.ComboOfferSide_title_mobile": function(d) { return "2 Medium Pizzas With<br>6-Toppings Combined<br> & 1 Cheesy Bread"; },
  "tiles.CouponsAll": function(d) { return ""; },
  "tiles.Domino's Home Page - Domino's Pizza, Order Pizza Online for Delivery - Dominos.com": function(d) { return ""; },
  "tiles.Domino's Home Page - Domino's Pizza, Order Pizza Online for Delivery - Dominos.com.gt": function(d) { return ""; },
  "tiles.Domino's Home Page - Domino's Pizza, Order Pizza Online for Delivery - Dominos.com.sv": function(d) { return ""; },
  "tiles.Donair9655_alt": function(d) { return "Enjoy a Half Pound Donair for only $7.99. Order Now."; },
  "tiles.Donair_alt": function(d) { return "Enjoy a Quarter Pound Donair for only $4.99. Offer Code: 8655. Order Now."; },
  "tiles.FeastPizza2021Side_alt": function(d) { return "ANY LARGE FEAST PIZZA. INCLUDING OUR NEW CHICKEN TACO & CHEESEBURGER. ORDER NOW"; },
  "tiles.FeastPizza2021Side_description": function(d) { return "ANY LARGE FEAST PIZZA. INCLUDING OUR NEW CHICKEN TACO & CHEESEBURGER"; },
  "tiles.FeastPizza2021Side_flag": function(d) { return "ANY LARGE FEAST PIZZA"; },
  "tiles.FeastPizza2021Side_title": function(d) { return "<span class=\"promo__title__emphasis\">INCLUDING OUR NEW</span>CHICKEN TACO &<br>CHEESEBURGER"; },
  "tiles.FeastPizzaSide_alt": function(d) { return "ANY LARGE FEAST PIZZA. INCLUDING OUR NEW CHICKEN TACO & CHEESEBURGER. ORDER NOW"; },
  "tiles.FeastPizzaSide_calorie_details": function(d) { return "Cals 250 – 360 per slice"; },
  "tiles.FeastPizzaSide_description": function(d) { return "ANY LARGE FEAST PIZZA. INCLUDING OUR NEW CHICKEN TACO & CHEESEBURGER"; },
  "tiles.FeastPizzaSide_flag": function(d) { return "ANY LARGE FEAST PIZZA"; },
  "tiles.FeastPizzaSide_title": function(d) { return "<span class=\"promo__title__emphasis\">INCLUDING OUR NEW</span>CHICKEN TACO &<br>CHEESEBURGER"; },
  "tiles.FooterBrowseMenu_alt": function(d) { return "We've got more. View Full Menu"; },
  "tiles.FooterBrowseMenu_mobile_alt": function(d) { return "Feast Pizzas, Chocolate Lava Crunch Cake, Parmesan Bread Bites, Specialty Chicken"; },
  "tiles.FooterBrowseMenu_title": function(d) { return "We've got <span class=\"promo__title__emphasis\">more</span>"; },
  "tiles.FooterCokeGametime_alt": function(d) { return "Game time offer. 2 x MEDIUM 2-TOPPING PIZZAS 4 x ANY 500† mL COCA-COLA® BEVERAGES ORDER NOW $20"; },
  "tiles.FooterCokeGametime_description": function(d) { return "Game time offer. 2 x MEDIUM 2-TOPPING PIZZAS 4 x ANY 500† mL COCA-COLA® BEVERAGES ORDER NOW *Single units are sold at regular price. <span>&nbsp;</span>†Dasani® bottle is 591 mL and Fanta® bottle is 473 mL. Trademarks shown are the property of their respective trademark owners."; },
  "tiles.FooterCokeGametime_legal": function(d) { return "*Single units are sold at regular price. <sup>&" + "#" + "8224;</sup>Dasani® bottle is 591 mL and Fanta® bottle is 473 mL.<br>Trademarks shown are the property of their respective trademark owners."; },
  "tiles.FooterCokeGametime_title": function(d) { return "<span class=\"promo__title__emphasis\">Game time offer</span><span class=\"promo__title__emphasis__small\">2 x MEDIUM 2-TOPPING PIZZAS<br>4 x ANY 500<sup>&" + "#" + "8224;</sup> <span class=\"small\">m</span>L COCA-COLA® BEVERAGES </span>"; },
  "tiles.FooterDxp_description": function(d) { return "<h2>The ultimate pizza delivery vehicle.</h2>"; },
  "tiles.FooterFeast_alt": function(d) { return "NEW. CHICKEN TACO & CHEESEBURGER FEAST PIZZAS. ORDER NOW"; },
  "tiles.FooterFeast_title": function(d) { return "CHICKEN TACO &<br>CHEESEBURGER<br>FEAST PIZZAS"; },
  "tiles.FooterHiring2020_alt": function(d) { return "We’re Hiring. Join the Domino’s Team. APPLY NOW"; },
  "tiles.FooterHiring2020_details": function(d) { return "Join the Domino’s Team"; },
  "tiles.FooterHiring2020_title": function(d) { return "We’re Hiring"; },
  "tiles.FooterHiring_alt": function(d) { return "Now Hiring. Possibilities, topped with pride. Join Our Team"; },
  "tiles.FooterHiring_details": function(d) { return "Possibilities, topped with pride"; },
  "tiles.FooterHiring_title": function(d) { return "Now Hiring"; },
  "tiles.FooterPieRewards_title": function(d) { return "Earn Points Toward Free Pizza"; },
  "tiles.FooterPieRewards_title_mobile": function(d) { return "Earn Points<br>Toward<br>Free Pizza"; },
  "tiles.FooterPizzaPayback_description": function(d) { return "<h2>Domino's is giving away cool stuff</h2><span>Enter for a chance to win a payback today</span>"; },
  "tiles.FooterShareACoke_alt": function(d) { return "Get Any 2 500ML Coca-Cola(R) Soft Drinks For Only $3.49*. Order Now."; },
  "tiles.FooterShareACoke_description": function(d) { return "Get Any 2 500ML Coca-Cola(R) Soft Drinks For Only $3.49*"; },
  "tiles.FooterShareACoke_title": function(d) { return "Get Any 2 500 ML<br /><span class=\"promo__title__emphasis\">Coca-Cola&reg;<br />Soft Drinks</span><span class=\"promo__title__emphasis__small\">For Only</span>"; },
  "tiles.FooterSignUp_alt": function(d) { return "Be in the domi-know get bits on exclusive offers and coupons directly in your inbox. Sign up."; },
  "tiles.FooterSignUp_details": function(d) { return "Receive Pizza Coupons and Special Offers Right To Your Inbox"; },
  "tiles.FooterSignUp_flag": function(d) { return "Sign Me Up"; },
  "tiles.Hero50Off_alt": function(d) { return "50% Off All Pizzas at Menu Price"; },
  "tiles.HeroWeekLongCarryout_description": function(d) { return "<h2>All Day. Every Day. Carryout Deal</h2> <h3>Large 3-Topping Pizza $7.99 Each</h3> <h4>Carryout Only</h4>"; },
  "tiles.Hiring_alt": function(d) { return "We’re Hiring. Join the Domino’s Team. Apply Now"; },
  "tiles.HolidayGiftCard2023_alt": function(d) { return "Get a free pizza! When you buy a $30 gift card. Free pizza can be redeemed online only, from January 1st through February 29th, 2024."; },
  "tiles.HolidayGiftCard2023_btn": function(d) { return "Find a store"; },
  "tiles.HolidayGiftCard2023_description": function(d) { return "Get a free pizza! When you buy a $30 gift card. Free pizza can be redeemed online only, from January 1st through February 29th, 2024."; },
  "tiles.HolidayGiftCard2023_legal": function(d) { return "*Limit 4 free pizza coupons per order. Coupon is redeemable online only for 1 free medium 2-topping pizza. Valid from January 1st through February 29th 2024. No substitutions. Additional toppings, premium toppings and specialty crusts subject to additional charge. Not valid with any other coupon or offer. Must meet minimum purchase requirement for delivery. Limited delivery area. Delivery charges may apply. No cash value. Valid at participating locations. While supplies last."; },
  "tiles.HolidayGiftCard2023_title": function(d) { return "<div class=\"promo__main__title\">Get a free pizza!</div><div class=\"promo__subtitle\">When you buy a $30 gift card* </div><div class=\"promo__subtitle__details\">*Free pizza can be redeemed online only, from January 1st through February 29th, 2024</div><div class=\"promo__gift__card\"></div>"; },
  "tiles.Hotspots_button": function(d) { return "Explore Hotspots"; },
  "tiles.Large4ToppingCarsideHero_alt": function(d) { return "Try It Today With Carside or Carryout Only Large 4-Topping Pizza"; },
  "tiles.Large4ToppingCarsideHero_description": function(d) { return "Try It Today With Carside or Carryout Only Large 4-Topping Pizza. $12.99 Order Now"; },
  "tiles.Large4ToppingCarsideHero_flag": function(d) { return "Try It Today"; },
  "tiles.Large4ToppingCarsideHero_legal": function(d) { return "*Carside Delivery at participating<br>locations only (4-9pm)"; },
  "tiles.Large4ToppingCarsideHero_legal_featured": function(d) { return "*Carside Delivery at participating locations only (4-9pm)"; },
  "tiles.Large4ToppingCarsideHero_legal_profiled": function(d) { return "*Carside Delivery at participating locations only (4-9pm)"; },
  "tiles.Large4ToppingCarsideHero_title": function(d) { return "With Carside or Carryout Only<span class=\"promo__title__emphasis\">Large<br />4-Topping Pizza</span>"; },
  "tiles.Large4ToppingCarsideHero_title_featured": function(d) { return "With Carside or Carryout Only<span class=\"promo__title__emphasis\">Large 4-Topping Pizza</span>"; },
  "tiles.Large4ToppingCarsideHero_title_profiled": function(d) { return "With Carside or Carryout Only<span class=\"promo__title__emphasis\">Large<br />4-Topping Pizza</span>"; },
  "tiles.Large4ToppingHero_alt": function(d) { return "Large Feast Pizza or Large 4-topping Pizza"; },
  "tiles.Large4ToppingHero_description": function(d) { return "Large Feast Pizza or Large 4-topping Pizza. $12.99 Order Now"; },
  "tiles.Large4ToppingHero_title": function(d) { return "<span class=\"promo__title__emphasis\">Large<br />4-Topping<br />Pizza</span>Carryout Only"; },
  "tiles.Large4ToppingHero_title_profiled": function(d) { return "<span class=\"promo__title__emphasis\">Large 4-Topping<br />Pizza</span>Carryout Only"; },
  "tiles.Large4ToppingQuebec_alt": function(d) { return "Québécoise Large Feast Pizza or Large 4-topping Pizza"; },
  "tiles.Large4ToppingQuebec_description": function(d) { return "Québécoise Large Feast Pizza or Large 4-topping Pizza. $12.99 Order Now"; },
  "tiles.Large4ToppingQuebec_flag": function(d) { return "Québécoise Large Feast Pizza"; },
  "tiles.Large4ToppingQuebec_title": function(d) { return "<span class=\"promo__title__emphasis\">or Large</span>4-topping<br>Pizza"; },
  "tiles.Large4ToppingQuebec_title_mobile": function(d) { return "or Large<br>4-topping Pizza"; },
  "tiles.Large4ToppingSide_alt": function(d) { return "Large 4-Topping Pizza. Carryout Only $12.99 Order Now"; },
  "tiles.Large4ToppingSide_calorie_details": function(d) { return "Cals 250 – 370 per slice"; },
  "tiles.Large4ToppingSide_description": function(d) { return "Large 4-Topping Pizza. Carryout Only $12.99"; },
  "tiles.Large4ToppingSide_title": function(d) { return "Large<br />4-Topping<br />Pizza<span class=\"promo__title__smaller\">Carryout Only</span>"; },
  "tiles.LargeFeastSide_alt": function(d) { return "Any Large Feast Pizzas Our faves ready to go"; },
  "tiles.LargeFeastSide_description": function(d) { return "Any Large Feast Pizzas Our faves ready to go $16.99 each ORDER NOW"; },
  "tiles.LargeFeastSide_flag": function(d) { return "Any Large Feast Pizzas"; },
  "tiles.LargeFeastSide_title": function(d) { return "<span class=\"promo__title__emphasis\">Our faves<br>ready<br>to go</span>"; },
  "tiles.LargeFeastSide_title_mobile": function(d) { return "<span class=\"promo__title__emphasis\">Our faves<br>ready to go</span>"; },
  "tiles.LoyaltyMixMatchHero_alt": function(d) { return "Mix & Match Your Way To A Free Pizza! $8.99* each 6 orders of $10 or more = 7th Pizza is Free"; },
  "tiles.LoyaltyMixMatchHero_description": function(d) { return "Mix & Match Your Way To A Free Pizza! $8.99* each 6 orders of $10 or more = 7th Pizza is Free ORDER NOW 2 item minimum"; },
  "tiles.LoyaltyMixMatchHero_legal": function(d) { return "2 item minimum"; },
  "tiles.LoyaltyMixMatchHero_title": function(d) { return "Mix & Match<br>Your Way To A<br>Free Pizza!"; },
  "tiles.LoyaltyMixMatchHero_title_featured": function(d) { return "Mix & Match<br>Your Way To<br>A Free Pizza!"; },
  "tiles.MixMatchAny2OrMoreHero_alt": function(d) { return "Mix & Match Any 2 or More $8.99* esch ORDER NOW 2 item minimum"; },
  "tiles.MixMatchAny2OrMoreHero_description": function(d) { return "Mix & Match Any 2 or More $8.99* each ORDER NOW 2 item minimum"; },
  "tiles.MixMatchAny2OrMoreHero_legal": function(d) { return "*2 item minimum"; },
  "tiles.MixMatchAny2OrMoreHero_title": function(d) { return "<span class=\"promo__title__emphasis\"><span class=\"mix\">Mix</span><span class=\"amper\">&</span><span class=\"match\">Match</span></span><span class=\"promo__title__smaller\"><span class=\"unlimited\">Unlimited</span><span class=\"medium\">Medium</span><span class=\"two-topping-pizzas\">2-Topping Pizzas<span class=\"and-more\">and More</span></span>"; },
  "tiles.MixMatchAny2OrMoreHero_title_profiled": function(d) { return "<span class=\"promo__title__emphasis\"><span class=\"mix\">Mix</span><span class=\"amper\">&</span><span class=\"match\">Match</span></span><span class=\"promo__title__smaller\"><span class=\"unlimited\">Unlimited</span><span class=\"medium\">Medium</span><span class=\"two-topping-pizzas\">2-Topping Pizzas<span class=\"and-more\">and More</span></span>"; },
  "tiles.MixMatchAny2OrMoreHero_title_profiled_coupon": function(d) { return "<span class=\"promo__title__emphasis\"><span class=\"mix\">Mix</span><span class=\"amper\">&</span><span class=\"match\">Match</span></span><span class=\"promo__title__smaller\">Pizza, Pasta<span>and More</span></span>"; },
  "tiles.MixMatchAny2OrMoreSide_alt": function(d) { return "Mix & Match Any 2 or More $8.99* each"; },
  "tiles.MixMatchAny2OrMoreSide_description": function(d) { return "Mix & Match Any 2 or More $8.99* each ORDER NOW 2 item minimum"; },
  "tiles.MixMatchAny2OrMoreSide_legal": function(d) { return "2 item minimum"; },
  "tiles.MixMatchAny2OrMoreSide_title": function(d) { return "<span class=\"promo__title__emphasis\">Mix & Match <br> Any 2 <br> Or More</span>"; },
  "tiles.MixMatchChooseAny2Hero_alt": function(d) { return "Choose any 2 or more $7.99* ORDER NOW 2 item minimum"; },
  "tiles.MixMatchChooseAny2Hero_description": function(d) { return "Choose any 2 or more $7.99* ORDER NOW 2 item minimum"; },
  "tiles.MixMatchChooseAny2Hero_legal": function(d) { return "2 item minimum"; },
  "tiles.MixMatchChooseAny2Hero_title": function(d) { return "<span class=\"promo__title__emphasis\">Choose Any<br>2 Or More</span>"; },
  "tiles.MixMatchChooseAny2Side_alt": function(d) { return "Choose any 2 or more $7.99* ORDER NOW 2 item minimum"; },
  "tiles.MixMatchChooseAny2Side_description": function(d) { return "Choose any 2 or more $7.99* ORDER NOW 2 item minimum"; },
  "tiles.MixMatchChooseAny2Side_legal": function(d) { return "2 item minimum"; },
  "tiles.MixMatchChooseAny2Side_title": function(d) { return "<span class=\"promo__title__emphasis\">Choose<br>Any 2<br>Or More</span>"; },
  "tiles.MixMatchChooseAny2Side_title_mobile": function(d) { return "<span class=\"promo__title__emphasis\">Choose Any<br>2 Or More</span>"; },
  "tiles.MixMatchPizzaMoreHeroV3_alt": function(d) { return "Mix & Match Get Any 2 or More Including New Pepperoni Stuffed Cheesy Bread. $8.99* each ORDER NOW 2 item minimum"; },
  "tiles.MixMatchPizzaMoreHeroV3_description": function(d) { return "Mix & Match Get Any 2 or More Including New Pepperoni Stuffed Cheesy Bread. $8.99* each ORDER NOW 2 item minimum"; },
  "tiles.MixMatchPizzaMoreHeroV3_legal": function(d) { return "*2 item minimum"; },
  "tiles.MixMatchPizzaMoreHeroV3_title": function(d) { return "<span class=\"flag\">Mix & Match</span> <div class=\"get-any\">get any 2 <span>or more</span></div> <div class=\"including\">including</div> <div class=\"new-pepperoni\"><span class=\"new\">new</span> pepperoni</div> <div class=\"stuffed-cheesy-bread\">stuffed cheesy bread</div>"; },
  "tiles.MixMatchPizzaMoreHero_alt": function(d) { return "Mix & Match Pizza + More $8.99* esch ORDER NOW 2 item minimum"; },
  "tiles.MixMatchPizzaMoreHero_description": function(d) { return "Mix & Match Mix & Match Pizza + More $8.99* each ORDER NOW 2 item minimum"; },
  "tiles.MixMatchPizzaMoreHero_legal": function(d) { return "*2 item minimum"; },
  "tiles.MixMatchPizzaMoreHero_title": function(d) { return "<span class=\"promo__title__emphasis\"><span class=\"mix\">Mix</span><span class=\"amper\">&</span><span class=\"match\">Match</span></span><span class=\"promo__title__smaller\">Pizza + More</span>"; },
  "tiles.MixMatchPizzaMoreHero_title_profiled": function(d) { return "<span class=\"promo__title__emphasis\"><span class=\"mix\">Mix</span><span class=\"amper\">&</span><span class=\"match\">Match</span></span><span class=\"promo__title__smaller\">Pizza + More</span>"; },
  "tiles.PepperoniStuffedCheesyBread_alt": function(d) { return "Introducing Domino’s NEW Pepperoni Stuffed Cheesy Bread"; },
  "tiles.PepperoniStuffedCheesyBread_description": function(d) { return "Get any 2 or more for"; },
  "tiles.PepperoniStuffedCheesyBread_flag": function(d) { return "Introducing"; },
  "tiles.PepperoniStuffedCheesyBread_legal": function(d) { return "*2 item minimum"; },
  "tiles.PepperoniStuffedCheesyBread_title": function(d) { return "<span class=\"blue-flag\">Introducing</span> <div class=\"promo__title__container\"><span>Domino’s</span> <span>NEW</span> <span>Pepperoni</span> <span>Stuffed</span> <span>Cheesy Bread</span></div>"; },
  "tiles.Poe_alt": function(d) { return "PIZZA OVER EVERYTHING"; },
  "tiles.Poe_description": function(d) { return "PIZZA OVER EVERYTHING"; },
  "tiles.Poutine_alt": function(d) { return "New To Mix & Match"; },
  "tiles.Poutine_description": function(d) { return "New To Mix & Match"; },
  "tiles.Poutine_flag": function(d) { return "<span class=\"new\">New</span> <span class=\"mix-and-match\">Mix & Match</span>"; },
  "tiles.Poutine_legal": function(d) { return "Only available at select locations."; },
  "tiles.Poutine_title": function(d) { return "Poutine"; },
  "tiles.RefreshSummer_alt": function(d) { return "REFRESH YOUR SUMMER… TWO 500 mL COCA-COLA® BEVERAGES FOR $3.99 ADD TO ANY ORDER ORDER NOW *Coca-Cola Ltd, used under license"; },
  "tiles.RefreshSummer_legal": function(d) { return "ADD TO ANY ORDER"; },
  "tiles.RefreshSummer_title": function(d) { return "<span class=\"promo__title__emphasis\">Refresh Your Summer...</span>Two 500 <span class=\"small\">m</span>L <br>Coca-Cola® <br>Beverages For <br><span class=\"promo__title__emphasis__smaller\">*Coca-Cola Ltd, used under license</span>"; },
  "tiles.Rewards_alt": function(d) { return "Piece Of The Pie Rewards. Earn Points Toward Free Pizza. Join Now"; },
  "tiles.Safety_alt": function(d) { return "Safety is our " + "#" + "1 priority. Safe Food Handling. Sealed For Peace Of Mind. Zero Contact Delivery & Carryout. Learn More"; },
  "tiles.Safety_details": function(d) { return "<span class=\"safety-text safe\">Safe Food Handling</span><span class=\"safety-text sealed\">Sealed For Peace Of Mind</span><span class=\"safety-text zero\">Zero Contact Delivery<br>& Carryout</span>"; },
  "tiles.Safety_title": function(d) { return "Safety is our <span> " + "#" + "1 priority</span>"; },
  "tiles.Scb_alt": function(d) { return "January 16-29 Double Points Double Points with new Stuffed Cheesy Bread* *Earn 2X the points on every order that includes Stuffed Cheesy Bread. $10 minimum transaction."; },
  "tiles.Scb_description": function(d) { return "January 16-29 Double Points Double Points with new Stuffed Cheesy Bread* *Earn 2X the points on every order that includes Stuffed Cheesy Bread. $10 minimum transaction."; },
  "tiles.Side899Pan_alt": function(d) { return "Medium 2-Topping Handmade Pan Pizzas For $8.99 each"; },
  "tiles.Side899Pan_description": function(d) { return "<h2>Medium 2-Topping Handmade Pan Pizzas For $8.99 each</h2>"; },
  "tiles.SideCheesyMixMatch_alt": function(d) { return "Choose Any Two Or More For Only $6.99 each"; },
  "tiles.SideCheesyMixMatch_description": function(d) { return "<h2>Choose Any Two Or More For Only $5.99 each</h2> <h2>Specialty Chicken</h2> <h3>Medium 2-Topping Pizza*</h3> <h3>8-Piece Chicken</h3> <h3>Pasta in a Dish</h3> <h3>Stuffed Cheesy Bread</h3> <h3>Oven Baked Sandwich</h3> <h3>Marbled Cookie Brownie</h3> <h4>2-item minimum. *Handmade Pan Pizza may be extra.</h4>"; },
  "tiles.SideCos_alt": function(d) { return "Carry Out Only. All Large Two Topping Pizzas, $5.99 each. Valid May 22nd through May 28th."; },
  "tiles.SideStJudeBundle_alt": function(d) { return "$19.99 St Jude Bundle"; },
  "tiles.SideStJudeBundle_description": function(d) { return "<h3>St. Jude Meal Deal</h3> <h2>2 Medium 1-Topping Pizzas</h2> <h2>New Marbled Cookie Brownie</h2> <h2>And a 2-Liter of Coca-Cola for $19.99</h2> <h2>$1 Donation to St. Jude Children's Hospital</h2> <h2>*Handmade Pan Pizzas may be extra</h2>"; },
  "tiles.StuffedCheesyBread_alt": function(d) { return "Stuffed Cheesy Bread"; },
  "tiles.StuffedCheesyBread_description": function(d) { return "Stuffed <br> Cheesy Bread"; },
  "tiles.StuffedCheesyBread_flag": function(d) { return "<span class=\"new\">New</span> <span class=\"mix-and-match\">Mix & Match</span>"; },
  "tiles.StuffedCheesyBread_legal": function(d) { return "*2 item minimum."; },
  "tiles.UnlimitedLarge2Topping2020Footer_alt": function(d) { return "Unlimited Large 2-Topping Pizzas $10.99* Order Now. 2 pizza minimum"; },
  "tiles.UnlimitedLarge2Topping2020Footer_calorie_details": function(d) { return "Cals 240 – 330 per slice"; },
  "tiles.UnlimitedLarge2Topping2020Footer_description": function(d) { return "Unlimited Large 2-Topping Pizzas $10.99*"; },
  "tiles.UnlimitedLarge2Topping2020Footer_legal": function(d) { return "2 pizza minimum"; },
  "tiles.UnlimitedLarge2Topping2020Footer_title": function(d) { return "Unlimited Large <span class=\"promo__title__emphasis\">2-Topping<br />Pizzas</span>"; },
  "tiles.UnlimitedLarge2ToppingSide_alt": function(d) { return "Unlimited Large 2-Topping Pizzas $10.99* Order Now. 2 pizza minimum"; },
  "tiles.UnlimitedLarge2ToppingSide_calorie_details": function(d) { return "Cals 240 – 330 per slice"; },
  "tiles.UnlimitedLarge2ToppingSide_description": function(d) { return "Unlimited Large 2-Topping Pizzas $10.99*"; },
  "tiles.UnlimitedLarge2ToppingSide_legal": function(d) { return "2 pizza minimum"; },
  "tiles.UnlimitedLarge2ToppingSide_title": function(d) { return "Unlimited Large <span class=\"promo__title__emphasis\">2-Topping<br />Pizzas</span>"; },
  "tiles.UnlimitedMed2ToppingsFeatured_title1": function(d) { return "Unlimited Medium"; },
  "tiles.UnlimitedMed2ToppingsFeatured_title2": function(d) { return "2-Topping"; },
  "tiles.UnlimitedMed2ToppingsFeatured_title3": function(d) { return "Pizzas"; },
  "tiles.UnlimitedMed2ToppingsHero_alt": function(d) { return "Unlimited Medium 2-Topping Pizzas $7.99 each. 2 pizza minimum. Order Now"; },
  "tiles.UnlimitedMed2ToppingsHero_calorie_details": function(d) { return "Cals 180 – 250 per slice"; },
  "tiles.UnlimitedMed2ToppingsHero_description": function(d) { return "Unlimited Medium 2-Topping Pizzas $7.99 each. 2 pizza minimum"; },
  "tiles.UnlimitedMed2ToppingsHero_legal": function(d) { return "2 pizza minimum"; },
  "tiles.UnlimitedMed2ToppingsHero_title": function(d) { return "Unlimited Medium <span class=\"promo__title__emphasis\">2-Topping<br />Pizzas</span>"; },
  "tiles.XL4ToppingFooter_alt": function(d) { return "X-large 4-Topping Pizza $15.99* ORDER NOW"; },
  "tiles.XL4ToppingFooter_calorie_details": function(d) { return "Cals 280 – 430 per slice"; },
  "tiles.XL4ToppingFooter_description": function(d) { return "X-large 4-Topping Pizza $15.99*"; },
  "tiles.XL4ToppingFooter_title": function(d) { return "X-large<br />4-Topping<br />Pizza"; },
  "tiles.all_menu_priced_orders": function(d) { return "all menu-priced orders"; },
  "tiles.all_pizzas": function(d) { return "All Pizzas"; },
  "tiles.and_now": function(d) { return "And now"; },
  "tiles.any_of_our": function(d) { return "any of our"; },
  "tiles.apply_now": function(d) { return "APPLY NOW"; },
  "tiles.at765PerfectCombo": function(d) { return "Coupons 2 Medium 1-Topping Pizzas, 16-piece Parmesan Bread Bites, 8 Piece Cinnamon Twists and a 2 Liter of Coke for $19.99"; },
  "tiles.available_4_9pm": function(d) { return "<span>Available</span> <span class=\"dcd-2mg-tile__availability-text\">4-9pm</span>"; },
  "tiles.carryout_any": function(d) { return "Carryout Any"; },
  "tiles.carryout_deal": function(d) { return "Carryout Deal"; },
  "tiles.carryout_or_delivery": function(d) { return "Carryout or delivery"; },
  "tiles.carryout_special_deal": function(d) { return "Carryout Special Deal"; },
  "tiles.chicken_and_burger": function(d) { return "chicken taco & cheeseburger"; },
  "tiles.choose_any": function(d) { return "Choose Any"; },
  "tiles.choose_any_2_or_more": function(d) { return "Choose Any 2 or More"; },
  "tiles.cos_redesign_date": function(d) { return "1/20 - 1/26 "; },
  "tiles.cos_redesign_date_only": function(d) { return "Only"; },
  "tiles.cos_redesign_date_with_only": function(d) { return "1/20 - 1/26 Only"; },
  "tiles.cos_redesign_description": function(d) { return "Large 2&" + "#" + "8209;Topping Pizzas"; },
  "tiles.cos_redesign_details": function(d) { return "You must ask for this limited-time offer. Prices, participation, and charges may vary."; },
  "tiles.cos_redesign_tagline": function(d) { return "Order online, pick it up at the store."; },
  "tiles.cos_redesign_tagline_l1": function(d) { return "Order online, pick it "; },
  "tiles.cos_redesign_tagline_l2": function(d) { return "up at the store."; },
  "tiles.cos_redesign_tagline_l3": function(d) { return "You must ask for this limited-time offer. Prices, participation, and charges may vary."; },
  "tiles.crust_avail_varies": function(d) { return "Crust availability varies by size."; },
  "tiles.delivery_note": function(d) { return "Delivery orders are also subject to the local store’s delivery charge"; },
  "tiles.dominos_carside_delivery": function(d) { return "Domino's Carside Delivery®"; },
  "tiles.dominos_carside_delivery_49off": function(d) { return ""; },
  "tiles.dominos_carside_delivery_all_pizzas": function(d) { return "all pizzas"; },
  "tiles.dominos_carside_delivery_alt_text": function(d) { return "Domino's team member brings your order to your car when you carry out from a Domino's location."; },
  "tiles.dominos_carside_delivery_at_menu_price": function(d) { return "at menu price"; },
  "tiles.dominos_carside_delivery_details": function(d) { return "A new way to carry out. We bring the order to your car, contact free."; },
  "tiles.dominos_carside_delivery_legal": function(d) { return "You must select this limited-time offer. Offer applies to the pizza portion of your order only. Offer available between at least 4-9PM local time. Prices, participation, and charges may vary."; },
  "tiles.dominos_carside_delivery_off": function(d) { return "off"; },
  "tiles.dominos_carside_delivery_service_method_and_dates": function(d) { return "Online and Domino's Carside Delivery® only 12/6-12/12"; },
  "tiles.dominos_carside_delivery_tm": function(d) { return "Domino's Carside Delivery®"; },
  "tiles.donairFooter_alt": function(d) { return "Try Our Donair. Enjoy tender slices of donair meat, fresh tomato and onions all smothered with a distinctly sweet donair sauce wrapped in a golden brown pizza. Order Now"; },
  "tiles.donairFooter_description": function(d) { return "Try Our Donair. Enjoy tender slices of donair meat, fresh tomato and onions all smothered with a distinctly sweet donair sauce wrapped in a golden brown pizza."; },
  "tiles.each": function(d) { return "each"; },
  "tiles.each_4191_ca": function(d) { return "each"; },
  "tiles.ecom47364_carside_online_oly": function(d) { return "Online and Domino's <span class=\"dcd-footer__header-dates\">Carside Delivery® only 12/6-12/12</span>"; },
  "tiles.ecom47364_curbside_deal": function(d) { return "Curbside Pickup Deal"; },
  "tiles.ecom47364_dominos_curbside_pickup": function(d) { return "Domino's Curbside Pickup"; },
  "tiles.ecom47364_footer_legal": function(d) { return "Online Domino's Carside Delivery® only. You must select this limited-time offer. Offer applies to the pizza portion of your order only. Offer available between at least 4-9PM local time. Prices, participation, and charges may vary."; },
  "tiles.ecom47364_when_you_chose": function(d) { return "When you choose"; },
  "tiles.ecom57443_carryout_any_2_or_more": function(d) { return "Carryout Any 2 or More"; },
  "tiles.excludes_xl": function(d) { return ""; },
  "tiles.excludes_xl_and_specialty_pizzas_crust_availability_varies_by_size": function(d) { return "Carryout only. Size availability<br />varies by crust type. Excludes XL<br />and specialty pizzas. Local stores<br />may charge extra for some<br />toppings and sauces."; },
  "tiles.excludes_xl_and_specialty_pizzas_crust_availability_varies_by_size_featured": function(d) { return "Carryout only. Size availability varies by crust type.<br />Excludes XL and specialty pizzas. Local stores may charge extra for some toppings and sauces."; },
  "tiles.f_carryout_insurance_details": function(d) { return "Protecting your pizza from the unexpected."; },
  "tiles.f_carryout_insurance_flag": function(d) { return "It's insurance. For pizza."; },
  "tiles.f_dinnerbell_details": function(d) { return "Make rounding everyone up for pizza night easier than ever."; },
  "tiles.f_dinnerbell_flag": function(d) { return "Domino's Dinner Bell"; },
  "tiles.f_hotspots_details": function(d) { return "Ballpark. Dog Park. National Park. Get pizza delivered to over 150,000 unexpected locations."; },
  "tiles.f_hotspots_flag": function(d) { return "Domino's Hotspots® Are Now Open"; },
  "tiles.f_paving_details": function(d) { return "BAD ROADS SHOULDN'T HAPPEN TO GOOD PIZZA."; },
  "tiles.f_paving_flag": function(d) { return "NOMINATE YOUR TOWN"; },
  "tiles.f_points_for_pie_details": function(d) { return "Frozen? Homemade? Delivery? Not Domino’s®? Not a problem."; },
  "tiles.f_points_for_pie_flag": function(d) { return "Get Rewards Points for Any Pizza"; },
  "tiles.f_rewards_details": function(d) { return "Earn Points Toward Free Pizza When You Order Online, By Phone Or In-Store"; },
  "tiles.f_rewards_flag": function(d) { return "Piece of the Pie rewards®"; },
  "tiles.f_sms_details": function(d) { return "Sign up for SMS alerts and receive terrific coupons and online only deals."; },
  "tiles.f_sms_flag": function(d) { return "Want more deals?"; },
  "tiles.fifty_off_all_pizzas": function(d) { return "<span class='promo__title__emphasis'><div class='fifty-off-text'>50% off</div>all pizzas</span>at menu price"; },
  "tiles.fifty_off_all_pizzas_large": function(d) { return "50% off"; },
  "tiles.fifty_off_all_pizzas_medium": function(d) { return "all pizzas"; },
  "tiles.fifty_off_all_pizzas_medium_desktop": function(d) { return "all pizzas"; },
  "tiles.fifty_off_all_pizzas_no_markup": function(d) { return "50% off all pizzas"; },
  "tiles.fifty_off_all_pizzas_plain": function(d) { return "50% off all pizzas <span class=\"promo__title--small\">at menu price</span>"; },
  "tiles.fifty_off_all_pizzas_small": function(d) { return "at menu price"; },
  "tiles.fifty_off_all_pizzas_small_desktop": function(d) { return "at menu price"; },
  "tiles.free_pizza": function(d) { return "free pizza"; },
  "tiles.guarantee": function(d) { return "guarantee"; },
  "tiles.handmade_pan_pizza_deal": function(d) { return "Handmade Pan Pizza Deal"; },
  "tiles.handmade_pan_pizzas": function(d) { return "Handmade Pan Pizzas"; },
  "tiles.headed_to_your_car_in_2_min": function(d) { return "Headed to your car in 2 minutes or"; },
  "tiles.its_carryout_delivered": function(d) { return "It's carryout, delivered"; },
  "tiles.join_now": function(d) { return "Join Now"; },
  "tiles.join_our_team": function(d) { return "Join Our Team"; },
  "tiles.large": function(d) { return "large"; },
  "tiles.large_2_topping_pizzas": function(d) { return "Large<br />2-Topping<br />Pizzas"; },
  "tiles.large_2_topping_pizzas_2_topping_pizzas": function(d) { return "2-Topping Pizzas"; },
  "tiles.large_2_topping_pizzas_l1": function(d) { return "Large"; },
  "tiles.large_2_topping_pizzas_l2": function(d) { return "2-Topping"; },
  "tiles.large_2_topping_pizzas_l3": function(d) { return "Pizzas"; },
  "tiles.large_3_topping_pizzas": function(d) { return "<span class='promo__title__emphasis'>Large</span> 3-topping pizzas"; },
  "tiles.large_3_topping_pizzas_and": function(d) { return "Large 3-Topping Pizzas"; },
  "tiles.large_3_topping_pizzas_and_now": function(d) { return "Large 3-Topping Pizzas<span class='promo__title--shadow'>And now</span>Medium 3-Topping<br />Handmade Pan Pizzas"; },
  "tiles.large_are_14": function(d) { return "Large Pizzas are 14\","; },
  "tiles.large_or_pan": function(d) { return "Large or Pan"; },
  "tiles.late_night_deal": function(d) { return "late night deal"; },
  "tiles.learn_more": function(d) { return "Learn More"; },
  "tiles.loyalty_he_50_50": function(d) { return "50"; },
  "tiles.loyalty_he_50_all_pizzas": function(d) { return "all pizzas"; },
  "tiles.loyalty_he_50_at_menu_price": function(d) { return "at menu price"; },
  "tiles.loyalty_he_50_legal": function(d) { return "Offer is limited to eligible members of Piece of the Pie Rewards® who are invited to redeem this offer. Offer applies to the pizza portion of your menu-priced order only."; },
  "tiles.loyalty_he_50_off": function(d) { return "off"; },
  "tiles.loyalty_he_50_online_only": function(d) { return "online only 11/29 - 12/05"; },
  "tiles.loyalty_he_50_order_now": function(d) { return "Order now"; },
  "tiles.loyalty_he_50_percent": function(d) { return "%"; },
  "tiles.loyalty_he_50_this_week_only": function(d) { return "this week only"; },
  "tiles.loyalty_he_50_title": function(d) { return "member only deal"; },
  "tiles.loyalty_he_5Off_5_off": function(d) { return "$5 off"; },
  "tiles.loyalty_he_5Off_get": function(d) { return "get"; },
  "tiles.loyalty_he_5Off_legal": function(d) { return "Offer is limited to eligible members of Piece of the Pie Rewards® who are invited to redeem this offer."; },
  "tiles.loyalty_he_5Off_menu_priced": function(d) { return "menu-priced orders of $20 or more"; },
  "tiles.loyalty_he_5Off_online_only": function(d) { return "online only"; },
  "tiles.loyalty_he_5Off_order_now": function(d) { return "Order now"; },
  "tiles.loyalty_he_5Off_title": function(d) { return "member only deal"; },
  "tiles.loyalty_he_button": function(d) { return "Order now <span class=\"is-visually-hidden\">to get a free medium 1-topping pizza when you buy any pizza of equal or greater value</span>"; },
  "tiles.loyalty_he_content": function(d) { return "<div class=\"high-engagement__text--line-1\">Get a <span class=\"high-engagement__text--banner\">free</span></div><div class=\"high-engagement__text--line-2\">medium 1-topping</div><div class=\"high-engagement__text--line-3\">pizza</div><div class=\"high-engagement__text--line-4\">when you buy any pizza of equal or greater value</div>"; },
  "tiles.loyalty_he_content_legal": function(d) { return "Offer is limited to eligible members of Piece of the Pie Rewards® who are invited to redeem this offer. Handmade Pan will be extra."; },
  "tiles.loyalty_he_delivery_dp_dates": function(d) { return "online only 10/24-10/30"; },
  "tiles.loyalty_he_delivery_dp_double_points": function(d) { return "double points"; },
  "tiles.loyalty_he_delivery_dp_for_delivery": function(d) { return "for delivery"; },
  "tiles.loyalty_he_delivery_dp_legal": function(d) { return "Offer is limited to members of the Piece of the Pie Rewards® program who have received an email to redeem. Limit: one order of $10 or more (excludes tip and donations) per calendar day can earn points. Minimum purchase required for delivery. Online only."; },
  "tiles.loyalty_he_delivery_dp_this_week_only": function(d) { return "this week only"; },
  "tiles.loyalty_he_delivery_dp_title": function(d) { return "member appreciation week"; },
  "tiles.loyalty_he_dp": function(d) { return ""; },
  "tiles.loyalty_he_dp_dates": function(d) { return "2/28/2022 - 3/6/2022"; },
  "tiles.loyalty_he_dp_get": function(d) { return "get"; },
  "tiles.loyalty_he_dp_legal": function(d) { return "Offer is limited to eligible members of Piece of the Pie Rewards® who are invited to redeem this offer."; },
  "tiles.loyalty_he_dp_online_only": function(d) { return "online only"; },
  "tiles.loyalty_he_dp_order_now": function(d) { return "Order now"; },
  "tiles.loyalty_he_dp_this": function(d) { return "this"; },
  "tiles.loyalty_he_dp_title": function(d) { return "member only deal"; },
  "tiles.loyalty_he_dp_week_only": function(d) { return "week only"; },
  "tiles.loyalty_he_potpr_image_alt": function(d) { return "Piece of the Pie Rewards®"; },
  "tiles.loyalty_he_tile_title": function(d) { return "Member only deal"; },
  "tiles.medium_2_topping": function(d) { return "Medium 2-Topping"; },
  "tiles.medium_2_topping_handmade_pan_pizzas_l1": function(d) { return "Medium 2-Topping"; },
  "tiles.medium_2_topping_handmade_pan_pizzas_l2": function(d) { return "Handmade"; },
  "tiles.medium_2_topping_handmade_pan_pizzas_l3": function(d) { return "Pan Pizzas"; },
  "tiles.medium_3_Topping": function(d) { return "Medium 3-Topping"; },
  "tiles.mind_ordering_tile_title": function(d) { return "Domino's Pizza and Netflix Stranger Things present Mind Ordering. Order pizza with the power of your mind. Learn more at DominosMindOrdering.com."; },
  "tiles.mix_match_deal": function(d) { return "Mix & Match Deal"; },
  "tiles.mix_match_details": function(d) { return "You must ask for this offer while available. Offer is available only at participating stores. Prices, delivery area, and charges may vary by store. Delivery orders are subject to each local store's delivery charge. 2-item minimum. Bone-in Wings, Bread Bowl Pasta, and Handmade Pan Pizza will cost extra. In addition, your local store may charge extra for some menu items available with this offer and some crust types, toppings, and sauces. Visit www.dominos.com to see your local store's online menu and the checkout page when placing an online order for order-specific pricing."; },
  "tiles.mix_match_details_tots": function(d) { return "2-Item Minimum. Bone-in Wings, Bread Bowl Pasta and Handmade Pan Pizza will cost extra. Prices, delivery area, and charges may vary by store. Delivery orders are subject to each local store's delivery charge."; },
  "tiles.mix_match_details_tots_click_here": function(d) { return "Click here for full details."; },
  "tiles.mix_match_including": function(d) { return "including"; },
  "tiles.mix_match_loaded_tots": function(d) { return "loaded tots"; },
  "tiles.mix_match_new": function(d) { return "new"; },
  "tiles.mix_match_new_pepperoni": function(d) { return "<i>New</i> Pepperoni"; },
  "tiles.mobile_menu_tile_legal": function(d) { return "Item availability may vary based on selected store."; },
  "tiles.mobile_menu_tile_text_1": function(d) { return "specialty pizzas"; },
  "tiles.mobile_menu_tile_text_2": function(d) { return "parmesan bread bites"; },
  "tiles.mobile_menu_tile_text_3": function(d) { return "specialty chicken"; },
  "tiles.mobile_menu_tile_text_4": function(d) { return "chocolate lava crunch cakes"; },
  "tiles.mobile_menu_view_full_menu": function(d) { return "View Full Menu"; },
  "tiles.new": function(d) { return "new"; },
  "tiles.new_combos": function(d) { return "new"; },
  "tiles.new_combos_1": function(d) { return "Dips & Twists Combos"; },
  "tiles.new_combos_2": function(d) { return "8-Piece Wings"; },
  "tiles.online_only_text_only": function(d) { return "Online Only"; },
  "tiles.online_only_xxx_xxx": function(d) { return "Online Only 11/14 - 11/20"; },
  "tiles.or": function(d) { return "or"; },
  "tiles.order_now": function(d) { return "Order Now"; },
  "tiles.order_online": function(d) { return "Order online,&nbsp;"; },
  "tiles.order_online_pickup_at_store": function(d) { return "Order online,<br />pick it up at the store"; },
  "tiles.pan_are_12": function(d) { return "Handmade Pan Pizzas are 12\""; },
  "tiles.perect_combo_details": function(d) { return "Medium 1-Topping Pizzas. Handmade Pan Pizzas will be extra. No substitutions permitted."; },
  "tiles.perfect_combo_deal": function(d) { return "Perfect Combo Deal"; },
  "tiles.perfect_combo_details": function(d) { return "Handmade Pan Pizzas will be extra.<br/>No substitutions permitted."; },
  "tiles.perfect_combo_details_flag": function(d) { return "Perfect Combo Deal"; },
  "tiles.pickup_at_store": function(d) { return "pick it up at the store"; },
  "tiles.pickup_at_store_period": function(d) { return "pick it up at the store."; },
  "tiles.see_price": function(d) { return "SEE PRICE"; },
  "tiles.specialty_pizzas": function(d) { return "specialty pizzas"; },
  "tiles.st_jude_side_tile_image_alt": function(d) { return "Give a gift that could last a lifetime. Order now and donate to St. Jude Children’s Research Hospital."; },
  "tiles.stjude_includes_1_donation": function(d) { return "Includes $1&nbsp;Donation"; },
  "tiles.stjude_meal_deal": function(d) { return "St. Jude Meal Deal"; },
  "tiles.stjude_valid_perfect_combo_details": function(d) { return "Valid 10/21/19-1/5/20. Handmade Pan Pizzas will be extra. No substitutions permitted."; },
  "tiles.this_week_online_only": function(d) { return "this week online only"; },
  "tiles.this_week_only": function(d) { return "this week only"; },
  "tiles.view_full_menu": function(d) { return "View Full Menu"; },
  "tiles.weeklong_carryout_deal": function(d) { return "Weeklong Carryout Deal"; },
  "tiles.with_your_next_order": function(d) { return "with your next order"; },
  "tiles.wlc_dips_twists_alt": function(d) { return "Carryout Deal - All Pizzas 1-Topping or New Dips and Twists Combos $7.99 each"; },
  "tiles.wlc_dips_twists_description": function(d) { return "<h2>All Pizzas 1-Topping or New Dips and Twists Combos</h2> <h2>$7.99 each</h2> <h2>Excludes XL & Specialty Pizzas. Crust availabilty varies by size</h2> <h2>Order online, pick it up at the store</h2>"; },
  "tiles.you_must_ask": function(d) { return "You must ask for this limited time offer. Prices, participation, and delivery area charges may vary. Discount applies to menu priced items only."; },
  "tiles.you_must_ask_for_discount": function(d) { return "You must ask for this limited-time offer. Prices, participation, and charges may vary. Discount applies to menu priced items only."; }
}
}
);
