define([], function anonymous(
) {
var pluralFuncs = {
  en: function(n, ord) {
    var s = String(n).split('.'), v0 = !s[1], t0 = Number(s[0]) == n,
        n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2);
    if (ord) return (n10 == 1 && n100 != 11) ? 'one'
        : (n10 == 2 && n100 != 12) ? 'two'
        : (n10 == 3 && n100 != 13) ? 'few'
        : 'other';
    return (n == 1 && v0) ? 'one' : 'other';
  }
};
var fmt = {};
var number = function(value, offset) {
  if (isNaN(value)) throw new Error("'" + value + "' isn't a number.");
  return value - (offset || 0);
};
var plural = function(value, offset, lcfunc, data, isOrdinal) {
  if ({}.hasOwnProperty.call(data, value)) return data[value]();
  if (offset) value -= offset;
  var key = lcfunc(value, isOrdinal);
  if (key in data) return data[key]();
  return data.other();
};
var select = function(value, data) {
  if ({}.hasOwnProperty.call(data, value)) return data[value]();
  return data.other()
};

return {
  "errors.Byopcoupons": function(d) { return "Don't see what you're looking for? You can build any pizza you want and it will still apply to your Group Order discount."; },
  "errors.CouponPrerequisiteUnfulfilled": function(d) { return "Your " + d.val1 + " will be removed if you continue to checkout with an incomplete " + d.val2 + " coupon. <div><button type=\"button\" class=\"btn btn--outline js-continueButton\" data-remove-coupon-code=" + d.val3 + ">continue checkout</button> <button class=\"js-closeButton\" data-add-to-coupon-id=\"" + d.val4 + "\">complete coupon</button></div>."; },
  "errors.You can use your new password to sign in to your Pizza Profile online or through the Domino's mobile apps.": function(d) { return ""; },
  "errors.adjustPayment": function(d) { return "Please select a card or adjust your payment type."; },
  "errors.at998powerCustomerPhoneUsedTooManyTimes": function(d) { return "Sorry, this account cannot be saved. This phone number is already registered to another Pizza Profile. Please use a different phone number for your account. You can still create an account and claim points on this order by continuing and clicking on CLAIM POINTS."; },
  "errors.byopcoupons": function(d) { return "Don't see what you're looking for? You can build any pizza you want and it will still apply to your Group Order discount."; },
  "errors.byopnocoupons": function(d) { return "Don't see what you're looking for? You can build any pizza you want."; },
  "errors.campaignOnlyCouponUnavailableForCustomer": function(d) { return "Sorry, you are not eligible for this offer. You can browse your store's coupons to find another one."; },
  "errors.carryout_no_results": function(d) { return "Sorry, but no stores found for the location \"" + d.val1 + "\". Please try entering a different location in the search field directly above the map."; },
  "errors.carryout_no_results_CANADA": function(d) { return "Sorry, but no stores found for the location. Please try entering a different location in the search field directly above the map."; },
  "errors.claimRewardsUnknownError": function(d) { return "Well, this is embarrassing. We're having a little trouble with the Piece of the Pie Rewards&reg;. Please check your reward history to make sure you received your points. If you haven't, please try again in 24 hours. Sorry for the inconvenience!"; },
  "errors.code-dpcDfcSchoolCodeInvalidRegion": function(d) { return "We're sorry, but the school you chose is in a different province than the store you are ordering from.  Schools must be in the same province as the store that you're ordering from."; },
  "errors.confirmAddressDelete": function(d) { return "Are you sure want to delete this address?"; },
  "errors.confirmCardDelete": function(d) { return "Are you sure want to delete this card?"; },
  "errors.confirmEoeSmsOptinDelete": function(d) { return "Are you sure you want to lose your ability to order by texting?"; },
  "errors.confirmEoeTweetOptinDelete": function(d) { return "Are you sure you want to lose your ability to order by Tweeting?"; },
  "errors.confirmLeaveWhileEditing": function(d) { return "You are currently editing your Pizza Profile. If you leave this page, unsaved progress will be lost. Are you sure you want to continue?"; },
  "errors.confirmPaymentAccountDelete": function(d) { return "Are you sure want to unlink this payment account?"; },
  "errors.confirmPrimaryAddressChange": function(d) { return "Do you want to make this your primary address?"; },
  "errors.confirmPrimaryCardChange": function(d) { return "Do you want to make this your primary card?"; },
  "errors.confirmPrimaryPaymentAccountChange": function(d) { return "Do you want to make this your primary payment account"; },
  "errors.copyandpayNotApprovedCA": function(d) { return "We’re sorry, we’ve encountered an issue processing your payment. Please verify your credit card information and try again."; },
  "errors.delayedLoyaltyAccountCreation": function(d) { return "You can still create an account and claim points on this order by continuing and clicking on CLAIM POINTS."; },
  "errors.discountLevelCurrent": function(d) { return "current"; },
  "errors.discountLevelNext": function(d) { return "next"; },
  "errors.dpcDfcSchoolCode404": function(d) { return "We're sorry, but the school code you entered was not found or is not currently participating in this program."; },
  "errors.duc_check_in_error": function(d) { return "Looks like something went wrong. Please try again."; },
  "errors.duc_save_order_error": function(d) { return "Your order was placed, but there was a problem saving it as a Carside delivery. Please call the store when you arrive to let them know you are there. They will bring your order to your vehicle."; },
  "errors.duplicateMobileNumber": function(d) { return "Sorry, this mobile number is already in use with another Pizza Profile."; },
  "errors.eAPIRedirectBOLO": function(d) { return ""; },
  "errors.eAddressIncompleteError": function(d) { return "We're sorry, the address you are using is incomplete, please return to store locator and <a class=\"js-continueButton\" href=\"" + d.ctx + "/pages/order/" + "#" + "/locations/search/?type=Delivery\">enter a full address.</a>"; },
  "errors.eAddressIncompleteErrorHyphen": function(d) { return ""; },
  "errors.eAddressIncompleteErrorWithRefund": function(d) { return "Unfortunately the order failed because the address you are using is incomplete, please return to store locator and <a class=\"js-continueButton\" href=\"" + d.ctx + "/pages/order/" + "#" + "/locations/search/?type=Delivery\">enter a full address.</a>  Though your credit card is charged at this time, we have initiated a refund which should appear in 4-7 business days from now. We apologize for the inconvenience. Please call the store after 7 business days, if you haven’t received the refund."; },
  "errors.eAddresseIncompleteErrorWithRefund": function(d) { return ""; },
  "errors.eAdyen2AuthorizationError": function(d) { return "Erro na autorização do pagamento. Por favor, tente de novo!"; },
  "errors.eAdyen2Cancelled": function(d) { return "A sua transação foi cancelada."; },
  "errors.eAdyen2Declined": function(d) { return "Unfortunately your payment was not authorized. Please make sure your payment details are correct and try again. If the issue persists, please contact your bank or card issuer."; },
  "errors.eAdyen2IncorrectData": function(d) { return "Os dados inseridos estão incorretos! Por favor, tente novamente."; },
  "errors.eAdyen2NotAuthorizedBank": function(d) { return "Transação não autorizada. Por favor, entre em contato com o seu banco."; },
  "errors.eAdyen2NotAuthorizedBankInfo": function(d) { return "Transação não autorizada. Por favor, entre em contato com o seu banco para mais informações."; },
  "errors.eAdyen2NotAuthorizedBankOrOther": function(d) { return "Transação não autorizada. Por favor, entre em contato com o seu banco ou tente outra forma de pagamento."; },
  "errors.eAdyen2NotAuthorizedTryAgain": function(d) { return "Transação não autorizada. Por favor, tente outra forma de pagamento."; },
  "errors.eAdyen2PaymentDetailNotFound": function(d) { return "Your saved card details must be entered again. Please choose “Use Other Card” and provide the requested card information. You will then be able to save your card again."; },
  "errors.eAdyen2TechnicalError": function(d) { return "Unfortunately, your payment failed due to a technical problem. Please try again."; },
  "errors.eAdyenAuthorizationFailed": function(d) { return "Sorry the payment was not authorized. Please double check payment details and try again."; },
  "errors.eAdyenEcryptionLibraryFailed": function(d) { return "Sorry, there was an error processing the payment. Please try again."; },
  "errors.eAlamarWalletPaymentAuthorizationFailed": function(d) { return "We are sorry. We can't use your e-wallet balance for now. Use a different payment method or try again later."; },
  "errors.eAlcoholCutoffTime": function(d) { return ""; },
  "errors.eAlcoholUnavailable": function(d) { return ""; },
  "errors.eAlphaNumeric": function(d) { return d.val1 + " is not alphanumeric."; },
  "errors.eAmericanExpress": function(d) { return d.val1 + " is not a valid AMERICAN EXPRESS number."; },
  "errors.eApplePayGenericError": function(d) { return ""; },
  "errors.eBingMapModuleFailed": function(d) { return "We are sorry but Bing maps is not responding. Please try again later or order a different way"; },
  "errors.eBothPasswordsMustMatch": function(d) { return "Both password fields must match."; },
  "errors.eCEP": function(d) { return ""; },
  "errors.eCEPNotFound": function(d) { return ""; },
  "errors.eCPF": function(d) { return "Please enter valid CPF/CNP"; },
  "errors.eCVV": function(d) { return "Please enter a valid Security Code."; },
  "errors.eCheeseHasBeenResetForCrustType": function(d) { return "Cheese has been added back to your " + d.val1 + ". It is required for product quality"; },
  "errors.eCodeRequired": function(d) { return "This field is required."; },
  "errors.eCompleteAllFields": function(d) { return "Please complete all fields"; },
  "errors.eCompletePrepaymentRequiredForCarsideOrders": function(d) { return "Pre-payment required for Domino's Carside Delivery®"; },
  "errors.eConfigurationMissing": function(d) { return "El pago con tarjeta de crédito a través del portal no está disponible en la sucursal por el momento por favor seleccione otro método de pago"; },
  "errors.eCouponBelowMinimumOrderAmount": function(d) { return "Minimum purchase of " + d.val1 + " (excludes donations and tips) required when redeeming this coupon. Please add more to your order OR continue to checkout without using this coupon."; },
  "errors.eCouponBelowMinimumOrderAmountHyphen": function(d) { return ""; },
  "errors.eCouponBelowMinimumOrderAmountWithRefund": function(d) { return "Unfortunately the order failed because a minimum purchase of " + d.val1 + " (before tax, delivery charges and gratuities) is required when redeeming this coupon. Please add more to your order OR continue to checkout without using this coupon.  Though your credit card is charged at this time, we have initiated a refund which should appear in 4-7 business days from now. We apologize for the inconvenience. Please call the store after 7 business days, if you haven’t received the refund."; },
  "errors.eCouponDate": function(d) { return "Sorry, the promotion/coupon code you tried to enter is invalid for the date of your current order."; },
  "errors.eCouponDay": function(d) { return "Sorry, the promotion/coupon code you tried to enter is invalid for the day of week of your current order."; },
  "errors.eCouponDucServiceMethod": function(d) { return "The offer you selected is valid for Domino's Carside Delivery™ orders only, however your order is currently set for " + d.val2 + ". You'll be asked to provide car details in the ordering process. Would you like to change your order to Domino's Carside Delivery™, or do you want to remove the offer from your cart? <div class=\"buttons fr\"><button type=\"button\" class=\"btn btn--secondary js-continueButton\" data-quid=\"remove-coupon\">Remove Offer</button> <button type=\"button\" class=\"btn js-closeButton\" data-quid=\"generic-overlay-switch-service-method\" >Order " + d.val1 + "</button><div class=\"clr\"><!-- --></div></div>"; },
  "errors.eCouponDucServiceMethodChanged": function(d) { return "The coupon in your cart is for Domino's Carside Delivery™ orders only. If you change your order to " + d.val2 + ", this coupon will be removed. Would you like to change your order to " + d.val2 + " and remove the coupon, or order Domino's Carside Delivery™ and keep the coupon in your cart.<div class=\"buttons fr\"><button type=\"button\" class=\"btn js-continueButton\" data-quid=\"generic-overlay-switch-service-method\">Order " + d.val2 + "</button> <button type=\"button\" class=\"btn btn--secondary js-closeButton\" data-quid=\"generic-overlay-keep-service-method\">Order " + d.val1 + "</button><div class=\"clr\"><!-- --></div></div><div class=\"clr\"><!-- --></div>"; },
  "errors.eCouponDucServiceMethodUnavailable": function(d) { return "We're sorry, your store does not currently offer Domino's Carside Delivery™. The coupon you've selected is only valid for Domino’s Carside Delivery&reg; and will be removed from your order. You can browse your store's coupons to find another one."; },
  "errors.eCouponDuplicate": function(d) { return "Sorry, the promotion/coupon code you entered is only allowed to be used " + d.val1 + " time(s) on your current order."; },
  "errors.eCouponInvalid": function(d) { return "Sorry, invalid coupon/promotion code. This code may not be active at this store. If the code was entered manually, please ensure the code is entered exactly as it appears, including dashes and special characters."; },
  "errors.eCouponInvalidForFutureOrder": function(d) { return "We're sorry, this coupon cannot be used for timed orders."; },
  "errors.eCouponInvalidSameDayCarryoutTips": function(d) { return "Sorry, redemptions are limited to once a day. Please return again tomorrow to use your $3 Carryout Tip"; },
  "errors.eCouponInvalidTMobileCode": function(d) { return "We’re sorry – the T-Mobile Tuesdays offer is currently unavailable, because this store has reached its offer limit.<br /><br />As a reminder, this offer is only available on Tuesdays."; },
  "errors.eCouponIsInvalidForDayPart": function(d) { return "Sorry, the coupon you selected is not available at this time and will be removed from your cart. Please review the updated order total before placing your order."; },
  "errors.eCouponMinimumPaymentAmount": function(d) { return "Minimum purchase of " + d.val1 + " required when redeeming this offer. Please add more to your order OR continue to checkout without using this offer."; },
  "errors.eCouponMinimumPaymentAmountWithRefund": function(d) { return "Unfortunately the order failed because a minimum purchase of " + d.val1 + " is required when redeeming this offer. Please add more to your order OR continue to checkout without using this offer.  Though your credit card is charged at this time, we have initiated a refund which should appear in 4-7 business days from now. We apologize for the inconvenience. Please call the store after 7 business days, if you haven’t received the refund."; },
  "errors.eCouponServiceMethod": function(d) { return "The offer you selected is valid for " + d.val1 + " orders only, however your order is currently set for " + d.val2 + ". Would you like to change your order to " + d.val1 + ", or do you want to remove the offer from your cart? <div class=\"buttons fr\"><button type=\"button\" class=\"btn btn--secondary js-continueButton\" data-quid=\"remove-coupon\">Remove Offer</button> <button type=\"button\" class=\"btn js-closeButton\" data-quid=\"generic-overlay-switch-service-method\" >Order " + d.val1 + "</button><div class=\"clr\"><!-- --></div></div><div class=\"clr\"><!-- --></div>"; },
  "errors.eCouponServiceMethodChanged": function(d) { return "You have a coupon in your cart that is for " + d.val1 + " orders only. If you change your order to " + d.val2 + ", we will automatically remove this coupon from your cart. Would you like to change your order to " + d.val2 + " and remove the coupon, or would you rather order " + d.val1 + " and keep the coupon in your cart?<div class=\"buttons fr\"><button type=\"button\" class=\"btn js-continueButton\" data-quid=\"generic-overlay-switch-service-method\">Order " + d.val2 + "</button> <button type=\"button\" class=\"btn btn--secondary js-closeButton\" data-quid=\"generic-overlay-keep-service-method\">Order " + d.val1 + "</button><div class=\"clr\"><!-- --></div></div><div class=\"clr\"><!-- --></div>"; },
  "errors.eCouponServiceMethodNeedsLocation": function(d) { return "The offer you selected is valid for " + d.val1 + " orders only, however your order is currently set for " + d.val2 + ". Would you like to change your order to " + d.val1 + ", or do you want to remove the offer from your cart? <div class=\"buttons fr\"><button type=\"button\" class=\"btn btn--secondary js-continueButton\" data-quid=\"remove-coupon\">Remove Offer</button> <a href=\"" + d.ctx + "/pages/order/" + "#" + "!/locations/search/\" class=\"btn js-goToLocator\" data-quid=\"generic-overlay-redirect-to-locator\">Order " + d.val1 + "</a><div class=\"clr\"><!-- --></div></div><div class=\"clr\"><!-- --></div>"; },
  "errors.eCouponServiceMethodNoRemove": function(d) { return "The offer you selected is valid for " + d.val1 + " orders only, however your order is currently set for " + d.val2 + ". Would you like to change your order to " + d.val1 + ", or do you want to remove the offer from your cart? <div class=\"buttons fr\"><button type=\"button\" class=\"btn js-closeButton\" data-quid=\"generic-overlay-switch-service-method\" >Order " + d.val1 + "</button><div class=\"clr\"><!-- --></div></div><div class=\"clr\"><!-- --></div>"; },
  "errors.eCouponTime": function(d) { return "Sorry, the promotion/coupon code you tried to enter is invalid for the time specified on your current order."; },
  "errors.eCouponTimeInvalid": function(d) { return "Sorry, invalid coupon/promotion code. This code may not be active at this store. If the code was entered manually, please ensure the code is entered exactly as it appears, including dashes and special characters."; },
  "errors.eCouponUsageCountViolation": function(d) { return "The deal you've selected has reached its usage limit and is no longer valid. This deal will be removed from your order."; },
  "errors.eCouponWBUsageCountViolation": function(d) { return "The deal you've selected has reached its usage limit and is no longer valid. This deal will be removed from your order."; },
  "errors.eCouponsNotAvailable": function(d) { return "We're sorry, there are no available coupons for this store at this time."; },
  "errors.eCredibanCoAborted": function(d) { return ""; },
  "errors.eCredibanCoCancelled": function(d) { return ""; },
  "errors.eCredibanCoDeclined": function(d) { return ""; },
  "errors.eCredibanCoFailed": function(d) { return ""; },
  "errors.eCredibanCoInsufficientBalance": function(d) { return ""; },
  "errors.eCredibanCoLimitExceeded": function(d) { return ""; },
  "errors.eCredibanCoTechnicalError": function(d) { return ""; },
  "errors.eCreditCardAuthNotificationMissing": function(d) { return ""; },
  "errors.eCreditCardDeclined": function(d) { return "Sorry the payment was not authorized. Please double check payment details and try again."; },
  "errors.eCreditCardNumber": function(d) { return "Credit Card Number is not valid."; },
  "errors.eCreditCardRefundTriggered": function(d) { return "Sorry there was an error in processing your order. Though your credit card is charged at this time, we have initiated a refund which should appear in 4-7 business days from now. We apologize for the inconvenience. Please call the store after 7 business days, if you haven’t received the refund."; },
  "errors.eCreditCardTransactionUnsuccessful": function(d) { return "Sorry, the credit card transaction was not successful. Please try again or select a different payment method for your order."; },
  "errors.eCreditExpirationDate": function(d) { return "Expiration Date must be in the future."; },
  "errors.eCreditExpirationDateEmpty": function(d) { return "Your Expiration Date is empty."; },
  "errors.eCreditExpirationDateNotFuture": function(d) { return "Your Expiration Date must be in the future."; },
  "errors.eCustomerConfirmEmail": function(d) { return d.val1 + " doesn't match your email."; },
  "errors.eCustomerConfirmPasswoprd": function(d) { return d.val1 + " doesn't match your password."; },
  "errors.eCustomerConfirmPassword": function(d) { return d.val1 + " doesn't match your password."; },
  "errors.eCustomerEmailError": function(d) { return "We're sorry, we could not save your email preferences at this time. Please try again later."; },
  "errors.eCustomerEmailSuccess": function(d) { return "Thanks! You are now enrolled to have these hot offers delivered right to you. ( <a href=\"" + d.ctx + "/pages/order/\">Continue Ordering</a> )"; },
  "errors.eCustomerEmailUnsubscribe": function(d) { return "You have successfully opted out of Email or Text Offers. If you would like to opt back in to receive terrific coupons and online only deals, please wait 15 minutes to make sure we can get you back on the list.( <a href=\"" + d.ctx + "/pages/order/\">Continue Ordering</a> )"; },
  "errors.eCustomerNewPassword": function(d) { return "Your new password must be different from current password."; },
  "errors.eCustomerPassword": function(d) { return "Doesn't meet the minimum password guidelines."; },
  "errors.eCustomerPasswordAlreadyUsed": function(d) { return "We're sorry, please enter a password that has not previously been used."; },
  "errors.eCustomerTermsOfUse": function(d) { return "You must agree to the terms of use."; },
  "errors.eDeliveryClosed": function(d) { return "We are sorry, the delivery service is closed for the day. You may edit your order to pick up from the closest carryout store!"; },
  "errors.eDeliveryDisabled": function(d) { return "We are sorry, the delivery service is temporarily unavailable in the store. We are working on bringing it back. You may edit your order to pick up from the closest carryout store!"; },
  "errors.eDinersClub": function(d) { return d.val1 + " is not a valid DINERS CLUB number."; },
  "errors.eDinnerBellGroupNotFound": function(d) { return "This group is no longer available."; },
  "errors.eDinnerBellServiceDown": function(d) { return "Well, this is awkward. Service is temporarily down. Try again in a few minutes."; },
  "errors.eDinnerBellTryAgain": function(d) { return "Uh oh. Something’s not right. Try again in a few minutes."; },
  "errors.eDiscover": function(d) { return d.val1 + " is not a valid DISCOVER number."; },
  "errors.eDownloadFlash": function(d) { return "For the hottest Dominos.com experience, you need to install <a href=\"http://get.adobe.com/flashplayer/\" target=\"_blank\">Adobe Flash Player</a>.<div class=\"buttons fr\"><a class=\"btn js-closeButton\" href=\"" + "#" + "\"><span>Continue</span></a></div><div class=\"clr\"><!-- --></div>"; },
  "errors.eDropAPin": function(d) { return "Please drop a pin on your delivery location so we can find your nearest store."; },
  "errors.eDuplicateOrderID": function(d) { return "Your order has already been placed – please click <a href=\"" + d.ctx + "/pages/tracker/" + "#" + "/track/order/\">here</a> to track the progress through the Domino’s Pizza Tracker!"; },
  "errors.eDuplicatePersonalCoupon": function(d) { return "Sorry, only one e-coupon can be redeemed for this order. If you like to proceed forward, please remove the existing e-coupon and try again"; },
  "errors.eDuplicatedEmail": function(d) { return ""; },
  "errors.eEasyOrderCannotBeCreated": function(d) { return "We are sorry Easy Order cannot be created at this time."; },
  "errors.eEmail": function(d) { return d.val1 + " is not an email address."; },
  "errors.eEmailAlreadyUsed": function(d) { return ""; },
  "errors.eEmpty": function(d) { return d.val1 + " is empty."; },
  "errors.eEqual": function(d) { return d.val1 + " does not match."; },
  "errors.eExpiredCode": function(d) { return "Code expired, please tap Resend Code link below to get new verification code"; },
  "errors.eExpiredOffer": function(d) { return "Looks like the offer you're trying to activate has expired or is no longer available."; },
  "errors.eFNBAuthorizationFailed": function(d) { return "We are sorry but we are unable to process your payment. Please verify the information and try again or use a different payment type. If errors persist, contact the store."; },
  "errors.eFutureOrderDateNotAllowedCA": function(d) { return "We are sorry, orders for future dates cannot be paid by online credit card.  Please modify your payment method and resubmit your order"; },
  "errors.eGenericCreditCardMessage": function(d) { return "We are sorry, but we are unable to process your payment. Please verify the information and try again, or use a different payment type.<br /><br />NOTE:  Each time you click on the “Place Order” button your bank may place a hold on funds in your account. Please make sure you submit the correct Expiration Date, Security Code, and Billing Postal Code."; },
  "errors.eGenericCreditCardMessageKiosk": function(d) { return "We're sorry! We are having trouble processing your payment. Please see a team member for assistance.<br /><div class=\"buttons fr\"><a class=\"btn js-closeButton--kiosk\" href=\"" + "#" + "\">Got it, thanks!</a></div>"; },
  "errors.eGenericCreditCardMessageKioskDelivery": function(d) { return "We're sorry! We are having trouble processing your payment. Please call Domino's at " + d.val1 + " for assistance.<button class=\"btn kiosk-restart js-closeButton--kiosk\">Got It, Thanks!</button>"; },
  "errors.eGenericPhoneNumber": function(d) { return "Phone Number is not valid."; },
  "errors.eGenericPointOfServiceError": function(d) { return "We're sorry, there seems to be a technical problem. Please try again."; },
  "errors.eGenericPointOfServiceErrorAdyen": function(d) { return "Sorry the payment was not authorized. Please double check payment details and try again"; },
  "errors.eGenericPointOfServiceErrorHyphen": function(d) { return ""; },
  "errors.eGenericPointOfServiceErrorKiosk": function(d) { return "We are sorry but an error has occurred. Please see a team member for assistance.<br /><div class=\"buttons fr\"><a class=\"btn js-closeButton--kiosk\" href=\"" + "#" + "\">Got it, thanks!</a></div>"; },
  "errors.eGenericPointOfServiceErrorKioskDelivery": function(d) { return "We're sorry but an error has occurred. Please call Domino's at " + d.val1 + " for assistance.<button class=\"btn kiosk-restart js-closeButton--kiosk\">Got It, Thanks!</button>"; },
  "errors.eGenericPointOfServiceErrorPosFailedCA": function(d) { return "We're sorry, there seems to be a technical problem. Please contact the store."; },
  "errors.eGenericPointOfServiceErrorWithRefund": function(d) { return "We are sorry but an error has occurred. Please try again momentarily. If errors persist, contact the store at " + d.val1 + ". Though your credit card is charged at this time, we have initiated a refund which should appear in 4-7 business days from now. We apologize for the inconvenience. Please call the store after 7 business days, if you haven’t received the refund."; },
  "errors.eGenericPointOfServiceErrorWithRefundKiosk": function(d) { return "We are sorry but an error has occurred. Please see a team member for assistance. Though your credit card is charged at this time, we have initiated a refund which should appear in 4-7 business days from now. We apologize for the inconvenience. Please call the store after 7 business days, if you haven’t received the refund.<br /><div class=\"buttons fr\"><a class=\"btn js-closeButton--kiosk\" href=\"" + "#" + "\">Got it, thanks!</a></div>"; },
  "errors.eGenericPointOfServiceErrorWithRefundKioskDelivery": function(d) { return "We're sorry but an error has occurred. Please call Domino's at " + d.val1 + " for assistance. Though your credit card is charged at this time, we have initiated a refund which should appear in 4-7 business days from now. We apologize for the inconvenience. Please call the store after 7 business days, if you haven’t received the refund.<button class=\"btn kiosk-restart js-closeButton--kiosk\">Got It, Thanks!</button>"; },
  "errors.eGenericSocial": function(d) { return "Sorry there was a technical error please try again later."; },
  "errors.eGiftCardMissing": function(d) { return "It looks like your forgot to enter a gift card."; },
  "errors.eGiftCardsError": function(d) { return "Please entered a $[label]"; },
  "errors.eGoloDucCheckinError": function(d) { return "Something went wrong.  Please call your store so they can bring your order to you."; },
  "errors.eGrabPayAuthorizationFailed": function(d) { return ""; },
  "errors.eHalfCheesePizza": function(d) { return "You've selected to adjust cheese on a portion of your pizza. Although you can't see it on your virtual pizza now, we'll get it right."; },
  "errors.eHandmadePanSauceChanged": function(d) { return "Hearty Marinara Sauce is not available on our Handmade Pan Pizza. With your change in crust selection, your sauce changed to Robust Tomato."; },
  "errors.eHotspotLiteNotAvailable": function(d) { return "Delivery Outside is currently not available. You can always order a delivery to your address. Please select DELIVERY as service method."; },
  "errors.eIncompleteAddress": function(d) { return "We're sorry, the address you are using is incomplete, Please check and correct the address."; },
  "errors.eIncompletePizza": function(d) { return "We noticed you didn't complete your previous pizza."; },
  "errors.eInterswitchAuthorizationFailed": function(d) { return "Sorry the payment was not authorized. Please double check payment details and try again."; },
  "errors.eInvalidAddress": function(d) { return "Sorry, we couldn't find any results."; },
  "errors.eInvalidCode": function(d) { return "The code you entered is invalid. Please try again."; },
  "errors.eInvalidPostalCodeCreditCardMessageCA": function(d) { return "The postal code entered does not match the postal code associated with this credit or debit card. Please check the postal code and try again. If problems persist, please contact your bank.\n<br /><br />NOTE:  Each time you click on the “Place Order” button your bank may place a hold on funds in your account. Please make sure you submit the correct Expiration Date, Security Code, and Billing Postal Code."; },
  "errors.eInvalidSourceOrgUriForAppBoost": function(d) { return "Sorry, the coupon code entered is only valid for first time app orders. If you are eligible for this coupon, please download and order through the Domino’s app."; },
  "errors.eIpayAuthorizationFailed": function(d) { return "Sorry the payment was not authorized. Please double check payment details and try again."; },
  "errors.eJCB": function(d) { return d.val1 + " is not a valid JCB number."; },
  "errors.eKipleAuthorizationFailed": function(d) { return "Unfortunately your payment was not authorized. Please make sure your payment details are correct and try again. If the issue persists, please contact your bank or card issuer."; },
  "errors.eListProviderFailed": function(d) { return "Due to network latency, we were unable to load the page. Please refresh the page and try again."; },
  "errors.eLobbyClosed": function(d) { return "We're sorry, the lobby is now closed for the night. Please select another store for your carryout order or switch to delivery."; },
  "errors.eLoyaltyDown": function(d) { return "Well, this is embarrassing. We're having a little trouble with Piece of the Pie Rewards, but qualifying orders will still earn points. If you’re trying to redeem your reward with a code, please ensure that you’ve signed into your Pizza Profile before entering your code."; },
  "errors.eLoyaltyEnrollmentFailed": function(d) { return "Well, this is embarrassing. We're having a little trouble and can't enroll you in Piece of the Pie Rewards right now. Please try again later!"; },
  "errors.eLoyaltyFailed": function(d) { return "Well, this is embarrassing. We're having a little trouble applying your Piece of the Pie Rewards points toward a free pizza. Your points have been credited back to your account. Sorry for the inconvenience! Please try again later."; },
  "errors.eLoyaltyInsufficientPoints": function(d) { return "You don't have enough points to redeem."; },
  "errors.eLoyaltyLoginFailed": function(d) { return "Unable to retrieve loyalty information."; },
  "errors.eLoyaltyOptOutFailed": function(d) { return "We're having a little trouble and are unable to opt you out right now. Please try again later!"; },
  "errors.eLoyaltyProfileCreationFailed": function(d) { return "Well, this is embarrassing. Your Pizza Profile was created, but we're having a little trouble enrolling you in Piece of the Pie Rewards right now. Please try again later!"; },
  "errors.eLoyaltyUnsupported": function(d) { return "The store you selected doesn't participate in Piece of the Pie Rewards. Please select a different store in order to redeem points."; },
  "errors.eManualOffline": function(d) { return ""; },
  "errors.eMastercard": function(d) { return d.val1 + " is not a valid MASTERCARD number."; },
  "errors.eMaxAddress": function(d) { return "We're sorry. Only " + d.val1 + " addresses can be saved to a profile. You have reached the limit on the number of addresses that can be saved."; },
  "errors.eMaxAttempts": function(d) { return ""; },
  "errors.eMaxAttemptsCode": function(d) { return "We’ve removed your coupon to redeem a free pizza. Please review your updated order total and proceed with payment."; },
  "errors.eMaxCodesSent": function(d) { return "Maximum number of verification codes sent. Please enter the most recent code in your inbox."; },
  "errors.eMaxOrderLimitExceeded": function(d) { return "Whoa there, big spender. An order this awesome exceeds our store's order limit of " + d.val1 + " Please contact <a href=\"mailto:customercare@dominospizza.ph\">customercare@dominospizza.ph</a> or call 997-3030 to speak with a representative about your order. We apologize for any inconvenience"; },
  "errors.eMaxPizzaToppingsQty": function(d) { return "Sorry, but you've exceeded the topping limit for the " + d.val1 + " portion of your pizza."; },
  "errors.eMaxSauceQty": function(d) { return "Sorry, but you've exceeded the sauce limit for your " + d.val1 + "."; },
  "errors.eMaxToppingsQty": function(d) { return "Sorry, but you've exceeded the topping limit for your " + d.val1 + "."; },
  "errors.eMayBankAuthorizationFailed": function(d) { return "Unfortunately your payment was not authorized. Please make sure your payment details are correct and try again. If the issue persists, please contact your bank or card issuer."; },
  "errors.eMinSauceQty": function(d) { return "Sorry, but you've must choose at least one sauce for your " + d.val1 + "."; },
  "errors.eMinimumProductQtyValidationError": function(d) { return "To enjoy add on deal, a minimum purchase of a Personal pizza is required"; },
  "errors.eMissingPaymentMethod": function(d) { return "Please select a payment method and try again."; },
  "errors.eMissingPhoneNumber": function(d) { return "Please add a phone number to your profile by clicking Edit below."; },
  "errors.eMissingStreetNumberAndName": function(d) { return "Oops, looks like your street number or name is missing. Please enter this information so we can fulfill your order."; },
  "errors.eMissingValidator": function(d) { return "Missing Validator"; },
  "errors.eNoCoordinates": function(d) { return "We're sorry, address format is no longer valid. we have removed this addresses for your convenience. Click <a class=\"js-continueButton\" href=\"" + d.ctx + "/pages/order/" + "#" + "/locations/\">here.</a> to re-add your address to your profile by dropping a pin on the map"; },
  "errors.eNoDeliveryStoreFound": function(d) { return "Your address is out of the delivery boundary. Please contact the call center at this number 920012345 to see if you can place an order at your location. You may edit your delivery address or pick up your order from the closest carryout store!"; },
  "errors.eNoResults": function(d) { return "Sorry, we are unable to locate this address. Please try again."; },
  "errors.eNonVisualPizzaTopping": function(d) { return "Sometimes believing is seeing. This is one of those times. Although you can't see it on your pizza now, we'll get it right."; },
  "errors.eNumber": function(d) { return d.val1 + " is not a number."; },
  "errors.eOnlineOrderingUnavailable": function(d) { return "Sorry, the store you have chosen is not currently available for online ordering.<br /><br />You can contact your store directly at " + d.val1 + ".<br /><div class=\"buttons fr\"><a class=\"btn js-closeButton\" href=\"" + "#" + "\">Got It</a></div>"; },
  "errors.eOnlineOrderingUnavailableKiosk": function(d) { return "Sorry, this kiosk isn't available for placing orders. Please see a team member to place an order.<br /><div class=\"buttons fr\"><a class=\"btn js-closeButton--kiosk\" href=\"" + "#" + "\">Got it, thanks!</a></div>"; },
  "errors.eOnlineOrderingUnavailableKioskDelivery": function(d) { return "Sorry, this kiosk isn't available for placing orders. Please call Domino's at " + d.val1 + " to place an order."; },
  "errors.eOptima": function(d) { return d.val1 + " is not a valid Optima number."; },
  "errors.eOrderCashLimit": function(d) { return "Your store is currently requiring prepayment for orders more than " + d.val1 + ". Please pay with credit/debit or gift card. Thank you"; },
  "errors.eOrderDateTimeInvalid": function(d) { return "Order Date/Time is Invalid. Please choose a future Date/Time."; },
  "errors.eOrderDeliveryUnavailable": function(d) { return "Delivery is not available for your current location ( <a href=\"" + d.ctx + "/pages/order/" + "#" + "/locations/search/\">Change Location</a> )."; },
  "errors.eOrderMinimumCarryoutFee": function(d) { return "Your order does not currently meet the minimum carryout amount of " + d.val1 + " for this store ( <a href=\"" + d.ctx + "/pages/order/" + "#" + "/section/Food/category/AllEntrees/\">Change Order</a> )."; },
  "errors.eOrderMinimumCarryoutFeeWithRefund": function(d) { return "Unfortunately the order failed because it does not currently meet the minimum carryout amount of " + d.val1 + " for this store ( <a href=\"" + d.ctx + "/pages/order/" + "#" + "/section/Food/category/AllEntrees/\">Change Order</a> ).  Though your credit card is charged at this time, we have initiated a refund which should appear in 4-7 business days from now. We apologize for the inconvenience. Please call the store after 7 business days, if you haven’t received the refund."; },
  "errors.eOrderMinimumDeliveryFee": function(d) { return "Your order does not currently meet the minimum delivery amount of " + d.val1 + " for this store ( <a href=\"" + d.ctx + "/pages/order/" + "#" + "/section/Food/category/AllEntrees/\">Change Order</a> )."; },
  "errors.eOrderMinimumDeliveryFeeHyphen": function(d) { return ""; },
  "errors.eOrderMinimumDeliveryFeeWithRefund": function(d) { return "Unfortunately the order failed because it does not currently meet the minimum delivery amount of " + d.val1 + " for this store ( <a href=\"" + d.ctx + "/pages/order/" + "#" + "/section/Food/category/AllEntrees/\">Change Order</a> ).  Though your credit card is charged at this time, we have initiated a refund which should appear in 4-7 business days from now. We apologize for the inconvenience. Please call the store after 7 business days, if you haven’t received the refund."; },
  "errors.ePaymentAuthorizationFailed": function(d) { return "Unfortunately your payment was not authorized. Please make sure your payment details are correct and try again. If the issue persists, please contact your bank or card issuer."; },
  "errors.ePaymentCancelled": function(d) { return "Your transaction has been canceled."; },
  "errors.ePaymentDeclined": function(d) { return "Sorry the payment was not authorized. Please double check payment details and try again."; },
  "errors.ePaymentTechnicalError": function(d) { return "We're sorry, there seems to be a technical problem. Please try again."; },
  "errors.ePaymentUserTimeoutError": function(d) { return "Attention: your payment session timed out. please try again."; },
  "errors.ePaypalBraintreeGenericError": function(d) { return ""; },
  "errors.ePaypalBraintreeNotDone": function(d) { return ""; },
  "errors.ePersonalCouponDuplicate": function(d) { return "Sorry, only one e-coupon can be redeemed for this order. If you like to proceed forward, please remove the existing e-coupon and try again"; },
  "errors.ePersonalCouponInvalid": function(d) { return "Sorry, your e-coupon has been redeemed or expired. This coupon will be removed from your order."; },
  "errors.ePhoneNumber": function(d) { return d.val1 + " is not a valid Phone Number."; },
  "errors.ePlaceToPayAuthorizationFailed": function(d) { return "Sorry the payment was not authorized. Please double check payment details and try again"; },
  "errors.ePlaceToPayWaitingMessage": function(d) { return "It may take up to 90 seconds to process this transaction. Please do not close the browser while the page is loading."; },
  "errors.ePostFinanceAuthorizationFailed": function(d) { return "Sorry the payment was not authorized. Please double check payment details and try again."; },
  "errors.ePostFinanceCancelled": function(d) { return "Your transaction has been cancelled."; },
  "errors.ePostFinanceDeclined": function(d) { return "Unfortunately your payment was not authorized. Please make sure your payment details are correct and try again. If the issue persists, please contact your bank or card issuer."; },
  "errors.ePostFinanceTechnicalError": function(d) { return "Unfortunately, your payment failed due to a technical problem. Please try again."; },
  "errors.ePostalCode": function(d) { return d.val1 + " is not a Postal Code."; },
  "errors.ePostalCodeNotFound": function(d) { return ""; },
  "errors.ePowerCommunication": function(d) { return "We're sorry, there seems to be a technical problem. Please try again."; },
  "errors.ePowerCommunicationWithReference": function(d) { return "We're sorry, there seems to be a technical problem. Please try again. <br><span class='bold'>Credit Card Reference " + "#" + ": " + d.val1 + "</span> <br><span class='bold'>Pay Maya Reference " + "#" + ": " + d.val2 + " </span> "; },
  "errors.eProfileMigrated": function(d) { return "Welcome to the new online ordering site. An email has been sent to <span class=\"buttonType4\">" + d.val1 + "</span> with instructions to activate your profile. Please read the terms and conditions to read more about our migration policy."; },
  "errors.ePromoCodeUser": function(d) { return "The email address you entered is not valid for this offer. To proceed with your order, please enter the valid email address or remove the offer from your cart."; },
  "errors.ePromoInvalid": function(d) { return "Sorry, the qualifying order was not completed, therefore this promotion code is no longer valid."; },
  "errors.ePulseCVVError": function(d) { return "We're sorry, there seems to be an issue with your Credit Card Security Code. Please verify and try again."; },
  "errors.ePulseCreditCardNumber": function(d) { return "We're sorry, there seems to be an issue with your credit card number.  Please verify and place your order again."; },
  "errors.ePulseGiftCard": function(d) { return "We're sorry, there seems to be an issue with your card. Please ensure you have entered the card number without spaces and verify your Card Number/ PIN and reCaptcha phrase are correct."; },
  "errors.ePulseNotApproved": function(d) { return "We're sorry, we were unable to approve your Credit Card. Please verify your payment information and try again."; },
  "errors.ePulsePhoneNumber": function(d) { return "We're sorry, there seems to be an issue with your phone number.  Please verify and place your order again."; },
  "errors.eReachedSauceQty": function(d) { return "You now have 2 sauces on your " + d.val1 + " which is the maximum allowed."; },
  "errors.eRecaptchaRequired": function(d) { return "Please enter the words shown above."; },
  "errors.eRemoveCheeseVisualBuilder": function(d) { return "Don't worry, although you see cheese on your pizza now, we'll get it right. We won't put cheese on your pizza."; },
  "errors.eReorderFail": function(d) { return "We are sorry, there is a problem with your address. Please try to enter it again."; },
  "errors.eRequired": function(d) { return "This field is required."; },
  "errors.eRequiredFields": function(d) { return "Missing Mandatory information"; },
  "errors.eResetPasswordExpired": function(d) { return "Your password change link has been used or expired. Please request a new password using the \"Forgot Your Password\" link."; },
  "errors.eRoutingCouponMessage": function(d) { return "The coupon you selected has been added to your order. Enter your location to get started.<div class=\"buttons fr\"><a class=\"btn js-closeButton\" href=\"" + "#" + "\">Continue</a></div><div class=\"clr\"><!-- --></div>"; },
  "errors.eRoutingMessage": function(d) { return "Please enter your location to connect to your local Domino's and get started.<div class=\"buttons fr\"><a class=\"btn js-closeButton\" href=\"" + "#" + "\">Continue</a></div><div class=\"clr\"><!-- --></div>"; },
  "errors.eSadadAccount": function(d) { return "Error with SADAD Account ID, please check and try again later"; },
  "errors.eSadadAlias": function(d) { return "Please enter a Valid SADAD Account ID and try again later"; },
  "errors.eSadadFailed": function(d) { return "Sorry payment could not be processed, Please try again later"; },
  "errors.eSadadLimit": function(d) { return "Sorry payment could not be processed, Please check your transaction limit"; },
  "errors.eSadadTransaction": function(d) { return "Transaction amount exceeded SADAD Account transaction limit"; },
  "errors.eSecondaryProfileIsNotStub": function(d) { return "Social account already used in other profile. Sorry cannot use provided social account."; },
  "errors.eServerMessage": function(d) { return d.val1; },
  "errors.eServiceMethodChanged": function(d) { return "We're sorry, your current service method selection is not available. We have switched your service method for you."; },
  "errors.eSidesError": function(d) { return "Wow, it looks like you are ordering a lot of sides. For an order this big, we want to make sure we get it right. Please call the store to complete this order."; },
  "errors.eSidesErrorKiosk": function(d) { return "Wow, it looks like you are ordering a lot of sides. For an order this big, we want to make sure we get it right. Please see a team member to complete this order.<br /><div class=\"buttons fr\"><a class=\"btn js-closeButton--kiosk\" href=\"" + "#" + "\">Got it, thanks!</a></div>"; },
  "errors.eSidesErrorKioskDelivery": function(d) { return "Wow, it looks like you are ordering a lot of sides. For an order this big, we want to make sure we get it right. Please call Domino's at " + d.val1 + " to complete this order.<button class=\"btn kiosk-restart js-closeButton--kiosk\">Got It, Thanks!</button>"; },
  "errors.eSpecialCharacters": function(d) { return "Name fields can only contain numbers and letters.  No punctuation or special characters are allowed."; },
  "errors.eStoreClosedForCarside": function(d) { return "We're sorry, but your store's Domino's Carside Delivery™ hours are now over. We've modified your order to store pickup. Please review the updated order total before placing your order as coupon eligibility may have changed."; },
  "errors.eStoreConnectionError": function(d) { return "We are sorry, we cannot price your order. Please try again later."; },
  "errors.eStoreIsClosed": function(d) { return "We apologize, we are working on solving the connectivity issue with the service provider. Please try again later or search for another store."; },
  "errors.eSwitchingFromGlutenFreeCrust": function(d) { return "Gluten Free Crust is only available in small"; },
  "errors.eSwitchingWithUnsupportedBase": function(d) { return d.val1 + " is only available in " + d.val2 + ". Your crust type has been changed to " + d.val3 + "."; },
  "errors.eSwitchingWithUnsupportedBaseExtended": function(d) { return d.val1 + " is only available in " + d.val2 + " pizzas. You can keep your selected crust or choose a different crust for your " + d.val3 + " pizza."; },
  "errors.eTaxIDValidationError": function(d) { return "The Tax CC/RUC/Passaporte is wrong, please enter a valid number."; },
  "errors.eTippingNotAllowedCA": function(d) { return "We are sorry this store does not allow online tipping on carryout orders.   Please remove the tip and resubmit the order."; },
  "errors.eToppingsError": function(d) { return "Sorry but there's something messed up with your toppings."; },
  "errors.eTrackerFeedbackNoText": function(d) { return "Please enter a valid comment for submission."; },
  "errors.eTrackerFeedbackWait": function(d) { return "Please answer after receiving your order."; },
  "errors.eTrackerShoutoutChoice": function(d) { return "Oops, you forgot to select a note of encouragement."; },
  "errors.eUnacceptedCardType": function(d) { return "We're sorry, this store does not accept this card type."; },
  "errors.eUnlinkFinalIdentity": function(d) { return "Sorry this account is not allowed to be removed from the profile as this is a primary login option. Please add password to the profile to unlink your social account."; },
  "errors.eVisa": function(d) { return d.val1 + " is not a valid VISA number."; },
  "errors.eWowPaymentAuthorizationFailed": function(d) { return "We are sorry. We can't use your Wow+ balance for now. Use a different payment method or try again later."; },
  "errors.eoePleaseCheckNumberAgain": function(d) { return "Sorry, an unkown error occured. Please double check the number and try again."; },
  "errors.eoeTextStopToStop": function(d) { return "If the number is correct text \"Stop\" to the following numbers and try signing up again."; },
  "errors.giftcardCannotSaveEasyOrder": function(d) { return "Easy Orders cannot be saved with Gift Cards"; },
  "errors.iCarryoutStoreSubstitute": function(d) { return "It looks like you have selected carryout. We want to make sure you have the correct address:<br/>" + d.val1; },
  "errors.iDefaultPaymentType": function(d) { return "Other/Enter at Checkout"; },
  "errors.iDeliveryLocationLabel": function(d) { return "Your Domino's store:"; },
  "errors.iDoorCreditType": function(d) { return ""; },
  "errors.iDoorDebitType": function(d) { return ""; },
  "errors.iForgotPasswordSuccess": function(d) { return "If an account exists with the e-mail address of <span class=\"buttonType3\">" + d.val1 + "</span> you will receive an e-mail allowing you to change your password."; },
  "errors.iNewDogEar": function(d) { return "New"; },
  "errors.iResetPasswordSuccess": function(d) { return "Your password has been updated! You can sign in using your new password"; },
  "errors.iStoreClosingWarning": function(d) { return "Your store closes at " + d.val1 + ". Don't worry, if you place your delivery order by " + d.val2 + " you will still get it delivered."; },
  "errors.iftttDuplicatePhoneNumber": function(d) { return "Sorry, this mobile number is already in use with another Pizza Profile."; },
  "errors.incompleteProfileInfo": function(d) { return "In order to create a Pizza Profile, we'll need you to provide your name, phone number and email address first."; },
  "errors.incompleteProfileInfoSaveEasyOrder": function(d) { return "In order to create a Pizza Profile, we'll need you to provide your name, phone number, email address and payment type first."; },
  "errors.noDUCFutureOrder_CA": function(d) { return "Future Orders cannot be placed using the Carside Delivery service method. Please select carryout or delivery to continue ordering online."; },
  "errors.noFutureTime_CA": function(d) { return "A time must be entered when selecting an order for a later date."; },
  "errors.noSandwichesServe_CA": function(d) { return "Currently this store does not serve Sandwiches."; },
  "errors.nowFunctionSetting": function(d) { return "The site date/time has been set to: " + d.val1 + ".<br /><br /> Usage: ?now=YYYY-MM-DD [HH:mm:ss] (ex. ?now=2016-12-01 11:01:00). If the time is left off, it will default to 03:01:00 EST.<br />Note: 'now', when compared to the configured expiration times, will use your local timezone."; },
  "errors.otpDeclined": function(d) { return ""; },
  "errors.otpExpired": function(d) { return ""; },
  "errors.otpFailed": function(d) { return ""; },
  "errors.otpIncorrectPassword": function(d) { return ""; },
  "errors.otpInsufficientBalance": function(d) { return ""; },
  "errors.otpLimitExceeded": function(d) { return ""; },
  "errors.otpNotEnrolled": function(d) { return ""; },
  "errors.otpNotFound": function(d) { return ""; },
  "errors.powerCustomer": function(d) { return "We could not locate a Pizza Profile with that e-mail and password combination. Please make sure you are using the e-mail address associated with your Domino's Pizza Profile. <button class=\"btn btn--link btn--link-red-hover buttonType5 js-login\" data-reset-password>Forgot Password?</button>"; },
  "errors.powerCustomerAccountLock": function(d) { return "This account has been locked for exceeding the number of invalid login attempts. If the email address you provided is valid, we'll send a password reset link to the provided email address. If you do not receive the password reset email, please check your spam folder. <button class=\"btn btn--link buttonType5 uppercase js-login\" data-reset-password>Reset Password</button>"; },
  "errors.powerCustomerEmailUsed": function(d) { return "Failed to save your account. This email address is already registered."; },
  "errors.powerCustomerGenericError": function(d) { return "We're sorry. We could not save your account at this time. Please try again later."; },
  "errors.powerCustomerInvalidEmail": function(d) { return "Please enter a valid e-mail address."; },
  "errors.powerCustomerMarketEmailUsed": function(d) { return "We're sorry, the email you have chosen is already in use in another market. Please select a new email address & try again."; },
  "errors.powerCustomerMaxCreditCards": function(d) { return "We're sorry. You've reached the limit on the number of credit cards you can save to your account at a time."; },
  "errors.powerCustomerPhoneUsedTooManyTimes": function(d) { return "Sorry, this account cannot be saved. This phone number is already registered to another Pizza Profile. Please use a different phone number for your account."; },
  "errors.productNotInStore": function(d) { return "We're sorry, the store you have chosen does not carry this product."; },
  "errors.recent_delivery_order_out_of_boundary": function(d) { return "Your store is outside of store boundaries. Please go to store locator to change your delivery location or pick a carryout store."; },
  "errors.resetPasswordSuccess": function(d) { return "Your password has been updated!"; },
  "errors.rncNoResults": function(d) { return "No matching company found. Check RNC number."; },
  "errors.sQtyReducedMax": function(d) { return "You exceeded the maximum quantity allowed for your selection. We have set your selection to the max quantity allowed."; },
  "errors.smsDuplicatePhoneNumber": function(d) { return "Sorry, this mobile number is already in use with another Pizza Profile for Text Ordering."; },
  "errors.tryAgainOrCSR": function(d) { return "Please try again or see a team member to place your order."; },
  "errors.twitterAuthError": function(d) { return "There was an error authorizing your Twitter account."; },
  "errors.unableLocateAddress": function(d) { return "Sorry, we were unable to locate your address."; },
  "errors.varianceMessage": function(d) { return "Please note that this store's regular operating hours have been impacted from " + d.varianceStart + " to " + d.varianceEnd + ". The available future order times below have been impacted due to this.  We apologize for the inconvenience."; }
}
}
);
