define([], function anonymous(
) {
var pluralFuncs = {
  en: function(n, ord) {
    var s = String(n).split('.'), v0 = !s[1], t0 = Number(s[0]) == n,
        n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2);
    if (ord) return (n10 == 1 && n100 != 11) ? 'one'
        : (n10 == 2 && n100 != 12) ? 'two'
        : (n10 == 3 && n100 != 13) ? 'few'
        : 'other';
    return (n == 1 && v0) ? 'one' : 'other';
  }
};
var fmt = {};
var number = function(value, offset) {
  if (isNaN(value)) throw new Error("'" + value + "' isn't a number.");
  return value - (offset || 0);
};
var plural = function(value, offset, lcfunc, data, isOrdinal) {
  if ({}.hasOwnProperty.call(data, value)) return data[value]();
  if (offset) value -= offset;
  var key = lcfunc(value, isOrdinal);
  if (key in data) return data[key]();
  return data.other();
};
var select = function(value, data) {
  if ({}.hasOwnProperty.call(data, value)) return data[value]();
  return data.other()
};

return {
  "payment.1_of_2": function(d) { return "1 of 2"; },
  "payment.1_of_3": function(d) { return "1 of 3"; },
  "payment.2_of_2": function(d) { return "2 of 2"; },
  "payment.2_of_3": function(d) { return "2 of 3"; },
  "payment.3_of_3": function(d) { return "3 of 3"; },
  "payment.3rd_party": function(d) { return "3rd Party"; },
  "payment.CNPJ": function(d) { return ""; },
  "payment.CPF": function(d) { return ""; },
  "payment.accepts_cards": function(d) { return "Accepts Mastercard and Visa"; },
  "payment.account_nickname": function(d) { return "Account Nickname:"; },
  "payment.account_nickname_example": function(d) { return "My Account, Corporate Account, etc."; },
  "payment.account_nickname_paypal3": function(d) { return "Saved Account Nickname:"; },
  "payment.account_nickname_visa_cybersource": function(d) { return "Account Nickname:"; },
  "payment.aciapplepay": function(d) { return "Apple Pay"; },
  "payment.add_16_parmesan_bread_bites": function(d) { return "Add 16 Parmesan Bread Bites for just $1.99."; },
  "payment.add_a_20oz_drink_to_your_order_for_just": function(d) { return "Add a 20oz drink to your order for just"; },
  "payment.add_a_tip_to_your_order": function(d) { return "Add a tip to your order."; },
  "payment.add_bread_bites_to_my_order": function(d) { return "Add bread bites to my order"; },
  "payment.add_drinks_to_my_order": function(d) { return "Add drinks to my order"; },
  "payment.after_you_place_your_order_carryout": function(d) { return "After you place your order, it should be ready between <span class=\"order-complete-time__text\">" + d.waitTime + "</span>"; },
  "payment.after_you_place_your_order_delivery": function(d) { return "After you place your order, it should be delivered between <span class=\"order-complete-time__text\">" + d.waitTime + "</span>"; },
  "payment.alamar_wallet": function(d) { return "Wallet"; },
  "payment.alamar_wallet_balance": function(d) { return "Current Balance: " + d.availableBalance; },
  "payment.alamar_wallet_promotional": function(d) { return "Wallet Promotional"; },
  "payment.amex": function(d) { return "AMEX"; },
  "payment.amount_to_apply": function(d) { return "Amount to Apply"; },
  "payment.apple_pay": function(d) { return "Apple Pay"; },
  "payment.apple_pay_giftcard_warning": function(d) { return "We're sorry, Apple Pay cannot be used with Gift Cards."; },
  "payment.apply_card": function(d) { return "Apply Card"; },
  "payment.approval_number": function(d) { return "Approval " + "#"; },
  "payment.ath": function(d) { return "ATH"; },
  "payment.back": function(d) { return "back"; },
  "payment.balance_due": function(d) { return "Balance Due:"; },
  "payment.billing_address": function(d) { return "Billing address"; },
  "payment.billing_zip_code": function(d) { return "Billing Postal Code"; },
  "payment.billing_zip_code_error": function(d) { return "Billing Postal Code Error"; },
  "payment.billing_zip_code_help": function(d) { return "Help with Credit Card Billing Postal Code"; },
  "payment.bring_change_for": function(d) { return "Bring Change For:"; },
  "payment.browse_coupons": function(d) { return "Browse coupons"; },
  "payment.by_creating_a_profile_you": function(d) { return "By enrolling, you agree to comply with the <a href=\"" + "#" + "!/loyalty/terms\" class=\"js-loyalty-terms-toggler terms-link terms-link--loyalty\">Terms & Conditions</a> of Piece of the Pie Rewards<sup>&reg;</sup>, as well as our general <a class=\"js-termsOfUseOverlay\" href=\"" + d.ctx + "/" + "#" + "!/content/terms/\">Terms of Use</a> and that you are at least 14 years old."; },
  "payment.by_placing_your_order_you": function(d) { return "By placing your order you agree to our <a class=\"js-isTemplatePopup\" data-template-popup=\"contentPageTerms\" href=\"" + "#" + "\">Terms of Use</a> and that you are at least 14 years old."; },
  "payment.cancel": function(d) { return "Cancel"; },
  "payment.card_details": function(d) { return "Card Details"; },
  "payment.card_number": function(d) { return "Card Number"; },
  "payment.carside_add_tip_encouraged": function(d) { return "Tipping now helps ensure a zero-contact Domino's Curbside Pickup experience for you and Domino's team members. Consider now the possibility of tipping."; },
  "payment.cash": function(d) { return "Cash"; },
  "payment.cc": function(d) { return ""; },
  "payment.ccNumber": function(d) { return ""; },
  "payment.cep": function(d) { return "Meu CEP"; },
  "payment.change_to_pay_at_store": function(d) { return "Change to Pay at Store upon arrival"; },
  "payment.change_your_order": function(d) { return "Change Your Order"; },
  "payment.chars": function(d) { return ""; },
  "payment.check_card": function(d) { return "Check Card"; },
  "payment.check_your_order_details": function(d) { return ""; },
  "payment.choose_payment_method": function(d) { return "Choose Payment Method"; },
  "payment.click_here": function(d) { return "Click here"; },
  "payment.code_resent": function(d) { return "A new code has been sent"; },
  "payment.company": function(d) { return "Company"; },
  "payment.company_name": function(d) { return ""; },
  "payment.contactless": function(d) { return "Zero Contact"; },
  "payment.contactless_additional_label_delivery_instructions": function(d) { return "To ensure our team members safety, delivery drivers will deliver orders to the lobby of buildings with communal entry ways."; },
  "payment.contactless_are_there_other_measures": function(d) { return ""; },
  "payment.contactless_are_there_other_measures_description": function(d) { return ""; },
  "payment.contactless_carryout": function(d) { return "Zero Contact Carryout"; },
  "payment.contactless_carryout_cash_note": function(d) { return "Prepayment is required with zero contact carryout. For more information please contact the store."; },
  "payment.contactless_carryout_details": function(d) { return ""; },
  "payment.contactless_carryout_info": function(d) { return "No direct contact with the Store Members."; },
  "payment.contactless_carryout_msg_1": function(d) { return "No direct contact between you and Domino's Team Members."; },
  "payment.contactless_carryout_msg_2": function(d) { return "When you arrive at the store you will receive specific pickup instructions."; },
  "payment.contactless_carryout_msg_3": function(d) { return ""; },
  "payment.contactless_carryout_msg_4": function(d) { return ""; },
  "payment.contactless_carryout_msg_5": function(d) { return ""; },
  "payment.contactless_carryout_note": function(d) { return "Your store is currently following <strong>Zero Contact Carryout</strong> procedures for all order pickups."; },
  "payment.contactless_carryout_note_lobby_closed": function(d) { return "Your store is currently following zero contact carryout procedures which <strong>includes limited or no lobby access</strong>.<br /><br />Look for specific pickup instructions when you arrive at the store."; },
  "payment.contactless_carryout_note_lobby_open": function(d) { return "Your store is currently following zero contact carryout procedures for all order pickups.<br /><br /> Look for specific pickup instructions when you arrive at the store."; },
  "payment.contactless_carryout_preference": function(d) { return "Carryout Preference"; },
  "payment.contactless_carryout_prepayment_required": function(d) { return "Prepayment required."; },
  "payment.contactless_cash_add_tip": function(d) { return "To ensure a true zero contact experience, <bold class=\"tip-green\">please consider pre-tipping now.</bold>"; },
  "payment.contactless_cash_add_tip_encouraged": function(d) { return "Tipping online allows you to tip your driver with a zero contact delivery experience for you and your delivery driver. <bold class=\"tip-green\" id=\"tip-instruction\">Please select a tip amount or choose \"No Tip\".</bold>"; },
  "payment.contactless_cash_add_tip_encouraged_carryout": function(d) { return "Tipping online allows you to tip your store's team members for a zero contact carryout experience for you and the team members.  <bold class=\"tip-green\">Please  confirm the tip selection below.</bold>"; },
  "payment.contactless_cash_note": function(d) { return "Cash payment not available for zero contact delivery."; },
  "payment.contactless_debit_at_door_note ": function(d) { return ""; },
  "payment.contactless_delivery": function(d) { return "Zero Contact Delivery"; },
  "payment.contactless_delivery_available": function(d) { return "Zero Contact Delivery Available"; },
  "payment.contactless_delivery_conditions": function(d) { return "Zero Contact Delivery Conditions"; },
  "payment.contactless_delivery_cost": function(d) { return ""; },
  "payment.contactless_delivery_cost_description": function(d) { return ""; },
  "payment.contactless_delivery_details": function(d) { return ""; },
  "payment.contactless_delivery_faq": function(d) { return ""; },
  "payment.contactless_delivery_faq_description": function(d) { return ""; },
  "payment.contactless_delivery_info": function(d) { return "No direct contact with your Delivery Expert."; },
  "payment.contactless_delivery_is_required": function(d) { return ""; },
  "payment.contactless_delivery_is_required_description": function(d) { return ""; },
  "payment.contactless_delivery_msg_1": function(d) { return ""; },
  "payment.contactless_delivery_msg_2": function(d) { return ""; },
  "payment.contactless_delivery_msg_3": function(d) { return ""; },
  "payment.contactless_delivery_msg_4": function(d) { return ""; },
  "payment.contactless_delivery_msg_5": function(d) { return ""; },
  "payment.contactless_delivery_preference": function(d) { return "Select Your Delivery Preference"; },
  "payment.contactless_delivery_required": function(d) { return "Zero Contact delivery required"; },
  "payment.contactless_delivery_required_by_store": function(d) { return "Your store is temporarily requiring <strong>Zero Contact Delivery</strong> for all delivery orders."; },
  "payment.contactless_delivery_selected": function(d) { return "Zero Contact delivery selected"; },
  "payment.contactless_delivery_will_conact_you": function(d) { return ""; },
  "payment.contactless_delivery_will_contact_you": function(d) { return ""; },
  "payment.contactless_details": function(d) { return "details"; },
  "payment.contactless_door_credit_note": function(d) { return "Door Credit payment not available for Zero Contact delivery."; },
  "payment.contactless_door_debit_note": function(d) { return "Door Debit not available for Zero Contact delivery."; },
  "payment.contactless_faq_1": function(d) { return ""; },
  "payment.contactless_faq_2": function(d) { return ""; },
  "payment.contactless_faq_3": function(d) { return ""; },
  "payment.contactless_faq_measures_1": function(d) { return ""; },
  "payment.contactless_faq_measures_2": function(d) { return ""; },
  "payment.contactless_faq_measures_3": function(d) { return ""; },
  "payment.contactless_faq_measures_4": function(d) { return ""; },
  "payment.contactless_faq_measures_5": function(d) { return ""; },
  "payment.contactless_faqs_1": function(d) { return ""; },
  "payment.contactless_faqs_1_description": function(d) { return ""; },
  "payment.contactless_faqs_2": function(d) { return ""; },
  "payment.contactless_faqs_2_description": function(d) { return ""; },
  "payment.contactless_faqs_3": function(d) { return ""; },
  "payment.contactless_faqs_3_description": function(d) { return ""; },
  "payment.contactless_faqs_4": function(d) { return ""; },
  "payment.contactless_faqs_4_description": function(d) { return ""; },
  "payment.contactless_faqs_5": function(d) { return ""; },
  "payment.contactless_faqs_5_description": function(d) { return ""; },
  "payment.contactless_for_our_communities": function(d) { return ""; },
  "payment.contactless_for_our_communities_description": function(d) { return ""; },
  "payment.contactless_how_it_works": function(d) { return "Here is how it works:"; },
  "payment.contactless_instructions_for_driver": function(d) { return "Instructions for Zero Contact delivery driver"; },
  "payment.contactless_is_cash_enabled": function(d) { return ""; },
  "payment.contactless_is_cash_enabled_description": function(d) { return ""; },
  "payment.contactless_learn_more": function(d) { return ""; },
  "payment.contactless_modal_available_list_item_1": function(d) { return "Select Zero Contact Delivery as your delivery preference."; },
  "payment.contactless_modal_available_title": function(d) { return "Zero Contact Delivery is available!"; },
  "payment.contactless_modal_face_covering_required": function(d) { return "Customers must cover their nose and mouth with a mask or other cloth material before entering the store. Please call the store if you have questions or need assistance."; },
  "payment.contactless_modal_list_item_0": function(d) { return "A Zero Contact Delivery prevents direct personal contact between you and your Delivery Expert."; },
  "payment.contactless_modal_list_item_2": function(d) { return "Please use the Delivery Instructions box on the next page to indicate where you'd like your order safely placed."; },
  "payment.contactless_modal_list_item_3": function(d) { return "More information available on next page."; },
  "payment.contactless_modal_required_list_item_1": function(d) { return "Your store is only offering Zero Contact Delivery."; },
  "payment.contactless_modal_required_title": function(d) { return "This will be a Zero Contact Delivery"; },
  "payment.contactless_must_cashless": function(d) { return "Cashless required"; },
  "payment.contactless_must_prepay": function(d) { return "Prepaid required"; },
  "payment.contactless_no_tip": function(d) { return "No Tip"; },
  "payment.contactless_pay_now_with_card_pick_up_contactless_msg": function(d) { return "Pay now with card to use our Pick-up Window for a seamless contactless experience!"; },
  "payment.contactless_pickup_msg": function(d) { return "For a seamless contactless experience, use our Pick-Up Window and consider paying now with a card."; },
  "payment.contactless_pickup_msg_2": function(d) { return "You'll receive specific pickup instructions when you arrive at the store if you're picking up in the lobby."; },
  "payment.contactless_required_placeholder": function(d) { return "(Required)"; },
  "payment.contactless_service": function(d) { return "<p>Please use the Delivery Instructions for Zero Contact Service.</p><p>Visit our <a href=\"https://pizza.dominos.ca/lp/zero-contact-service\" target=\"_blank\">Zero Contact Service</a> page for more information.</p>"; },
  "payment.contactless_step_1": function(d) { return "1. The delivery instructions box is where special directions can be written for the location that you would like your order delivered. Pre-payment and pre-tipping are options that can make the delivery more efficient."; },
  "payment.contactless_step_1_available": function(d) { return "1. Zero Contact Delivery is available as a delivery option. The delivery instructions box is for any special directions, including the location where you would like the delivery placed. Pre-payment and pre-tipping make your contactless delivery more efficient."; },
  "payment.contactless_step_1_required": function(d) { return "1. Your store only offers Zero Contact Delivery. The delivery instructions box is for any special directions, including the location where you would like the delivery placed. Pre-payment and pre-tipping are options that can make your zero contact delivery more efficient."; },
  "payment.contactless_step_1_requiredCashless": function(d) { return "1. Currently your store is requiring Zero Contact Delivery and prepayment for all orders. The delivery instructions box is for any special directions, including the location where you would like the delivery placed. Optional pre-tipping is also available."; },
  "payment.contactless_step_2": function(d) { return "2. The delivery expert will notify you when the order has arrived and may call you (keep your phone handy)."; },
  "payment.contactless_step_3": function(d) { return "3. They will place your order on a clean and safe surface in the location that you specified in the delivery instructions."; },
  "payment.contactless_step_4": function(d) { return "4. Please help us keep safe and wait until your delivery expert is 6 feet away before you collect your order."; },
  "payment.contactless_step_5": function(d) { return ""; },
  "payment.contactless_store_credit_note": function(d) { return "Credit in store payment not available for Zero Contact carryout."; },
  "payment.contactless_store_debit_note": function(d) { return "Debit in store payment not available for Zero Contact carryout."; },
  "payment.contactless_traditional": function(d) { return "Traditional Delivery"; },
  "payment.contactless_traditional_info": function(d) { return "Your Delivery Expert will hand you your order."; },
  "payment.contactless_what_is_explaination": function(d) { return "A zero contact delivery means having your order delivered with no direct personal contact between the customer and the delivery expert."; },
  "payment.contactless_what_is_it": function(d) { return "What is Zero Contact Delivery?"; },
  "payment.contactless_what_is_it_explainaition": function(d) { return ""; },
  "payment.contactless_yes_add_a_tip_now": function(d) { return "Yes, add a tip now."; },
  "payment.core_10814_cinnamon_bread_twists": function(d) { return "Cinnamon Bread Twists"; },
  "payment.core_10814_enjoy_an_order_of_bread_twists": function(d) { return "Enjoy an order of Bread Twists for only $1"; },
  "payment.core_10814_garlic_bread_twists": function(d) { return ""; },
  "payment.core_10814_parmesan_bread_twists": function(d) { return ""; },
  "payment.core_10814_special_one_time_offer": function(d) { return "special one-time offer"; },
  "payment.core_10814_you_qualify_for_special_one_time_bread_twist": function(d) { return "You qualify for a special one-time offer to try one of our Bread Twists."; },
  "payment.core_10814_your_new_total_is": function(d) { return "Your new total is"; },
  "payment.core_10814_your_order_of_blank_was_added_to_your_cart": function(d) { return "Your order of " + d.twistHoldoutTypeAdded + " was added to your cart!"; },
  "payment.create_a_pizza_profile_and": function(d) { return "Create a Pizza Profile and we'll save your order info and settings for faster ordering next time"; },
  "payment.create_a_pizza_profile_and_loyalty_version": function(d) { return "Create a Pizza Profile for faster ordering and to enroll in Piece of the Pie Rewards<sup>&reg;</sup>"; },
  "payment.create_one_below_during_checkout": function(d) { return "Create one below during checkout"; },
  "payment.credit_at_the_door": function(d) { return ""; },
  "payment.credit_card": function(d) { return "Credit Card"; },
  "payment.credit_card_at_the_door": function(d) { return "Credit Card/Gift Card at the Door"; },
  "payment.credit_card_at_the_door_prepaid": function(d) { return "Credit Card/Gift Card at the Door (Online Payment Only)"; },
  "payment.credit_card_nickname": function(d) { return "Credit Card Nickname"; },
  "payment.credit_card_non_acceptance": function(d) { return "This store does not accept online payments."; },
  "payment.credit_card_not_used_at_this_time": function(d) { return "We are sorry credit cards cannot be used online at this time."; },
  "payment.credit_card_number": function(d) { return "Card Number"; },
  "payment.credit_card_security_code": function(d) { return "Credit Card Security Code"; },
  "payment.credit_card_security_code_help": function(d) { return "Help with Credit Card Security Code"; },
  "payment.credit_card_type": function(d) { return "Credit Card Type"; },
  "payment.credit_cardholder_name": function(d) { return "Cardholder Name"; },
  "payment.credit_debit": function(d) { return "Pay with credit or debit card"; },
  "payment.creditcard": function(d) { return "Credit Card"; },
  "payment.creditcardtype_ending_in_lastfour": function(d) { return d.creditCardType + " ending in ***" + d.lastFour; },
  "payment.curbside_pickup_delivery_instructions": function(d) { return ""; },
  "payment.custom_tip": function(d) { return "Custom Tip"; },
  "payment.customer_order_details": function(d) { return ""; },
  "payment.cvv_prompt_message": function(d) { return "Please enter the " + d.cvvDigitLength + "-digit security code found on the " + d.frontOrBack + " of the card. For your protection, we sometimes ask that you verify your identity."; },
  "payment.cvv_verification": function(d) { return "CVV Verification"; },
  "payment.cybersource": function(d) { return "Cyber Source"; },
  "payment.debit_at_the_door": function(d) { return ""; },
  "payment.debit_card_at_the_door": function(d) { return "Debit Card at the Door"; },
  "payment.debit_card_at_the_door_prepaid": function(d) { return "Debit Card at the Door (Online Payment Only)"; },
  "payment.delivery_instructions_for_driver": function(d) { return "Delivery Instructions For Driver"; },
  "payment.diners": function(d) { return "Diner's"; },
  "payment.directory": function(d) { return d.subType; },
  "payment.discover": function(d) { return "Discover"; },
  "payment.dominos_debit": function(d) { return "Domino's Debit"; },
  "payment.doorcredit": function(d) { return "Credit Card at the Door"; },
  "payment.doordebit": function(d) { return "Debit Card at the Door"; },
  "payment.duc_contactless_would_you_like_your_order_in_vehicle": function(d) { return "Would you like to provide your vehicle information and be able to alert the store upon arrival?"; },
  "payment.duc_pay_at_store_for_duc": function(d) { return "By selecting Pay at Store, your service method will change to Carryout. Would you like to Continue?"; },
  "payment.duc_pay_at_store_for_duc_with_coupon": function(d) { return "By selecting Pay at Store, your service method will change to Store Pickup and the Domino’s Carside Delivery™ coupon will be removed from your order. Would you like to continue with Pay at Store?"; },
  "payment.duc_pay_with_card_or_paypal": function(d) { return "Pay now with card to use our Domino's Carside Delivery™ for a seamless experience!"; },
  "payment.duc_sms_phone_placeholder": function(d) { return "(Mobile phone " + "#" + " of person picking up)"; },
  "payment.duc_subtitle": function(d) { return "We will only use this information to make sure your store can find you for a seamless experience!"; },
  "payment.duc_vehicle_information": function(d) { return "Domino's Carside Delivery™ vehicle information"; },
  "payment.duc_would_you_like_to_get_order_in_vehicle": function(d) { return "Don't want to get out of your car? Let us bring your order to you."; },
  "payment.duc_your_prepaid_order_allows_duc": function(d) { return "Your prepaid Carryout order allows you to have a Domino's Carside Delivery™ experience upon arrival at the store. Provide your vehicle information and the order will be brought to your vehicle once you indicate you have arrived."; },
  "payment.easy_order_name": function(d) { return "Easy Order Name:"; },
  "payment.easy_order_saved_as": function(d) { return "Your Easy Order has been saved as:"; },
  "payment.ecom40590_nice_you_will_earnCA": function(d) { return "Nice! You will earn"; },
  "payment.ecom40590_only_x_away_from_earning_ten": function(d) { return d.amountBelowLoyalty; },
  "payment.ecom40590_you_will_earnCA": function(d) { return "Nice! You will earn <span class=\"uppercase\"> 10 reward points </span> for your order of $10 or more."; },
  "payment.ecom40590_you_will_notearnCA": function(d) { return "You're not earning Rewards Points for this order. Add"; },
  "payment.ecom40590_you_will_notearnpointsCA": function(d) { return "You're not earning Rewards Points for this order."; },
  "payment.ecom40590_you_will_notearnsCA": function(d) { return "to earn 10 Rewards Points."; },
  "payment.ecom47364_cpd_pay_with_card_or_paypal": function(d) { return "Pay now with card to use our Curbside Pickup for a seamless experience!"; },
  "payment.ecom47364_cpd_vehicle_information": function(d) { return "Curbside Pickup vehicle information"; },
  "payment.ecom47364_cpd_your_prepaid_order_allows_duc": function(d) { return "Your prepaid Carryout order allows you to have a Curbside Pickup experience upon arrival at the store. Provide your vehicle information, opt into SMS and the order will be brought to your vehicle once you indicate you have arrived."; },
  "payment.encryptedCardNumber": function(d) { return "Card Number"; },
  "payment.encryptedExpiryMonth": function(d) { return "Month"; },
  "payment.encryptedExpiryYear": function(d) { return "Year"; },
  "payment.encryptedSecurityCode": function(d) { return "CVV"; },
  "payment.enrollEmail": function(d) { return "Receive email offers"; },
  "payment.enroute": function(d) { return "Enroute"; },
  "payment.enter_code": function(d) { return "Enter verification code here:"; },
  "payment.enter_rnc_number": function(d) { return "Enter RNC Number:"; },
  "payment.enter_the_text_shown_below": function(d) { return "Enter the text shown below, then click on the \"Apply Card\" button."; },
  "payment.expired_cards_cannot_be_editted": function(d) { return "Expired Cards cannot be edited for use at this time."; },
  "payment.expired_expirationmonth_expirationyear": function(d) { return "expired (" + d.expirationMonth + "/" + d.expirationYear + ")"; },
  "payment.expires_on_expirationmonth_expirationyear": function(d) { return "expires on (" + d.expirationMonth + "/" + d.expirationYear + ")"; },
  "payment.fac": function(d) { return "Credit Card"; },
  "payment.factura": function(d) { return ""; },
  "payment.feeling_generous": function(d) { return "Feeling Generous?"; },
  "payment.final_consumer": function(d) { return "Final Consumer"; },
  "payment.for_each_gift_card_or": function(d) { return "For each gift card, please enter your card number and PIN (with no spaces) and click Apply Card. If the gift card is accepted, you can then change the amount to apply."; },
  "payment.for_each_gift_card_or_page": function(d) { return "For each gift card, please enter your card number and PIN (with no spaces) and click Check Card."; },
  "payment.front": function(d) { return "front"; },
  "payment.gift_card_balance": function(d) { return "Gift Card Balance:"; },
  "payment.gift_card_help": function(d) { return "Gift Card Help"; },
  "payment.gift_card_help_alt": function(d) { return "The image is of the back of a physical gift card. The gift card has a scratch off area to reveal the last 7 digits of the gift card code and there are 19 total digits for the gift card number. The 4 digit pin is located to the right of the gift card number."; },
  "payment.gift_cards_promotional_card_cannot_at_this_time": function(d) { return "Gift Cards cannot be used at this time."; },
  "payment.gift_cards_promotional_cards": function(d) { return "Gift Cards"; },
  "payment.gift_cards_promotional_cards_cannot": function(d) { return "Gift Cards cannot be used for future orders."; },
  "payment.gift_cards_promotional_cards_cannot_easy_order": function(d) { return "Gift Cards cannot be used for Easy Orders."; },
  "payment.gift_cards_promotional_cards_cannot_paypal_option": function(d) { return "We're sorry, Gift Cards cannot be used with PayPal."; },
  "payment.giftcard": function(d) { return "Gift Card"; },
  "payment.golo_duc": function(d) { return "Drive Up Carryout"; },
  "payment.government": function(d) { return "Government"; },
  "payment.grabpay": function(d) { return "Grabpay"; },
  "payment.great_you_will_finish_after_place_order": function(d) { return "Great! You can finish signing up after you place your order."; },
  "payment.heres_where_to_find_your": function(d) { return "Here's where to find your Card Number and PIN"; },
  "payment.hide_order_summary": function(d) { return "Hide order summary"; },
  "payment.holderName": function(d) { return "Card Holder Name"; },
  "payment.ill_sign_up_later": function(d) { return "I'll sign up later"; },
  "payment.individual": function(d) { return "Individual"; },
  "payment.info": function(d) { return "info"; },
  "payment.interswitch": function(d) { return "Interswitch"; },
  "payment.invalid_billing_zip": function(d) { return "Oops, looks like the Billing Postal Code on this card is invalid. Please update your Postal Code on this card."; },
  "payment.invoice": function(d) { return ""; },
  "payment.ipay": function(d) { return "Credit/debit card"; },
  "payment.izipay": function(d) { return "IZIPay"; },
  "payment.jcb": function(d) { return "JCB"; },
  "payment.kiple": function(d) { return "Kiple"; },
  "payment.klarna": function(d) { return "Klarna - Pay Later"; },
  "payment.klarna_account": function(d) { return "Klarna - Slice It"; },
  "payment.klarna_paynow": function(d) { return "Klarna - Pay Now"; },
  "payment.legal_credit_card_text": function(d) { return ""; },
  "payment.legal_tip_text": function(d) { return "Any Delivery Charge is not a tip paid to your driver. Please reward your driver for awesomeness. Our drivers carry less than $20."; },
  "payment.link_fac_account": function(d) { return ""; },
  "payment.link_paypal3_account": function(d) { return "Link your PayPal accout with Domino's"; },
  "payment.link_visacybersource_account": function(d) { return "Save my credit card"; },
  "payment.loyalty_earned_points": function(d) { return "Nice! You will earn <span class=\"loyalty__payment-card__reward--hightlight\">" + d.potentialEarnedPoints + "</span> reward points."; },
  "payment.loyalty_earned_with_bonus": function(d) { return "<div class=\"loyalty_payment-card__reward--row\">Nice! You will earn:</div><div class=\"loyalty_payment-card__reward--row\"><span class=\"loyalty__payment-card__reward--hightlight\">" + d.potentialEarnedPoints + "</span> reward points</div><div class=\"loyalty_payment-card__reward--row\"><span class=\"loyalty__payment-card__reward--hightlight\">" + d.potentialBonusPoints + "</span> bonus points for your first order</div>"; },
  "payment.loyalty_enrolled": function(d) { return "Enrolled!"; },
  "payment.loyalty_enrollment_after_order": function(d) { return "Your Enrollment will be completed once you place your order"; },
  "payment.loyalty_enrollment_legal": function(d) { return "By enrolling, you agree to comply with the <button class=\"js-termsAndConditions btn--link\" type=\"button\">Terms & Conditions</button> of Piece of the Pie Rewards&reg;, as well as our general <button class=\"js-termsOfUseOverlay btn--link\" type=\"button\">Terms of Use</button> and that you are at least 14 years old."; },
  "payment.loyalty_fill_information": function(d) { return "Fill in the information below to create a Pizza Profile and enroll in Piece of the Pie Rewards."; },
  "payment.loyalty_mastercard_only": function(d) { return "Please enter a valid Mastercard"; },
  "payment.loyalty_points_activation": function(d) { return "Your points will be available within approximately 48-72 hours of purchase."; },
  "payment.mada": function(d) { return "Mada"; },
  "payment.make_this_card_my_primary_card": function(d) { return "Make this card my primary card"; },
  "payment.make_this_my_primary_account": function(d) { return "Make this my primary account"; },
  "payment.make_this_my_primary_account_izipay": function(d) { return "This is my primary card"; },
  "payment.make_this_my_primary_account_paypal3": function(d) { return "This is my primary card"; },
  "payment.make_this_my_primary_account_transbank": function(d) { return "This is my primary card"; },
  "payment.make_this_my_primary_account_visa_cybersource": function(d) { return "This is my primary card"; },
  "payment.mastercard": function(d) { return "Mastercard"; },
  "payment.mastercard_debit": function(d) { return "Mastercard Debit"; },
  "payment.maybank": function(d) { return "Credit/Debit Online"; },
  "payment.maybank_2": function(d) { return "Credit/Debit Online"; },
  "payment.mbway": function(d) { return "Pay with MBWAY"; },
  "payment.mbway_details": function(d) { return "Mbway Details"; },
  "payment.mbway_push_notification": function(d) { return "A Push Notification will be sent to your device. Please accept the transaction with your PIN MB WAY. This transaction will expire in 4 minutes."; },
  "payment.mc": function(d) { return "Mastercard"; },
  "payment.moyasar": function(d) { return "Credit Card"; },
  "payment.mpesa": function(d) { return ""; },
  "payment.multi_transaction_failed": function(d) { return "We were unable to process your payment. Please choose another payment method or try later."; },
  "payment.my_dominos_favorite": function(d) { return "My Domino's Favorite"; },
  "payment.my_visa_corporate_card_etc": function(d) { return "My Visa, Corporate Card, etc."; },
  "payment.name_your_easy_order": function(d) { return "Name your Easy Order"; },
  "payment.need_help": function(d) { return "Need Help?"; },
  "payment.nexi": function(d) { return "Credit Card"; },
  "payment.nice_order_thats_why_we": function(d) { return "Nice Order! That's why we picked you for a special offer."; },
  "payment.nice_you_will_earn": function(d) { return "Nice! You will earn:"; },
  "payment.no_code": function(d) { return "Didn't receive the code?"; },
  "payment.no_comma_thanks": function(d) { return "No, thanks"; },
  "payment.no_thanks": function(d) { return "No thanks"; },
  "payment.no_thanks_place_order": function(d) { return "No thanks, Place Order"; },
  "payment.none": function(d) { return "None"; },
  "payment.not_recent_address_attention_line1_CA": function(d) { return "We noticed you have not ordered from this store recently."; },
  "payment.not_recent_address_attention_line2_CA": function(d) { return "If this is not the location you wish to order from, please go back and choose a different store."; },
  "payment.note_all_credit_payments_will": function(d) { return "Note: All credit card payments will be processed at your door.  Card MUST be presented at the door to complete the transaction."; },
  "payment.note_all_debit_payments_will": function(d) { return "Note: All debit payments will be processed at your door.  Card MUST be presented at the door to complete the transaction.  An extra charge may apply for Interac transactions."; },
  "payment.note_at_the_store_you": function(d) { return ""; },
  "payment.note_carryout_payment_at_store": function(d) { return "Note: At the store you can pay with cash or credit card."; },
  "payment.note_carryout_payment_at_store_gift_card": function(d) { return "Note: At the store you can pay with cash, credit card, debit card or gift card."; },
  "payment.note_drivers_carry_less_than": function(d) { return "Note: Drivers carry less than " + d.cashCurrCode + " in change and cheques are NOT accepted for online orders. Feeling generous? You can tip at the door."; },
  "payment.note_duc_payment_at_store_no_cash": function(d) { return "Note: At the store you can pay with credit card or debit card only."; },
  "payment.note_gate_code_ring_the": function(d) { return "(<b>Note:</b> Gate code, ring the door bell, etc.)"; },
  "payment.note_gate_code_ring_the_contactless": function(d) { return "(<b>Note:</b> Gate code, ring the door bell, zero contact request, etc.)"; },
  "payment.note_please_have_your_legal": function(d) { return "Feeling generous? You can tip at the door when you sign your credit card receipt."; },
  "payment.note_room_gate_lobby_buliding": function(d) { return "(<b>E.g.</b> Room " + "#" + ", lobby name, building " + "#" + ", apt. " + "#" + ", suite " + "#" + ")"; },
  "payment.now_give_it_a_name": function(d) { return "Now give it a name"; },
  "payment.official_address": function(d) { return ""; },
  "payment.official_info": function(d) { return ""; },
  "payment.oh_yeah_eo_saved": function(d) { return "Oh yeahhh, your Easy Order has been saved as:"; },
  "payment.one_click_payment": function(d) { return "One click payment"; },
  "payment.oops_an_error_occured": function(d) { return "Oops!! An error occured:"; },
  "payment.openpay": function(d) { return "Online payment with credit or debit card"; },
  "payment.optima": function(d) { return "Optima"; },
  "payment.or_create_one_below": function(d) { return "or create profile below"; },
  "payment.or_tip_at_door": function(d) { return "(or you can tip at the door)"; },
  "payment.order_delayed": function(d) { return "Order delivery time is expected to be between " + d.range + " minutes due to " + d.reason + "."; },
  "payment.order_review": function(d) { return "Order Review"; },
  "payment.order_timing_later": function(d) { return "Order Timing - Later"; },
  "payment.order_timing_now": function(d) { return "Order Timing - Now"; },
  "payment.order_total": function(d) { return "Order Total:"; },
  "payment.orders_that_require_a_special": function(d) { return ""; },
  "payment.otro/introducir_al_checkout": function(d) { return ""; },
  "payment.paid": function(d) { return "Paid"; },
  "payment.passport": function(d) { return ""; },
  "payment.pay_at_counter_with_cash": function(d) { return "Pay at Counter"; },
  "payment.pay_at_store": function(d) { return "Pay at Store"; },
  "payment.pay_at_store_cash_disabled_CA": function(d) { return "Pay by Debit or Credit at Pick Up Time"; },
  "payment.pay_at_store_disabled": function(d) { return "Pay at Store <span class=\"contactless-service-message\">(Cash currently NOT accepted)</span>"; },
  "payment.pay_at_store_prepaid": function(d) { return "Pay at Store (Online Payment Only)"; },
  "payment.pay_at_store_prepaid_required_CA": function(d) { return "Pay by Debit or Credit at Pick Up Time (Online payment only)"; },
  "payment.pay_at_store_with_credit": function(d) { return "Pay with credit in store"; },
  "payment.pay_at_store_with_debit": function(d) { return "Pay with debit in store"; },
  "payment.pay_eps": function(d) { return "Pay now with other ePayment method"; },
  "payment.pay_in_installments": function(d) { return "Pay in installments"; },
  "payment.pay_in_store": function(d) { return "Pay in the store"; },
  "payment.pay_ipay": function(d) { return "Pay now with credit card or debit card"; },
  "payment.pay_klarna": function(d) { return "Pay with Klarna - Pay Later"; },
  "payment.pay_klarna_account": function(d) { return "Pay with Klarna - Slice It"; },
  "payment.pay_klarna_paynow": function(d) { return "Pay with Klarna - Pay Now"; },
  "payment.pay_later": function(d) { return ""; },
  "payment.pay_now_with_alamar_wallet": function(d) { return "Use eWallet balance (" + d.availableBalance + ")"; },
  "payment.pay_now_with_amex": function(d) { return "Pay now with American Express"; },
  "payment.pay_now_with_credit_card": function(d) { return "Pay Now with Debit or Credit Card"; },
  "payment.pay_now_with_fac": function(d) { return "Pay now with Credit Card"; },
  "payment.pay_now_with_grabpay": function(d) { return "Pay now with GrabPay"; },
  "payment.pay_now_with_mastercard": function(d) { return "Pay now with MasterCard"; },
  "payment.pay_now_with_moyasar_creditcard": function(d) { return "Credit or Mada Online"; },
  "payment.pay_now_with_mpgs": function(d) { return "Pay online with Credit or Debit card"; },
  "payment.pay_now_with_openpay": function(d) { return "Pay online with Credit or Debit card"; },
  "payment.pay_now_with_paypal3": function(d) { return "Pay now with PayPal"; },
  "payment.pay_now_with_plexo": function(d) { return "Pay now with Credit/Debit Card"; },
  "payment.pay_now_with_transbank": function(d) { return "Pay with WebPay Transbank"; },
  "payment.pay_now_with_vales_cdmx": function(d) { return "CDMX Vouchers at the Door"; },
  "payment.pay_now_with_visa": function(d) { return "Pay now with Visa"; },
  "payment.pay_now_with_visa_master": function(d) { return "Pay now with Visa/Mastercard"; },
  "payment.pay_now_with_visacybersource": function(d) { return "Pay with credit card"; },
  "payment.pay_now_with_wirecard": function(d) { return "Pay now with credit card or PayLah!"; },
  "payment.pay_now_with_wow": function(d) { return "Pay now with "; },
  "payment.pay_on_delivery": function(d) { return "Pay on delivery"; },
  "payment.pay_pix": function(d) { return "Pay with PIX"; },
  "payment.pay_pix_copy_code": function(d) { return "Copy Code"; },
  "payment.pay_pix_copy_success": function(d) { return "Code copied!"; },
  "payment.pay_pix_cpf_cnpj_required": function(d) { return "Payment with PIX requires CPF or CNPJ"; },
  "payment.pay_pix_expired": function(d) { return "The PIX code has expired"; },
  "payment.pay_pix_expiry": function(d) { return "You have " + d.expiryTimer + " to pay"; },
  "payment.pay_pix_instruction_1": function(d) { return "Open the app with your registered PIX key, choose"; },
  "payment.pay_pix_instruction_2": function(d) { return "and scan the QR Code or copy and paste the code"; },
  "payment.pay_scheme": function(d) { return "Pay with Credit Card"; },
  "payment.pay_swish": function(d) { return "Pay with Swish"; },
  "payment.pay_with": function(d) { return "Pay with"; },
  "payment.pay_with_cash_upon_delivery": function(d) { return "Pay with Cash upon Delivery"; },
  "payment.pay_with_cash_upon_delivery_disabled": function(d) { return "Pay with Cash upon Delivery - This store is currently not accepting Cash"; },
  "payment.pay_with_cash_upon_delivery_prepaid": function(d) { return "Pay with Cash upon Delivery (Online Payment Only)"; },
  "payment.payment": function(d) { return "payment"; },
  "payment.payment_information": function(d) { return "Payment Information"; },
  "payment.payment_make": function(d) { return "You are able to make payments with credit and debit card"; },
  "payment.payment_method": function(d) { return "It is a payment method that is easy, quick, and secure."; },
  "payment.payment_note": function(d) { return ""; },
  "payment.payment_people": function(d) { return "More than 100 million people in the world use PayPal"; },
  "payment.payment_processed_return_to_app": function(d) { return "Your payment has been processed, select return to app to complete your order."; },
  "payment.payment_protects": function(d) { return "PayPal protects your information. Financial data is never shared."; },
  "payment.payment_session_cancelled_with_refund": function(d) { return "Your order was cancelled. Though your payment method is charged at this time, we have initiated a refund which should appear in 4-7 business days from now. We apologize for the inconvenience. Please call the store after 7 business days, if you haven’t received the refund."; },
  "payment.payment_type": function(d) { return "Payment Type:"; },
  "payment.paypal": function(d) { return "PayPal"; },
  "payment.paypal_giftcard_warning": function(d) { return "We're sorry, PayPal cannot be used with Gift Cards."; },
  "payment.paypal_what_is_it": function(d) { return "What is PayPal?"; },
  "payment.paypalv3": function(d) { return "PayPal"; },
  "payment.pesalink": function(d) { return ""; },
  "payment.pin": function(d) { return "PIN"; },
  "payment.pix": function(d) { return "PIX"; },
  "payment.place_order": function(d) { return "Place Order"; },
  "payment.place_order_session_refunded": function(d) { return "Sorry there was an error in processing your order. Though your payment method is charged at this time, we have initiated a refund which should appear in 4-7 business days from now. We apologize for the inconvenience. Please call the store after 7 business days, if you haven’t received the refund."; },
  "payment.place_your_easy_order": function(d) { return "Place Your Easy Order"; },
  "payment.place_your_order": function(d) { return "Place Your Order"; },
  "payment.please_bring_change_for": function(d) { return "Please bring change for"; },
  "payment.please_reselect_your_quantity_and": function(d) { return "Please reselect your quantity and try again."; },
  "payment.please_review_your_easy_order_below": function(d) { return "Please review your Easy Order and complete the fields below, then choose a payment type and click \"Save Your Easy Order\"."; },
  "payment.please_review_your_order_below": function(d) { return "Please review your order and complete the fields below, then choose a payment type and click \"Place Your Order\"."; },
  "payment.please_reward_your_driver": function(d) { return "Any Delivery charge is not a tip paid to your driver. Please reward your driver for awesomeness. Our drivers carry less than $20."; },
  "payment.please_select_your_credit_card": function(d) { return "Please select your credit card:"; },
  "payment.please_use_mm_format": function(d) { return ""; },
  "payment.please_use_mm_yy_format": function(d) { return ""; },
  "payment.please_use_pin_pad": function(d) { return "Please Use Pin Pad to Complete Transaction"; },
  "payment.please_use_yy_format": function(d) { return ""; },
  "payment.plexo": function(d) { return "Credit/Debit Card"; },
  "payment.point_redemption_verification": function(d) { return "point redemption verification"; },
  "payment.post_payment_note": function(d) { return "En el evento que sea procedente la devolución del dinero cuando se aplique la garantía de 30 minutos ó gratis el cual aplica cuando el pedido llegue hasta su portería, para pedidos máximo de 4 pizzas; el valor pagado por el consumidor será devuelto por parte de Gastronomía Italiana en Colombia S.A.S. como operador de la marca Domino´s Pizza, dentro de los quince (15) días hábiles siguientes al momento en que se realizo la compra. En caso de presentar alguna o duda sobre el procedimiento por favor comuníquese a XXXXXXXXXXXX o envíenos un correo electrónico a <a href=\"mailto:xxxxxxxxx@dominos.com.co\">xxxxxxxxx@dominos.com.co</a>"; },
  "payment.postfinance": function(d) { return "Post Finance"; },
  "payment.primary_account": function(d) { return "(Primary Account)"; },
  "payment.primary_card": function(d) { return "(Primary Card)"; },
  "payment.qitaf": function(d) { return "Qitaf"; },
  "payment.qitaf_change_phone": function(d) { return ""; },
  "payment.qitaf_instructions_phase_1": function(d) { return ""; },
  "payment.qitaf_partial_amount": function(d) { return ""; },
  "payment.qitaf_partial_payment": function(d) { return ""; },
  "payment.qitaf_pay_with": function(d) { return ""; },
  "payment.qitaf_request_password": function(d) { return ""; },
  "payment.qty": function(d) { return "Qty."; },
  "payment.receipt": function(d) { return ""; },
  "payment.redemption_confirmation": function(d) { return "Let's make sure it's you redeeming points for this order. We've sent a verification code to: "; },
  "payment.reference_no": function(d) { return "Reference No."; },
  "payment.replace_eo_without_placing_order": function(d) { return "Replace your current Easy Order now without placing an order?"; },
  "payment.resend_code": function(d) { return "Resend Code"; },
  "payment.return_to_app": function(d) { return "Return to App"; },
  "payment.reverify_card": function(d) { return "Card Details Re-verification"; },
  "payment.reverify_card_message": function(d) { return "Hi, we are improving our online payment platform, we need you to re-enter your card information and save it to your profile. Thank you for your help and sorry for the inconvenience. See you later!"; },
  "payment.rewardpoints": function(d) { return ""; },
  "payment.rnc_section": function(d) { return ""; },
  "payment.rpsm_pay_now_with_card": function(d) { return "Pay now with card to use our new Express Pick-up Station!"; },
  "payment.ruc": function(d) { return ""; },
  "payment.sadad": function(d) { return "SADAD Account ID:"; },
  "payment.sadadPayment": function(d) { return "Sadad"; },
  "payment.same_delivery": function(d) { return "Same as delivery"; },
  "payment.save_changes_to_my_pizza_profile": function(d) { return "Save changes to my Pizza Profile"; },
  "payment.save_this_order_as_your": function(d) { return "Save this order as your Easy Order."; },
  "payment.scheme": function(d) { return "Credit Card"; },
  "payment.security_code": function(d) { return "Security Code"; },
  "payment.select_more_payment_options": function(d) { return "Please select more payment options to fulfill the order total."; },
  "payment.select_receipt_type": function(d) { return "Select Receipt Type:"; },
  "payment.send_us_a_text_when_arrive": function(d) { return "Send us a text when you arrive by responding \"HERE\". This will tell the store you have arrived for your order."; },
  "payment.service_method_location": function(d) { return "Service Method &amp; Location"; },
  "payment.show_1_of_2_aria": function(d) { return "Step 1 of 2 Info"; },
  "payment.show_2_of_2_aria": function(d) { return "Step 2 of 2 Payments"; },
  "payment.show_order_summary": function(d) { return "Show order summary"; },
  "payment.sign_in_to_your_pizza_profile": function(d) { return "<a href=\"" + d.ctx + "/pages/customer/" + "#" + "!/customer/login/\" class=\"link-button--sign-in js-login-payment\">Sign In</a> to your Pizza Profile for faster checkout or continue below as guest."; },
  "payment.sign_me_up_now": function(d) { return "Sign me up now!"; },
  "payment.sorry_trouble_processing": function(d) { return "We're having trouble processing your payment. Please see a team member for assistance."; },
  "payment.special_regime": function(d) { return "Special Regime"; },
  "payment.starting_balance": function(d) { return "Starting Balance:"; },
  "payment.swish": function(d) { return "Swish"; },
  "payment.taxid_address": function(d) { return "Official Address"; },
  "payment.taxid_city": function(d) { return "City:"; },
  "payment.taxid_company_name": function(d) { return ""; },
  "payment.taxid_companyname": function(d) { return "Company Name:"; },
  "payment.taxid_customer_name": function(d) { return ""; },
  "payment.taxid_customername": function(d) { return "Customer Name:"; },
  "payment.taxid_dni": function(d) { return ""; },
  "payment.taxid_first_and_last_names": function(d) { return ""; },
  "payment.taxid_pec": function(d) { return "PEC"; },
  "payment.taxid_postalcode": function(d) { return "Postal Code:"; },
  "payment.taxid_registered_name": function(d) { return ""; },
  "payment.taxid_ruc": function(d) { return ""; },
  "payment.taxid_sdi": function(d) { return "SDI"; },
  "payment.taxid_section": function(d) { return "RNC Section"; },
  "payment.taxid_streetname": function(d) { return "Street Name:"; },
  "payment.taxid_streetnumber": function(d) { return "Street Number:"; },
  "payment.taxid_tax_id": function(d) { return ""; },
  "payment.taxid_taxid": function(d) { return ""; },
  "payment.taxid_type_company": function(d) { return ""; },
  "payment.taxid_type_individual": function(d) { return ""; },
  "payment.taxid_type_none": function(d) { return ""; },
  "payment.taxid_vatcode": function(d) { return "VAT Code:"; },
  "payment.this_store_accepts": function(d) { return "This store accepts " + d.acceptedCardsNames + " cards."; },
  "payment.time_remaining_for_this_offer": function(d) { return "Time remaining for this offer"; },
  "payment.tip": function(d) { return "Tip"; },
  "payment.tip_cannot_exceed": function(d) { return "Sorry, your tip cannot exceed " + d.amount + "% of your order total."; },
  "payment.tip_equals_to": function(d) { return "(tip) ="; },
  "payment.tip_is_invalid": function(d) { return "Sorry, your tip is invalid, Please correct it before placing your order."; },
  "payment.tip_pretipping_recommendation": function(d) { return "Pre-payment and pre-tipping are recommended for the best experience."; },
  "payment.tip_too_big": function(d) { return "Sorry, your tip cannot exceed 400% of your order total."; },
  "payment.tip_when_tipping": function(d) { return "When paying online with a Debit Card you may see three transactions. The first for the amount of the order before tip, the second a reversal of this transaction, and a third for the amount of the order with the tip. This behavior varies by bank and the reversing transaction may take up to 5 days to post.<br /><br />NOTE: Each time you click on the “Place Order” button your bank may place a hold on funds in your account. Please make sure you submit the correct Expiration Date, Security Code, and Billing PostalCode."; },
  "payment.tip_your_driver": function(d) { return "Tip Your Driver"; },
  "payment.to_find_another": function(d) { return "to find another."; },
  "payment.to_switch_to_carryout": function(d) { return "to change your order to carryout and receive a special deal."; },
  "payment.total": function(d) { return "Total"; },
  "payment.transbank": function(d) { return "WebPay Transbank"; },
  "payment.try_again_with_card": function(d) { return "Try again with Debit or Credit Card"; },
  "payment.update": function(d) { return "Update"; },
  "payment.update_zip_code": function(d) { return "Update Postal Code"; },
  "payment.updated_payment_duc_removed": function(d) { return "Your order has been updated to in-store carryout to allow payment upon arrival."; },
  "payment.use_another_payment_method": function(d) { return "Use Another Payment Method"; },
  "payment.use_delivery_address": function(d) { return ""; },
  "payment.use_openpay_points": function(d) { return "Please select to use bank points offered on the card"; },
  "payment.use_other_account": function(d) { return "Use Other Account"; },
  "payment.use_other_account_paypal3": function(d) { return "Use other PayPal account"; },
  "payment.use_other_account_visa_cybersource": function(d) { return "Use other card"; },
  "payment.use_other_card": function(d) { return "Use Other Card"; },
  "payment.vales_cdmx": function(d) { return "Vales CDMX"; },
  "payment.valescdmx": function(d) { return ""; },
  "payment.validate": function(d) { return "Validate"; },
  "payment.verve": function(d) { return ""; },
  "payment.visa": function(d) { return "Visa"; },
  "payment.visa_debit": function(d) { return "Visa Debit"; },
  "payment.visa_master": function(d) { return "Visa/Mastercard"; },
  "payment.visacybersource": function(d) { return "Credit Card"; },
  "payment.waiting_notification_message": function(d) { return "The order will be sent to your Domino’s store, which may take a few seconds. Please wait and do not close the window. You will be automatically redirected to the Domino's website"; },
  "payment.want_to_place_order_now": function(d) { return "Want to place your order now?"; },
  "payment.we_accept": function(d) { return "We Accept:"; },
  "payment.we_offer_klarna": function(d) { return "We offer Klarna – Slice It as a payment option for all purchases over"; },
  "payment.well_remember_your_vehicle_information": function(d) { return "We'll remember your vehicle information for your next order."; },
  "payment.where_can_we_find_you": function(d) { return "Where can we find you?"; },
  "payment.where_cvv_body": function(d) { return "For Visa, MasterCard, and Discover cards, the Credit Card Security code (Also known as CVV2 or CVC2 and similar names) is the three-digit number printed on the signature panel on the back of your card that immediately follows the card's account number. For American Express and Optima card holders it is the 4 digit, non raised number printed above your account number on the front of your card. If you need help, please contact your local store or your credit card company."; },
  "payment.where_cvv_heading": function(d) { return "Where is my Credit Card Security Code?"; },
  "payment.why_cvv_body": function(d) { return "Having this information allows us to be sure the account is legitimate and to be more certain that the card is in your possession. This is a safety measure that helps to protect you, Domino's and other valued Domino's customers."; },
  "payment.why_cvv_heading": function(d) { return "Why do we need the Credit Card Security Code?"; },
  "payment.wow_plus": function(d) { return "Wow+"; },
  "payment.wow_plus_balance": function(d) { return "Current Balance: " + d.availableBalance; },
  "payment.yes_add_a_tip_now": function(d) { return "Yes, add a tip now"; },
  "payment.yes_add_a_tip_now_dcd": function(d) { return "Yes, add a tip now (or you can tip when you arrive)"; },
  "payment.yes_i_have_a_dominos": function(d) { return "Yes, I have a Domino's Gift Card."; },
  "payment.you_are_paying": function(d) { return "You are paying"; },
  "payment.you_dont_have_any_saved": function(d) { return "You don't have any saved credit cards."; },
  "payment.you_have_15_minutes_to_complete": function(d) { return ""; },
  "payment.you_have_a_pizza_profile_and_eo": function(d) { return "You now have a Pizza Profile and an Easy Order. Today is a great day"; },
  "payment.your_card_securely_with_easy_order": function(d) { return "Your card information will be securely saved with your Easy Order."; },
  "payment.your_existing_eo": function(d) { return "Your existing easy order"; },
  "payment.your_information": function(d) { return "Your Information"; },
  "payment.your_vehicle_information_duc": function(d) { return "Your vehicle information for Domino's Carside Delivery™"; },
  "payment.youve_exceeded_your_stores_cash": function(d) { return "You've exceeded your store's cash limit of "; }
}
}
);
