define([], function anonymous(
) {
var pluralFuncs = {
  en: function(n, ord) {
    var s = String(n).split('.'), v0 = !s[1], t0 = Number(s[0]) == n,
        n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2);
    if (ord) return (n10 == 1 && n100 != 11) ? 'one'
        : (n10 == 2 && n100 != 12) ? 'two'
        : (n10 == 3 && n100 != 13) ? 'few'
        : 'other';
    return (n == 1 && v0) ? 'one' : 'other';
  }
};
var fmt = {};
var number = function(value, offset) {
  if (isNaN(value)) throw new Error("'" + value + "' isn't a number.");
  return value - (offset || 0);
};
var plural = function(value, offset, lcfunc, data, isOrdinal) {
  if ({}.hasOwnProperty.call(data, value)) return data[value]();
  if (offset) value -= offset;
  var key = lcfunc(value, isOrdinal);
  if (key in data) return data[key]();
  return data.other();
};
var select = function(value, data) {
  if ({}.hasOwnProperty.call(data, value)) return data[value]();
  return data.other()
};

return {
  "entrees.add_another_item": function(d) { return "Add Another Item"; },
  "entrees.add_another_item_to_this_coupon": function(d) { return "Add another item to this coupon"; },
  "entrees.add_to_order": function(d) { return ""; },
  "entrees.add_to_your_total": function(d) { return "Add to Your Total"; },
  "entrees.already_have_a_code": function(d) { return "Already have a code? Enter here"; },
  "entrees.at1684_breads_alt": function(d) { return "Breads"; },
  "entrees.at1684_breads_description": function(d) { return "Experience oven baked goodness with an order of our delicious breads."; },
  "entrees.at1684_breads_title": function(d) { return "Breads"; },
  "entrees.at1684_extras_alt": function(d) { return "Extras"; },
  "entrees.at1684_extras_description": function(d) { return "Don't forget your favorite dipping sauce or dressing."; },
  "entrees.at1684_extras_title": function(d) { return "Extras"; },
  "entrees.at1684_salads_alt": function(d) { return "Salads"; },
  "entrees.at1684_salads_description": function(d) { return "Domino’s Salads, the perfect complement to pizza."; },
  "entrees.at1684_salads_title": function(d) { return "Salads"; },
  "entrees.awaiting_your_delicious_selections": function(d) { return "Awaiting your delicious selections"; },
  "entrees.back_to_menu": function(d) { return "Back to Menu"; },
  "entrees.boxku_alt": function(d) { return "BoxKu"; },
  "entrees.boxku_description": function(d) { return "BoxKu Personal Pizza and Side Meal - a tasty, easy meal for you!"; },
  "entrees.boxku_title": function(d) { return "BoxKu"; },
  "entrees.bread_alt": function(d) { return "Breads"; },
  "entrees.bread_and_oven_baked_dips_alt": function(d) { return "Breads and Oven-Baked Dips"; },
  "entrees.bread_and_oven_baked_dips_title": function(d) { return "Breads & Oven-Baked Dips"; },
  "entrees.bread_description": function(d) { return "Experience oven baked goodness with an order of our delicious breads."; },
  "entrees.bread_title": function(d) { return "Breads"; },
  "entrees.build_your_own_pizza": function(d) { return "Build Your Own Pizza"; },
  "entrees.build_your_own_pizza_alt": function(d) { return ""; },
  "entrees.build_your_own_pizza_title": function(d) { return ""; },
  "entrees.calzone": function(d) { return ""; },
  "entrees.calzone_alt": function(d) { return "Sides"; },
  "entrees.calzone_description": function(d) { return "Complement your meal and your appetite."; },
  "entrees.calzone_title": function(d) { return "Sides"; },
  "entrees.change_store": function(d) { return "Change my store"; },
  "entrees.checkout_without_coupon": function(d) { return "Checkout Without Coupon"; },
  "entrees.cheese_alt": function(d) { return ""; },
  "entrees.cheese_description": function(d) { return ""; },
  "entrees.cheese_title": function(d) { return ""; },
  "entrees.chicken_alt": function(d) { return "Chicken"; },
  "entrees.chicken_description": function(d) { return "Specialty Chicken, Wings, and Boneless Chicken in a selection of bold flavors."; },
  "entrees.chicken_title": function(d) { return "Chicken"; },
  "entrees.click_the_button_to_find": function(d) { return "Click the button to find a coupon that fits you."; },
  "entrees.combo_alt": function(d) { return "Combo"; },
  "entrees.combo_description": function(d) { return ""; },
  "entrees.combo_title": function(d) { return "Combo"; },
  "entrees.complete_coupon": function(d) { return "Complete Coupon"; },
  "entrees.contactless_carryout_msg_2": function(d) { return ""; },
  "entrees.contactless_learn_more": function(d) { return ""; },
  "entrees.contactless_primer_header": function(d) { return "Zero Contact Option"; },
  "entrees.contactless_primer_text_01": function(d) { return "The safety of team members and customers is our priority. We value the trust you place in our brand and our ability to deliver to you safely. We are taking advice from experts and health authorities to add all neccessary precautionary measures."; },
  "entrees.contactless_primer_text_02": function(d) { return "For your protection and the protection of employees, Zero Contact option is provided on the payment page. We have provided instructions and FAQs next to the option for more details. Please contact store for additional details."; },
  "entrees.contactless_primer_text_03": function(d) { return ""; },
  "entrees.contactless_primer_text_04": function(d) { return ""; },
  "entrees.contactless_primer_text_05": function(d) { return ""; },
  "entrees.contactless_primer_text_06": function(d) { return ""; },
  "entrees.coupon_code_applied": function(d) { return "Coupon (" + d.code + ") applied"; },
  "entrees.coupon_complete": function(d) { return "Coupon Complete"; },
  "entrees.coupon_wizard": function(d) { return "Coupon Wizard"; },
  "entrees.coupon_wizard_fulfilled": function(d) { return "Your coupon has been fulfilled"; },
  "entrees.coupon_wizard_step_currentcount_of": function(d) { return "Coupon Wizard : Step " + d.currentCount + " of " + d.totalCount; },
  "entrees.coupons": function(d) { return ""; },
  "entrees.coupons_alt": function(d) { return "Deals"; },
  "entrees.coupons_description": function(d) { return ""; },
  "entrees.coupons_title": function(d) { return "Deals"; },
  "entrees.customize": function(d) { return ""; },
  "entrees.deals_alt": function(d) { return ""; },
  "entrees.deals_title": function(d) { return ""; },
  "entrees.dessert_description": function(d) { return ""; },
  "entrees.desserts_alt": function(d) { return "Lava Crunch Cake"; },
  "entrees.desserts_description": function(d) { return "Satisfy your sweet tooth."; },
  "entrees.desserts_title": function(d) { return "Desserts"; },
  "entrees.dobleseis_alt": function(d) { return ""; },
  "entrees.dobleseis_description": function(d) { return ""; },
  "entrees.dobleseis_title": function(d) { return ""; },
  "entrees.dominos": function(d) { return "Domino's"; },
  "entrees.drinks_alt": function(d) { return "Drinks"; },
  "entrees.drinks_description": function(d) { return "Quench your thirst."; },
  "entrees.drinks_title": function(d) { return "Drinks"; },
  "entrees.easily_add_to_cart": function(d) { return ""; },
  "entrees.easily_add_tots_to_cart": function(d) { return ""; },
  "entrees.ecom43205_combo_items_heading": function(d) { return ""; },
  "entrees.ecom43205_easily_add_items": function(d) { return ""; },
  "entrees.ecom43205_easily_add_to_cart": function(d) { return ""; },
  "entrees.ecom43205_new_items_callout": function(d) { return ""; },
  "entrees.ecom43205_recently_added_items": function(d) { return ""; },
  "entrees.ecom44835_build_your_faster": function(d) { return "Build your order faster!"; },
  "entrees.ecom44835_sign_in_or_create": function(d) { return "Sign in or create an account to view your recent items."; },
  "entrees.ecom44835_thanks_for_signing_up": function(d) { return "Thanks for signing up!"; },
  "entrees.ecom44835_you_will_begin": function(d) { return "You'll begin to see your recent items here once you place an order."; },
  "entrees.ecom56224_build_your_order_faster": function(d) { return "Build your order faster!"; },
  "entrees.ecom56224_or": function(d) { return "or"; },
  "entrees.ecom56224_quickly_add": function(d) { return "Quickly add recently ordered items."; },
  "entrees.ecom56224_sign_in_or_create": function(d) { return "Sign in or create an account to view your recently ordered items."; },
  "entrees.ecom56224_thanks_for_signing_up": function(d) { return "Thanks for signing up!"; },
  "entrees.ecom56224_you_will_begin": function(d) { return "You'll begin to see your recent items here once you place an order."; },
  "entrees.enter_promotion_or_coupon_code": function(d) { return "Enter promotion or coupon code"; },
  "entrees.epic_alt": function(d) { return ""; },
  "entrees.epic_description": function(d) { return ""; },
  "entrees.epic_title": function(d) { return ""; },
  "entrees.estimated_carryout_time": function(d) { return "est. " + d.serviceMethod + " time"; },
  "entrees.estimated_delivery_time": function(d) { return "est. " + d.serviceMethod + " time"; },
  "entrees.estimated_wait_carryout": function(d) { return ""; },
  "entrees.estimated_wait_minutes_average_carryout": function(d) { return "Your " + d.serviceMethod + " will be ready in about " + d.minutes + " minutes after you place your order."; },
  "entrees.estimated_wait_minutes_average_delivery": function(d) { return "Your " + d.serviceMethod + " will be ready in about " + d.minutes + " minutes after you place your order."; },
  "entrees.extras_alt": function(d) { return "Extras"; },
  "entrees.extras_description": function(d) { return ""; },
  "entrees.extras_title": function(d) { return "Extras"; },
  "entrees.famous_alt": function(d) { return ""; },
  "entrees.famous_description": function(d) { return ""; },
  "entrees.famous_title": function(d) { return ""; },
  "entrees.faq_link": function(d) { return "Looking for something? Visit our <a href='/pages/content/customer-service/faq?faqsection=nationalmenu&subsection=looking' class='js-goToPage'>FAQ page.</a>"; },
  "entrees.featured_items": function(d) { return "Featured Items"; },
  "entrees.feeds_feeds": function(d) { return "Feeds " + d.feeds; },
  "entrees.find_a_coupon": function(d) { return "Find a Coupon"; },
  "entrees.find_the_perfect_hot_online": function(d) { return "Find the perfect hot online deal."; },
  "entrees.from": function(d) { return "From:"; },
  "entrees.gifts_alt": function(d) { return "Gifts"; },
  "entrees.gifts_description": function(d) { return ""; },
  "entrees.gifts_title": function(d) { return "Gifts"; },
  "entrees.gluten_free_alt": function(d) { return "Guten Free Pizza"; },
  "entrees.gluten_free_description": function(d) { return "Build your own 10 inch gluten free crust pizza"; },
  "entrees.gluten_free_title": function(d) { return "Gluten Free Pizza"; },
  "entrees.half_and_half_panel_description": function(d) { return "Torn between two pizzas? Why not have both of them? Two sides on one base."; },
  "entrees.half_and_half_panel_title": function(d) { return "Half & Half"; },
  "entrees.have_a_coupon_or_promotion": function(d) { return "Have a coupon or promotion code?"; },
  "entrees.hot_deals": function(d) { return "Hot Deals"; },
  "entrees.i_already_have_a_coupon": function(d) { return "I already have a coupon."; },
  "entrees.i_dont_have_a_coupon": function(d) { return "I don't have a coupon."; },
  "entrees.incomplete_coupon": function(d) { return "Incomplete Coupon"; },
  "entrees.loaded_tots_alt": function(d) { return "Loaded Tots"; },
  "entrees.loaded_tots_description": function(d) { return ""; },
  "entrees.loaded_tots_title": function(d) { return "Loaded Tots"; },
  "entrees.loyalty_cancel_redemption": function(d) { return "Cancel Redemption"; },
  "entrees.loyalty_coupon_complete": function(d) { return "Complete"; },
  "entrees.loyalty_coupon_remove": function(d) { return "Remove Reward"; },
  "entrees.loyalty_coupon_wizard_complete": function(d) { return "Congrats on your redemption. Go You! Once you checkout, rewards points will be removed from your account. Did we mention you’re one of our most favorite customers ever? Don’t tell the others."; },
  "entrees.loyalty_join": function(d) { return "Introducing Piece of the Pie Rewards.  Join Today - Start earning points toward free pizza!"; },
  "entrees.loyalty_join_button_text": function(d) { return "Join Now"; },
  "entrees.minute_abbreviation": function(d) { return "mins"; },
  "entrees.n": function(d) { return ""; },
  "entrees.new": function(d) { return "New!"; },
  "entrees.new_alt": function(d) { return ""; },
  "entrees.new_description": function(d) { return ""; },
  "entrees.new_item": function(d) { return "New item!"; },
  "entrees.new_title": function(d) { return ""; },
  "entrees.no_time_to_waste_choose": function(d) { return "No time to waste? Choose a meal and head straight for checkout."; },
  "entrees.order_here": function(d) { return "Order Here"; },
  "entrees.past_orders": function(d) { return "Past Orders"; },
  "entrees.pasta_alt": function(d) { return "Penne Pasta"; },
  "entrees.pasta_description": function(d) { return "Prepared to order and baked to perfection."; },
  "entrees.pasta_title": function(d) { return "Pasta"; },
  "entrees.personal": function(d) { return ""; },
  "entrees.pizza_description": function(d) { return ""; },
  "entrees.please_enter_your_coupon_or": function(d) { return "Please enter your coupon or promotion code:"; },
  "entrees.popular_items": function(d) { return "Popular Items"; },
  "entrees.price_order": function(d) { return "Price Order"; },
  "entrees.product_filter_all": function(d) { return "All"; },
  "entrees.product_filter_search_example": function(d) { return "Roasted chicken, mushrooms, ..."; },
  "entrees.product_filter_search_products": function(d) { return "Search Products:"; },
  "entrees.recently_added_items": function(d) { return ""; },
  "entrees.redeem_now": function(d) { return "Redeem Now"; },
  "entrees.redemptionComplete": function(d) { return "Complete"; },
  "entrees.remove_coupon": function(d) { return "Remove coupon"; },
  "entrees.reorder_recent_items": function(d) { return "Easily reorder your recent items"; },
  "entrees.rice_alt": function(d) { return "Rice Bowls"; },
  "entrees.rice_description": function(d) { return "Hot delicious rice bowl made with jasmin rice."; },
  "entrees.rice_title": function(d) { return "Rice Bowls"; },
  "entrees.salad_alt": function(d) { return "Salad"; },
  "entrees.salad_description": function(d) { return "Domino's Salads, the perfect complement to pizza."; },
  "entrees.salad_title": function(d) { return "Salad"; },
  "entrees.sandwiches_alt": function(d) { return "Oven Baked Sandwiches"; },
  "entrees.sandwiches_description": function(d) { return "All on artisan bread with premium ingredients and baked to perfection."; },
  "entrees.sandwiches_sides_and_desserts": function(d) { return "Sides and Desserts"; },
  "entrees.sandwiches_title": function(d) { return "Oven Baked Sandwiches"; },
  "entrees.select_your_options_in_this": function(d) { return "Select your options in this wizard."; },
  "entrees.selfie_alt": function(d) { return ""; },
  "entrees.selfie_description": function(d) { return ""; },
  "entrees.selfie_title": function(d) { return "Value Range"; },
  "entrees.show_fewer_items": function(d) { return "Show Fewer Items"; },
  "entrees.show_more_items": function(d) { return "Show More Items"; },
  "entrees.showing_x_of_x": function(d) { return "showing " + d.visibleItemCount + " of " + d.totalItemCount; },
  "entrees.sides_alt": function(d) { return "Sides"; },
  "entrees.sides_category_name": function(d) { return "Sides and desserts"; },
  "entrees.sides_description": function(d) { return "Complement your meal and your appetite."; },
  "entrees.sides_title": function(d) { return "Sides"; },
  "entrees.sidesdesserts_alt": function(d) { return ""; },
  "entrees.sidesdesserts_description": function(d) { return ""; },
  "entrees.sidesdesserts_title": function(d) { return ""; },
  "entrees.sidesdrinks_alt": function(d) { return "Sides"; },
  "entrees.sidesdrinks_description": function(d) { return "Complement your meal and your appetite."; },
  "entrees.sidesdrinks_title": function(d) { return "Sides"; },
  "entrees.smallie_description": function(d) { return "Taste the extra with our small but mighty Smallie pizzas"; },
  "entrees.smallie_title": function(d) { return "Smallie"; },
  "entrees.specialty_pizza": function(d) { return ""; },
  "entrees.specialtypizza_alt": function(d) { return "Pick a Feast Pizza"; },
  "entrees.specialtypizza_description": function(d) { return "Enjoy one of our chef-inspired pizza combinations."; },
  "entrees.specialtypizza_national_title": function(d) { return "Pizza and Pasta"; },
  "entrees.specialtypizza_title": function(d) { return "Feast Pizzas"; },
  "entrees.step_currentcount_of_totalcount": function(d) { return "Step " + d.currentCount + " of " + d.totalCount; },
  "entrees.store_selected": function(d) { return "You have selected " + d.storeAddress + " for your carryout order."; },
  "entrees.supreme_alt": function(d) { return ""; },
  "entrees.supreme_description": function(d) { return ""; },
  "entrees.supreme_title": function(d) { return ""; },
  "entrees.tap_to_reorder": function(d) { return "Tap to easily reorder your recent items."; },
  "entrees.the_prices_shown_are_for_the_small_size": function(d) { return "The prices shown are for the \"Small\" size"; },
  "entrees.traditional_alt": function(d) { return ""; },
  "entrees.traditional_description": function(d) { return ""; },
  "entrees.traditional_title": function(d) { return ""; },
  "entrees.watch_the_pizza_of_your": function(d) { return "Watch the pizza of your wildest dreams come to life."; },
  "entrees.would_you_like": function(d) { return "Would you like to add this coupon to your order?"; },
  "entrees.your_recent_items": function(d) { return "Your Recent Items"; }
}
}
);
