define([], function anonymous(
) {
var pluralFuncs = {
  en: function(n, ord) {
    var s = String(n).split('.'), v0 = !s[1], t0 = Number(s[0]) == n,
        n10 = t0 && s[0].slice(-1), n100 = t0 && s[0].slice(-2);
    if (ord) return (n10 == 1 && n100 != 11) ? 'one'
        : (n10 == 2 && n100 != 12) ? 'two'
        : (n10 == 3 && n100 != 13) ? 'few'
        : 'other';
    return (n == 1 && v0) ? 'one' : 'other';
  }
};
var fmt = {};
var number = function(value, offset) {
  if (isNaN(value)) throw new Error("'" + value + "' isn't a number.");
  return value - (offset || 0);
};
var plural = function(value, offset, lcfunc, data, isOrdinal) {
  if ({}.hasOwnProperty.call(data, value)) return data[value]();
  if (offset) value -= offset;
  var key = lcfunc(value, isOrdinal);
  if (key in data) return data[key]();
  return data.other();
};
var select = function(value, data) {
  if ({}.hasOwnProperty.call(data, value)) return data[value]();
  return data.other()
};

return {
  "forms.Maximum_characters_you_have": function(d) { return ""; },
  "forms._": function(d) { return "?"; },
  "forms.activate": function(d) { return "Activate"; },
  "forms.add": function(d) { return "Add"; },
  "forms.add_coupon": function(d) { return "Add Coupon"; },
  "forms.agree_terms_of_use": function(d) { return ""; },
  "forms.alternate_phone_number": function(d) { return "Alternate Phone Number"; },
  "forms.arrive_for_your_order": function(d) { return "When you arrive, tap <b>“I’M HERE”</b> on the Domino's Tracker or in your confirmation email. It will tell the store you have arrived for your order."; },
  "forms.attention": function(d) { return "Attention!"; },
  "forms.callback_and_text": function(d) { return "Callback and Text Number"; },
  "forms.callback_phone": function(d) { return "Callback Phone " + "#"; },
  "forms.cancel": function(d) { return "Cancel"; },
  "forms.career_comments": function(d) { return ""; },
  "forms.characters_left": function(d) { return " characters left."; },
  "forms.clear": function(d) { return "Clear"; },
  "forms.click_unsubscribe": function(d) { return "Click 'UNSUBSCRIBE' below to stop receiving survey emails."; },
  "forms.comments": function(d) { return "Comments"; },
  "forms.comments_label": function(d) { return "You may include any helpful details about your experience, such as the order number. Please do not include additional personal information (i.e. social security, credit card information, etc.) in the field below. The Dominos's Customer Care Team will contact you if additional information is required."; },
  "forms.confirm": function(d) { return "Confirm"; },
  "forms.confirm_email_address": function(d) { return ""; },
  "forms.continue": function(d) { return "Continue"; },
  "forms.country_code": function(d) { return "Country Code"; },
  "forms.coupon_code": function(d) { return "Coupon Code"; },
  "forms.coupon_continue": function(d) { return "Continue To Coupons"; },
  "forms.coupon_not_complete": function(d) { return "Coupon not complete"; },
  "forms.current_password": function(d) { return ""; },
  "forms.duc_consent_for_three_texts": function(d) { return "** By checking this box, you consent to receive up to 3 text messages for this order from 88607. Message and data rates may apply. "; },
  "forms.duc_less_toggle": function(d) { return "Less Information &" + "#" + "x25be;"; },
  "forms.duc_more_toggle": function(d) { return "More Information &" + "#" + "x25b8;"; },
  "forms.duc_opt_out_disclaimer": function(d) { return "To opt out of receiving further text messages with this order, send the word STOP to 88607 at any time. You understand and agree that text messages sent to your mobile phone/device may be generated using automated technology. Your consent to receive text messages is not required to make a purchase."; },
  "forms.duc_required_for_duc": function(d) { return "Required for Domino's Carside Delivery™"; },
  "forms.duc_text_messages_required": function(d) { return "(text messages required for Domino's Carside Delivery™)"; },
  "forms.ecom47364_cpd_text_messages_required": function(d) { return "(text messages required for Curbside Pickup)"; },
  "forms.ecom47364_required_for_cpd_orders": function(d) { return "Required for Curbside Pickup orders. By checking this box, you consent to receive up to five text messages regarding your order from 88607. Message and data rates may apply."; },
  "forms.email": function(d) { return "Email"; },
  "forms.emailOptIn": function(d) { return "Yes"; },
  "forms.email_address": function(d) { return "Email Address"; },
  "forms.email_offers": function(d) { return "<span class=\"dominosColor2 yes\">Yes!</span> I would like to receive <strong>exclusive</strong> e-mail coupons from Domino's"; },
  "forms.email_optin_20_off_confirmation": function(d) { return "Hot deals coming your way! Thanks for signing up."; },
  "forms.email_optin_20_off_guest_note": function(d) { return "Want offers & coupons delivered straight to your inbox? A new email address will receive a coupon for 20% off your next order!"; },
  "forms.email_optin_20_off_profiled_note": function(d) { return "Yes, I want to receive email offers from Domino’s and a coupon for 20% off my next order (applies only to new email sign ups)."; },
  "forms.enroll_and_checkout": function(d) { return "Activate Rewards"; },
  "forms.enroll_and_continue": function(d) { return "Enroll & Continue"; },
  "forms.evaluate": function(d) { return "Evaluate"; },
  "forms.example": function(d) { return "Example:"; },
  "forms.franchise_opportunities": function(d) { return ""; },
  "forms.go_to_homepage": function(d) { return "Go back to dominos.com homepage"; },
  "forms.got_a_coupon": function(d) { return "Got a coupon code? Enter it below."; },
  "forms.hide": function(d) { return "hide"; },
  "forms.indicates_required_field": function(d) { return "Indicates required field."; },
  "forms.installment": function(d) { return "Installment"; },
  "forms.kiosk_email": function(d) { return "Domino’s Piece of the Pie Rewards&reg; members can earn points for orders of $10 or more by providing their email address. Or you can enter your email address above to receive a confirmation email for this order."; },
  "forms.less_likely": function(d) { return "Less Likely"; },
  "forms.maximum_characters_you_have": function(d) { return "Maximum 1000 characters, you have "; },
  "forms.message": function(d) { return "Message"; },
  "forms.missing_mandatory_information": function(d) { return "Missing Mandatory Information"; },
  "forms.mm": function(d) { return "MM"; },
  "forms.mobile_phone_number": function(d) { return "Mobile Phone Number"; },
  "forms.more_likely": function(d) { return "More Likely"; },
  "forms.new": function(d) { return "New"; },
  "forms.new_password": function(d) { return "New Password"; },
  "forms.no": function(d) { return "No"; },
  "forms.no_keep_address_CA": function(d) { return "No, Keep Address"; },
  "forms.no_offers": function(d) { return "I no longer want to receive emails from Domino's containing offers or promotions"; },
  "forms.no_surveys": function(d) { return "I no longer want to receive emails from Domino's containing surveys"; },
  "forms.no_surveys_or_offers": function(d) { return "I no longer want to receive either of these types of emails from Domino's"; },
  "forms.notemailOptIn": function(d) { return "No"; },
  "forms.notes": function(d) { return "Notes"; },
  "forms.numbers_only": function(d) { return "(Numbers only. Please do NOT include any special characters and alphabets. For additional address information, please include it below under Delivery Instructions)"; },
  "forms.or_go_to_homepage": function(d) { return "Or, go to dominos.com homepage"; },
  "forms.ordering_phone_number": function(d) { return "Ordering Phone Number"; },
  "forms.other": function(d) { return "Other"; },
  "forms.password": function(d) { return "Password"; },
  "forms.password_hint_combination": function(d) { return "Including a combination of numbers and letters"; },
  "forms.password_hint_minimum_characters": function(d) { return "Creating a password with a minimum of 8 characters"; },
  "forms.password_hint_mixture": function(d) { return "Using a mixture of upper and lowercase letters"; },
  "forms.password_hint_not_reusing": function(d) { return "Not reusing passwords you use on other sites"; },
  "forms.password_hint_one_special_character": function(d) { return "Adding at least one special character (ie: !@^" + "#" + "%)"; },
  "forms.password_hint_title": function(d) { return "Please create a strong, unique password by:"; },
  "forms.password_not_previously_used": function(d) { return "Please enter a password that has not previously been used."; },
  "forms.phone_extension": function(d) { return "Phone Extension"; },
  "forms.phone_fixed": function(d) { return ""; },
  "forms.phone_number": function(d) { return "Phone Number"; },
  "forms.pickup_details": function(d) { return "Pickup Details"; },
  "forms.pickup_preference": function(d) { return "Preferred Location"; },
  "forms.pickup_preference_back_seat": function(d) { return "Back Seat"; },
  "forms.pickup_preference_decide_later": function(d) { return "I'll decide when I arrive"; },
  "forms.pickup_preference_driver_side": function(d) { return "Driver Side"; },
  "forms.pickup_preference_let_us_know": function(d) { return "- Let us know where to leave your order -"; },
  "forms.pickup_preference_passenger_side": function(d) { return "Passenger Side"; },
  "forms.pickup_preference_pickup_window": function(d) { return "Pick-Up Window"; },
  "forms.pickup_preference_trunk": function(d) { return "Trunk"; },
  "forms.placeholder_address": function(d) { return "Address"; },
  "forms.placeholder_city": function(d) { return "City"; },
  "forms.placeholder_date": function(d) { return "Date"; },
  "forms.placeholder_email": function(d) { return "Email Address"; },
  "forms.placeholder_ext": function(d) { return "Ext."; },
  "forms.placeholder_first_name": function(d) { return "First Name"; },
  "forms.placeholder_full_name": function(d) { return "Full Name"; },
  "forms.placeholder_invoice": function(d) { return "Invoice " + "#"; },
  "forms.placeholder_last_name": function(d) { return "Last Name"; },
  "forms.placeholder_mobile_phone": function(d) { return "Mobile Phone"; },
  "forms.placeholder_name": function(d) { return "Name"; },
  "forms.placeholder_notes": function(d) { return "Notes"; },
  "forms.placeholder_phone": function(d) { return "Phone"; },
  "forms.placeholder_phone_prefix": function(d) { return "Country"; },
  "forms.placeholder_postal_code": function(d) { return "Postal Code"; },
  "forms.placeholder_select_area": function(d) { return "select a area"; },
  "forms.placeholder_store_address": function(d) { return "Store Address"; },
  "forms.placeholder_store_name": function(d) { return "Store Name"; },
  "forms.placeholder_store_number": function(d) { return "Store" + "#" + "/Name"; },
  "forms.placeholder_store_phone": function(d) { return "Store Phone"; },
  "forms.placeholder_suburb": function(d) { return "Suburb"; },
  "forms.please_fill_in_the_form_below": function(d) { return "Please fill in the form below and we will contact you shortly"; },
  "forms.please_include_a_message": function(d) { return "Please include a message below."; },
  "forms.primary_phone_number": function(d) { return "Primary Phone Number"; },
  "forms.recaptcha_note": function(d) { return "Please help us protect your account by checking \"I'm not a robot\""; },
  "forms.recaptcha_retry": function(d) { return "Sorry, something went wrong. Please try again."; },
  "forms.receive_e-post_offers": function(d) { return ""; },
  "forms.receive_email_offers": function(d) { return "Receive email offers"; },
  "forms.receive_sms_offers": function(d) { return "Receive SMS offers"; },
  "forms.redeem": function(d) { return "Redeem"; },
  "forms.remind_me_later": function(d) { return ""; },
  "forms.required_for_duc_orders": function(d) { return "Required for Domino's Carside Delivery™ orders. By checking this box, you consent to receive up to five text messages regarding your order from 88607. Message and data rates may apply."; },
  "forms.reset_password": function(d) { return "Password Reset!"; },
  "forms.save": function(d) { return "Save"; },
  "forms.save_changes": function(d) { return "Save Changes"; },
  "forms.save_password": function(d) { return "Save Password"; },
  "forms.security_code": function(d) { return "Security Code"; },
  "forms.select": function(d) { return "- select -"; },
  "forms.send": function(d) { return "Send"; },
  "forms.show": function(d) { return "show"; },
  "forms.sign_in": function(d) { return "Sign In"; },
  "forms.sign_in_and_earn_rewards": function(d) { return "sign in &amp; earn rewards"; },
  "forms.sign_in_continue": function(d) { return "sign in & continue"; },
  "forms.sign_in_loyalty": function(d) { return "SIGN IN to earn points toward FREE PIZZA on this order!"; },
  "forms.sign_in_with_apple": function(d) { return "Sign in with Apple"; },
  "forms.sign_in_with_facebook": function(d) { return "Sign in with Facebook"; },
  "forms.sign_in_with_google": function(d) { return "Sign in with Google"; },
  "forms.sorry_to_see_you_go": function(d) { return "We're sorry to see you go!"; },
  "forms.subject_label": function(d) { return "Subject"; },
  "forms.submit": function(d) { return "Submit"; },
  "forms.submit_changes": function(d) { return "submit changes"; },
  "forms.submit_feedback": function(d) { return "Submit Feedback"; },
  "forms.subscription_preference": function(d) { return "Subscription Preference"; },
  "forms.test": function(d) { return ""; },
  "forms.to_find": function(d) { return "To find"; },
  "forms.unsubscribe": function(d) { return "Unsubscribe"; },
  "forms.unsubscribe_requested": function(d) { return "We have received your unsubscribe request. Please allow 4-6 days for processing."; },
  "forms.use_at_least_8_chara cters": function(d) { return ""; },
  "forms.use_at_least_8_characters": function(d) { return "Password must be at least 8 characters."; },
  "forms.vehicle_cell_phone_number": function(d) { return "Cell Phone " + "#"; },
  "forms.vehicle_color": function(d) { return "Vehicle Colour"; },
  "forms.vehicle_color_black": function(d) { return "Black"; },
  "forms.vehicle_color_blue": function(d) { return "Blue"; },
  "forms.vehicle_color_brown": function(d) { return "Brown"; },
  "forms.vehicle_color_gold": function(d) { return "Gold"; },
  "forms.vehicle_color_gray": function(d) { return "Gray"; },
  "forms.vehicle_color_green": function(d) { return "Green"; },
  "forms.vehicle_color_orange": function(d) { return "Orange"; },
  "forms.vehicle_color_purple": function(d) { return "Purple"; },
  "forms.vehicle_color_red": function(d) { return "Red"; },
  "forms.vehicle_color_silver": function(d) { return "Silver"; },
  "forms.vehicle_color_tan": function(d) { return "Tan"; },
  "forms.vehicle_color_white": function(d) { return "White"; },
  "forms.vehicle_color_yellow": function(d) { return "Yellow"; },
  "forms.vehicle_make": function(d) { return "Vehicle Make"; },
  "forms.vehicle_make_acura": function(d) { return "Acura"; },
  "forms.vehicle_make_alfa_romeo": function(d) { return "Alfa Romeo"; },
  "forms.vehicle_make_aston_martin": function(d) { return "Aston Martin"; },
  "forms.vehicle_make_audi": function(d) { return "Audi"; },
  "forms.vehicle_make_bentley": function(d) { return "Bentley"; },
  "forms.vehicle_make_bmw": function(d) { return "BMW"; },
  "forms.vehicle_make_bugatti": function(d) { return "Bugatti"; },
  "forms.vehicle_make_buick": function(d) { return "Buick"; },
  "forms.vehicle_make_cadillac": function(d) { return "Cadillac"; },
  "forms.vehicle_make_chevrolet": function(d) { return "Chevrolet"; },
  "forms.vehicle_make_chrystler": function(d) { return "Chrysler"; },
  "forms.vehicle_make_dodge": function(d) { return "Dodge"; },
  "forms.vehicle_make_ferrari": function(d) { return "Ferrari"; },
  "forms.vehicle_make_fiat": function(d) { return "Fiat"; },
  "forms.vehicle_make_ford": function(d) { return "Ford"; },
  "forms.vehicle_make_general_motors": function(d) { return "General Motors"; },
  "forms.vehicle_make_gmc": function(d) { return "GMC"; },
  "forms.vehicle_make_honda": function(d) { return "Honda"; },
  "forms.vehicle_make_hyundai": function(d) { return "Hyundai"; },
  "forms.vehicle_make_infiniti": function(d) { return "Infiniti"; },
  "forms.vehicle_make_jaguar": function(d) { return "Jaguar"; },
  "forms.vehicle_make_jeep": function(d) { return "Jeep"; },
  "forms.vehicle_make_kia": function(d) { return "Kia"; },
  "forms.vehicle_make_land_rover": function(d) { return "Land Rover"; },
  "forms.vehicle_make_lexus": function(d) { return "Lexus"; },
  "forms.vehicle_make_lincoln": function(d) { return "Lincoln"; },
  "forms.vehicle_make_maserati": function(d) { return "Maserati"; },
  "forms.vehicle_make_mazda": function(d) { return "Mazda"; },
  "forms.vehicle_make_mercedes_benz": function(d) { return "Mercedes-Benz"; },
  "forms.vehicle_make_mini": function(d) { return "Mini"; },
  "forms.vehicle_make_mitsubishi": function(d) { return "Mitsubishi"; },
  "forms.vehicle_make_nissan": function(d) { return "Nissan"; },
  "forms.vehicle_make_oldsmobile": function(d) { return "Oldsmobile"; },
  "forms.vehicle_make_pontiac": function(d) { return "Pontiac"; },
  "forms.vehicle_make_porsche": function(d) { return "Porsche"; },
  "forms.vehicle_make_ram": function(d) { return "Ram"; },
  "forms.vehicle_make_saab": function(d) { return "Saab"; },
  "forms.vehicle_make_subaru": function(d) { return "Subaru"; },
  "forms.vehicle_make_suzuki": function(d) { return "Suzuki"; },
  "forms.vehicle_make_tesla": function(d) { return "Tesla"; },
  "forms.vehicle_make_toyota": function(d) { return "Toyota"; },
  "forms.vehicle_make_volkswagen": function(d) { return "Volkswagen"; },
  "forms.vehicle_make_volvo": function(d) { return "Volvo"; },
  "forms.vehicle_model": function(d) { return "Vehicle Model"; },
  "forms.vehicle_plate": function(d) { return "Plate Number"; },
  "forms.verify_now": function(d) { return "Verify"; },
  "forms.we_are_missing_mandatory_information": function(d) { return "Oops we are missing information to complete the order."; },
  "forms.we_sent_an_email": function(d) { return "We've sent an email!"; },
  "forms.why_do_we_need_this": function(d) { return "Why do we need this?"; },
  "forms.yes": function(d) { return "Yes"; },
  "forms.yes_change_address_CA": function(d) { return "Yes, Change Address"; },
  "forms.yy": function(d) { return "YY"; }
}
}
);
